### ISSUE TITLE
In 4.9.0 the treegrid opens with all levels open and cannot close/open levels

### ISSUE THREAD

**Issue by zoltan-fedor** [free-jqgrid/jqGrid#104]
It seems that in 4.9.0 the standard treegrid example doesn't work anymore - when opens it opens with all levels open and the opening / closing of levels doesn't work.
The same code works fine in 4.8.0.

Please try 4.8.0 : http://broadcast-this.com/treegrid-4.8.0.php
Then try 4.9.0 : http://broadcast-this.com/treegrid-4.9.0.php

The only difference between the two examples are the jqgrid version in line 25 : 
http://cdn.jsdelivr.net/free-jqgrid/4.8.0/js/jquery.jqgrid.src.js
http://cdn.jsdelivr.net/free-jqgrid/4.9.0/js/jquery.jqgrid.src.js

**Comment by zoltan-fedor** [comment]
Hups, I just read the note about all the changes to the treegrid in 4.9.0, so it seems the json data should be different (no levels and such).
Is there an example how to use the new additionalProperties to set all these?

**Comment by zoltan-fedor** [comment]
Ignore, I switched over to adjacency model and then it worked, see http://broadcast-this.com/treegrid-4.9.0-3.php
I'm not sure what has changed about the handling of the nested model since 4.8.0 making the above example which has worked in 4.8.0 not to work in 4.9.0, but I'm okey to use the adjacency model with 4.9.0.

I keep this ticket open, as the example with the nested model still doesn't work and I would like to know why not, but for now I have a workaround (use the adjacency model).

**Comment by OlegKi** [comment]
First of all I was a little confused because you wrote "The only difference between the two examples are the jqgrid version in line 25", but I see another data in the first demos. Analyzing of the code I could see that you should **different** URL for data, different data and even the format of the data is absolutely another: the demo 4.8.0 uses `treeGridModel: 'nested'` (with `"lft"` and `"rgt"` instead of `parent_id`).

Many parts of the code of TreeGrid and full code for loading JSON/XML data are full rewritten in jqGrid 4.9.0. I tried to hold compatibility, but I don't analysed the code for wrong parameters and wrong input data.
1. You used `"treeGridModel":"nested"` option and the corresponding `treeReader` with data returned from the server in `treeGridModel: 'adjacency'` format.
2. You defines hidden columns `lft`, `rgt`, `level` which breaks processing of jqGrid. The names of columns are reserved for TreeGrid properties. Old versions of jqGrid saves the properties in local `data` **and** created additional hidden columns. Free jqGrid 4.9.0 **don't create** the hidden columns, but the existence of columns with the reserved names can break the standard processing of the grid loading. **You should remove hidden columns `lft`, `rgt`, `level` from `colModel`**.
3. Some demos (http://broadcast-this.com/treegrid-4.9.0-3.php for example) uses `"loadonce":true` in combination with `"treeGrid":true` which have no sense. TreeGrid saves the loaded data in `data` option, but it works not like standard Grid with `loadonce: true`. There are many tests in the code for `loadonce` and I can't validate whether the usage of **wrong** option `loadonce: true` have some side effects. So I strictly recommend you to remove the option for TreeGrids.
4. I don't recommend you to use `jQuery(document).ready(function($) {` inside of `<script type="text/javascript">` which you **included in the body**. It can have side effects in different web browsers in combination with different version of jQuery. There are two correct ways: a) placing `<script>` which includes `jQuery(document).ready(function($) {...});` inside of `<head>` b) placing the code **without** `jQuery(document).ready(function($) {...});` inside of `<body>` directly after `<table id="tree"></table>`. I personally prefer the way a) with clear separation of JavaScript code and HTML markup. You can move JavaScript code later in separate .js file holding the same structure of HTML file.

The meaning of hidden `uiicon` column is unclear for me too. There are no input data for the column. I suppose that you wanted to use `treeReader:{icon_field:"uiicon"}` option which would corresponds JSON data used for the demo http://broadcast-this.com/treegrid-4.8.0.php.

I don't recommend you to have hidden `category_id` column with `key:true` if you don't plan **to display** the column in the grid. Instead of that you should just use `jsonReader: { id: "category_id" }` option which inform jqGrid that the rowid should be get from `category_id` property of data.

The usage of `index` property in `colModel` is also not recommended. It's better to remove all the properties if the corresponding values are the same as the values of `name` property.

The next problem: the JSON data used as input for the first demo http://broadcast-this.com/treegrid-4.8.0.php don't have any `isLeaf`, `expanded` and `loaded` properties. The old free jqGrid 4.8.0 code still could load and display the data corectly, but not the new rewritten code of jqGrid 4.9.0.

**Nevertheless thank you for your post!** I analysed the code of jqGrid 4.9.0 with your current input data and can see that it works in another way as free jqGrid 4.8.0 with **undefined** `isLeaf`, `expanded` and `loaded` properties. I will fix the code and will inform you after I'll merge the changes to GitHub.

**Comment by zoltan-fedor** [comment]
Hi Oleg,
Apologies, after I wrote that "The only difference between the two examples are the jqgrid version in line 25" I was experimenting further and by mistake I overwrite the 4.9.0 file, so it ended up being different from the 4.8.0 one in other lines too. Sorry for that.

I have now copied the 4.8.0 file and really only changed the reference to jqgrid in line 25:
http://broadcast-this.com/treegrid-4.9.0-retry.php
http://broadcast-this.com/treegrid-4.8.0.php
The issue is as described originally, so I will wait for your confirmation about the changes you planned and then test again.


Regarding the mess in  http://broadcast-this.com/treegrid-4.9.0-3.php, I was trying out all different things to figure out how to make the treegrid work in 4.9.0 again, after the drop-in replacement from 4.8.0 did not work. This is why  http://broadcast-this.com/treegrid-4.9.0-3.php ended up being a bit of a mess, but at least the treegrid worked, so I was happy to report that it is not that the treegrid wouldn't work at all in 4.9.0
Thanks for all the pointers re the inconsistencies in http://broadcast-this.com/treegrid-4.9.0-3.php, I will clean all those up.

Also, as mentioned above, when you had a chance to make the changes in the code and merge it back to GitHub, I would be happy to test with http://broadcast-this.com/treegrid-4.9.0-retry.php

Thanks!

**Comment by OlegKi** [comment]
Thank you for new demos. I posted just now some fixes. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/NestedTreeGrid49fixed.htm), which uses practically your old code display correct data. I recommend you to try to test the last changes. You can just change URLs to free jqGrid like it's described in [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs). I will analyse your new demos (from your latest comment) too.

**Comment by zoltan-fedor** [comment]
Thanks, yes, I can confirm that the old demo is now fixed, see:
http://broadcast-this.com/treegrid-4.9.0-retry3-old.php
vs
http://broadcast-this.com/treegrid-4.9.0-retry3-fixed.php
(only change between the two is the reference to the currenty version jqgrid in line #25)

**Comment by OlegKi** [comment]
You are welcome! Thanks you too for reporting of the problem. If you think the problem is fixed then I would ask you to close the issue. I prefer to follow the rule, that the person who report the bug and who opens the issue closes it.

I personally don't use `treeGridModel: "nested"` at all. So I would ask you to report any suspected issues and the corresponding demo in the future too. It will help other users of free jqGrid.

**Comment by zoltan-fedor** [comment]
Thank you Oleg, yes the problem is fixed now, so closing this ticket.
Thanks for your quick code fix!
