### ISSUE TITLE
Missing Tony's copyright notice in main license

### ISSUE THREAD

**Issue by vlna** [free-jqgrid/jqGrid#112]
File `LICENSE.md` with main license should contain Tony's copyright notice too, line like `Copyright (c) 2008-2014, Tony Tomov, tony@trirand.com` should be added.

**Comment by OlegKi** [comment]
Sorry, but the most important information from `LICENSE.md` is: **the code is available under GPL v2 and MIT licenses**. I don't removed any persons from separate .js files. See `jqdnr.js`, `jsonxml.js`, `grid.tbltogrid.js`, `grid.custom.js` and many other. You can examine the list of contributors of jqGrid  here: https://github.com/tonytomov/jqGrid/graphs/contributors. I read the discussion which says that changing of licence agreement is possible only if **all contributors** are agreed. I posted a lot of changes to the code of jqGrid (till jqGrid 4.7 release), and implementation of many features and functions. An example is the `setGroupHeaders` method written mostly by me and Wildraid, wildraid@mail.ru (see [the lines](https://github.com/tonytomov/jqGrid/blob/v4.7.0/js/grid.custom.js#L9-L10)). Tony just removed any references to another authors during publishing of jqGrid 4.8 (see [the file](https://github.com/tonytomov/jqGrid/blob/v4.8/js/grid.grouping.js) which contains the same method `setGroupHeaders` but without any references to the authors).

So To be exactly jqGrid and free jqGrid contains results of work on many contributors. I don't know the whole history of jqGrid development. Many code fragments are posted in the trirand forum, which we can't see of gitHub. I just hold all copirights in all js files of jqGrid. I don't want to fill all the persons in `LICENSE.md` because I will be not sure that the list will be full. I included my name just because I made the most changes in the code of free jqGrid and I try to develop it forward.

**Comment by vlna** [comment]
Thanks for explanation of your view.

Important is MIT license allows sublicensing and everyone (Tony too) has **right to sublicense** contributed MIT code (under any MIT compliant license), but important is **to keep all copyright notices** included and don't misinform about authorship.

Every contributor holds copyright for his own piece of code and licenses it under terms of MIT license but Tony holds **main copyright** for whole package. And it is reason why I think Tony should be added to the main license file.

This is my interpretation of jqGrid licensing status and it may make jqGrid commercial use legally safer.

**Comment by OlegKi** [comment]
I don't plan to remove any names from js files. Even the module [grid.pivot.js](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.pivot.js), which is full rewritten with exception of some lines of original code (just parsing of input parameters and call the main part `pivotSetup`), have still reference to Tony.

I don't understand what you mean "holds main copyright for whole package". I don't agree with statement. Free jqGrid is organization unit on GitHub, but currently I'm the only [member](https://github.com/orgs/free-jqgrid/teams/jqgrid) of the team. So I hold correct that the fork "free jqGrid" contains only my name. By the way the files `jquery.jqgrid.min.js` and `jquery.jqgrid.src.js` contains both `Copyright (c) 2008-2014, Tony Tomov, tony@trirand.com` and `Copyright (c) 2014-2015, Oleg Kiriljuk, oleg.kiriljuk@ok-soft-gmbh.com` statements. So the practical meaning of MIT or GPL licences means just reference to the authors and main files of free jqGrd `jquery.jqgrid.min.js` and `jquery.jqgrid.src.js` includes Tony as the author.

I recommend you to compare the existing code of free jqGrid with the code of 4.7 used as basis. The look at the commits statistic (see [here](https://github.com/free-jqgrid/jqGrid/graphs/commit-activity)) can shows that the existing code contains *really a lot of changes*. I try to hold compatibility to the old versions of jqGrid, but the internals of the most methods will be full rewritten step by step. Just one more example: `addXmlData` and `addJSONData` methods, used for filling of the grid with data, are full rewritten too. I will continue rewriting of other parts in the future.
