### ISSUE TITLE
CellBuilder issue with 4.9

### ISSUE THREAD

**Issue by jimmccarthy** [free-jqgrid/jqGrid#119]
Just tried 4.9 and I am getting errors trying to run my app now in getCellBuilder when cm.formatter = "string".  Failing here:

fillOrClearCellBuilder calls...

} else if (typeof cm.formatter === "string") {
  cm.cellBuilder = $.fn.fmatter.getCellBuilder.call(ts, cm.formatter, opt, act || "add");

Error here

	$FnFmatter.getCellBuilder = function (formatType, opts, act) {
		var cellBuilder = $.fn.fmatter[formatType].getCellBuilder;

error: Cannot read property 'getCellBuilder' of undefined on the line: 

$.fn.fmatter[formatType].getCellBuilder;

I don't see a $FnFmatter.string in the code anywhere.

Is this a known issue?

**Comment by jimmccarthy** [comment]
I think this fixes it:

$FnFmatter.getCellBuilder = function (formatType, opts, act) {

  var cellBuilder = $.fn.fmatter[formatType] ?  $.fn.fmatter[formatType].getCellBuilder :     $.fn.fmatter.defaultFormat.getCellBuilder;

**Comment by OlegKi** [comment]
Hi Jim,

thank you for reporting the issue. I'm not sure which value of `formatType` you have. The usage of `formatter: "string"` is wrong because there are no predefined formatter with the name `"string"` (see [the documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter#predefined_format_types)).

I suppose that you defined your custom formatter by extending `$.fn.fmatter`, but in the case the value `$.fn.fmatter[formatType]` should be not undefined. The current test in `$FnFmatter.getCellBuilder` is really wrong in the case and if one use **unknown** value of `formatter` property, like `formatter: "string"` or `formatter: "abcdefg"`.

In any way, I posted [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/1c0a76d67ec1c485093333065c0ae77097be87b9) to improve the compatibility with previous versions which used default formatter in case of an unknown value of `formatter` property. Please reload free jqGrid from [GitHub](https://github.com/free-jqgrid/jqGrid).

By the way the reason of introduction of `getCellBuilder` is improving performance. It's interesting whether you will see the performance improvements in your project.

Best regards
Oleg

**Comment by OlegKi** [comment]
Because I didn't get any confirmation I will close the issue. I hope that the fix which I posed fixed the problem which you had.

**Comment by jimmccarthy** [comment]
Yes all set, sorry I never got back to this.  Thanks.

**Comment by OlegKi** [comment]
Do you use jqGrid 4.9.1 now (or better the latest source from GitHub where one bug is fixed)? Do you have any problems? Please continue reporting of all found problems. It's the only way to fix all bugs in the code.

**Comment by jimmccarthy** [comment]
4.9.0 at the moment.  We will upgrade soon.  Thanks for being so active on this.
