### ISSUE TITLE
Error with  using jQuery 3.0 alpha 1

### ISSUE THREAD

**Issue by herbalite** [free-jqgrid/jqGrid#127]
This is a similar error I'm also getting with the last free original jqGrid version 4.6.0.

I'm using 4.9.1-post

and using jquery 3 alpha 1 ( http://blog.jquery.com/ )
The error I'm getting, with *any* grid using while data is loading, is as following:

    560 TypeError: ts.rows[0] is undefined1 jquery.jqgrid.src.js:5053:3

The code on the line 5053 is 

    ts.grid.cols = ts.rows[0].cells;

The DOM for the shadow table shows shows that ts.rows is a HTMlCollection of size 0. That's why the error occurs.

Debugging further the issue shows me that the problem starts at line 4669

    tbody = document.createElement("tbody");
    ts.appendChild(tbody);
    $self0.addClass(getGuiStyles("grid", "ui-jqgrid-btable")).append(firstr);

while debugging, I noticed that the part

    $self0. ... .append(firstr);

is being rendered without the <tr> tags (set in the firstr variable) with jQuery 3.0 alpha 1

The DOM of shadow table is void of the rows[0] array. With the latest jQuery production release (2.1.4) it does some magic and the rows is filled

The reason I post this error here, is because the jqGrid code does something strange and it looks like a bug, maybe a compatibility hack for old IE versions which took advantage of some jQuery magic. In the readInput function I've seen a hack that  deals with this issue for IE < 9

What the code above was intended to do on the HTML structure of the shadow table is:

    tbody = document.createElement("tbody");
    ts.appendChild(tbody);
    $self0.addClass(getGuiStyles("grid", "ui-jqgrid-btable"));
    $(tbody).append(firstr);

By doing that the HTML structures look correct again, no matter what jQuery version is being used.

However that isn't enough. as ts.rows still is empty.

ts.tBodies[0].children will be set, but changing the code line 5053

    ts.grid.cols = ts.tBodies[0].children;

throws a similar error as the above on line 3372

So I changed line 3372 from

    self.grid.cols = self.rows[0].cells; // update cached first row

to

    self.grid.cols = self.tBodies[0].children; // update cached first row

Well now I got an

   42.777 SyntaxError: An invalid or illegal string was specified1 jquery.jqgrid.src.js:3371:0

Error, because I use jqGrid in an XHTML environment.

That's where I am stuck at this time.

It seems to me that jQuery 3.0 seems to have removed some of it's magic in their DOMmanip function. I'm not sure however how many issues unknown to me would pop up in jqGrid, if I work through all the issues I'm having. I use very few of the jqGrid advanced features. As I said, this problem should pop up immediately when using the alpha version (I'm working with an XHTML framework)

So I think this needs even more testing and debugging, and I leave it up to someone else's discretion to raise the issue with the jQuery developers. 

IMO if the issue is not a bug in jQuery 3.0 alpha, but them removing  some old legacy code to appease older IE versions (and jqGrid relying on that hack), then the fix IMO should be done in jgGrid itself. But so far it appears the jQuery 3.0 alpha breaks a lot of, if not all jgGrid installations ..

**Comment by OlegKi** [comment]
Please could you post some demo which can be used to reproduce the problem. I get just some first demo and modify it to use jQuery 3.0.0-alpha1 and I could not reproduce the problems which you described. Try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/jQuery3alpha1.htm) for example. The data could be loaded without any problems in Chrome, Microsoft Edge (Windows 10), IE11 or Firefox. I could see only some problems in the usage of Datepicker of jQuery UI, but it's another problem. Please post the demo which can be used to reproduce the problem and the test case (step by step instructions to reproduce the problem). Please describe which web browsers you used in your tests.

**Comment by herbalite** [comment]
Your example does work for me too.

So what's the issue? To make a long winded explanation short. the reason is that I serve the page with application/xhtml+xml

In any browser innerHTML and application/xhtml+xml doesn't work well. (To put it mildly).  jqGrid makes extensive use of strings that will be appended or prepended into the DOM. jQuery inserts them using innerHTML. That will raise some issues, except that JQuery in the past has included workarounds for this.

So I have to raise the issue with the jQuery developers. 

Still would be nice if jgGrid would work with XHTML out of the box (i've fixed each and every version time after time, some of the issues you can find in the original jqGrid issues here on github. 

But fixing this particular issue to work no matter what jQuery is doing would require an extensive rewrite of jqGrid.

**Comment by OlegKi** [comment]
What you mean if you write "Your example does work for me too"? Do you can open [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/jQuery3alpha1.htm)? Do you see the results like on the picture below?
![jquery3a1](https://cloud.githubusercontent.com/assets/249117/8989980/ba89e050-36ef-11e5-87c1-084d94a976d1.png)
If you don't see the grid, please write me which web browser in which version you used. You wrote in your first post in the issue: "The error I'm getting, with *any* grid using while data is loading". So I get just the first simple demo and tried to reproduced the reported problem.

You wrote about `application/xhtml+xml`, but it is just MIME media type, which can be used by web server as *additional information* to the main HTML/XHTML page. It's unclear for me another more important part: which XHTML standard you use in your tests. [The modified demo](http://www.ok-soft-gmbh.com/jqGrid/OK/jQuery3alpha1_.htm) for example uses XHTML 1.0 Strict standard and I see no problem with the demo too.

I think that we will don't do forward if you don't provides **your demo which can be used to reproduce the problem**. Please write the test case (step by step instructions to reproduce the problem) too and inform me which web browsers and in which version you used to reproduce your problem. If you prepare the demo, please use non-minimizes files direct from GitHub (see [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)). In the way I will be able not only reproduce the problem, but to verify that the problem is fixed after I post the corresponding bug fix.

About you common remarks about "extensive use of strings" I can write that jqGrid code uses the technique *to improve performance* of the solution. One don't use DOM manipulations (prepends, appends) and one assigns `innerHTML` directly to save many internal work of web browsers, which it do after every modification of the DOM. I recommend you to read [the article](https://developers.google.com/speed/articles/reflow) first of all. You can find [the article](http://learn.jquery.com/performance/append-outside-loop/) in ["Performance"](http://learn.jquery.com/performance/) part of [the learning center](http://learn.jquery.com/) of jQuery too. You can make your own tests additionally to be sure that building long HTML fragments as strings and assigning it to `innerHTML` directly is really the best way from performance point of view. I want to stress that the discussion about the subject is *separately*  from reporting any bug about compatibility free jqGrid 4.9.1 and jQuery 3.0.0 alpha 1.

**Comment by herbalite** [comment]
I will post a demo showing the problem later so you can see for yourself, but it might take til next Monday.

**Comment by OlegKi** [comment]
Fine! I will debug the code after it will be ready. I remind: please, use non-minimizes jqGrid files direct from GitHub.

**Comment by herbalite** [comment]
Got a free time slot now, so here are 2 links earlier as promised and as you requested..

Both pages contain essentially your demo page with XHTML strict and everything using https:// adjustments, the PHP part at the top of those 2 pages looks like this:
    <?php
    header('Content-type: application/xhtml+xml; charset=UTF-8');
   ?>

Open these pages in Chrome, as Chrome gives you better error messages

In this link you will see the how jQuery 3.0 alpha 1 and XHTML STRICT fails
[Simple test with jQuery 3.0.0 alpha1](https://bmwbike.com/demojqgrid/jqgrid_alpha.php)

In this link you will see how jgGrid fails with the current jQuery stable version and XHTML STRICT standards applied

[Simple test with jQuery-1.11.3](https://bmwbike.com/demojqgrid/jqgrid_current.php)

Hopefully my comments above become more clear now. If you are a German native speaker, we can use German for clearer communication if needed.

Regards

**Comment by OlegKi** [comment]
I posted some fixes which solves the main problems with the using `Content-type: application/xhtml+xml; charset=UTF-8`. There are exist still one problem in searching toolbar which I will still analyse later. Probably it's really the bug in jQuery 3.0.0 alpha1 and not in jqGrid. Please test the latest code of free jqGrid from GitHub and confirm that the reported problem is fixed now.

**Comment by OlegKi** [comment]
@herbalite Thanks once more for the bug report. I posted some changes in the code of free jqGrid which improved the compatibility to XHTML standards.
One small remark. jqGrid creates ARIA attributes, so the most correct DOCTYPE for the HTML page would be
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+ARIA 1.0//EN" "http://www.w3.org/WAI/ARIA/schemata/xhtml-aria-1.dtd">
```
[The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/jQuery3alpha1_fixed.php) uses the same code and both original XHTML code and the dynamically created by jqGrid XHTML code (you can see the code in Chrome for example by using "inspect element" item of context menu) corresponds the standards. It can be verified by https://validator.w3.org/ for example.
The current alpha1 version of jQuery 3.0.0 have some bugs in creating disconnected DOM elements for `<th>`, `<tbody>` and some other. Nevertheless the latest code of free jqGrid works correctly with jQuery 3.0.0 alpha1 on some my tests. Please test it and confirm that the reported problem is fixed now.

**Comment by herbalite** [comment]
Thank you. For Firefox I got one page of our site mostly working. i got it working with both DTD's, that is XHTML STRICT and XHTML+ARIA. The remaining issue in Firefox seems to be XSLT related. 

Chrome is still complaining with an error message of invalid XML and aborts rendering the same page of ours that works with Firefox. I'm investigating myself, where that isssue is coming from.. 

Another xhtml issue that I still see one of our admin pages is when we use a subgrid. There are 2 errors being shown that appear to be jgGrid related.

But maybe it's better if I open an own ticket for that subgrid issue. What do you suggest? Continue here, or open another ticket for the problem we encounter with subgrids?

**Comment by OlegKi** [comment]
It doesn't matter whether you open new issue or not. You should just post enough information so that one can reproduce the problem and to localize and to fix the bug.

You wrote: "Chrome is still complaining with an error message of invalid XML and aborts rendering the same page". What page? [Your last demo](https://bmwbike.com/demojqgrid/jqgrid_alpha.php) have no problem in Chrome. In the same way you write about some problems with subgrid. The information that "our admin pages" have some problems helps not to localize the bug and to fix it. **Please send always the demo which reproduce the problem if you want to help to fix it.**

**Comment by OlegKi** [comment]
I posted some fixes in Subgrid module (see [here](https://github.com/free-jqgrid/jqGrid/commit/fd3324acb3be1cc6bc30da5828cef32c40b0e8bd)) which I could find. I don't recommend to use jQuery 3.0.0 alpha1 now because it have clear bugs in *changing* of `<table>`, `<tbody>`, `<tr>`, `<th>` and `<td>` elements (the method `domManip` works incorrectly). Please post demos which reproduce any problems which you could find additionally.

**Comment by herbalite** [comment]
Thanks. Subgrids are working fine.

The issue with CHrome is *not* a bug with jqGrid.

Therefore I am going to close this thread.

Thanks again, for your time and work.

**Comment by OlegKi** [comment]
Thanks you too for reporting of the problem! Only by reporting of all found bugs one can fix there. Please continue to report all problems which you could find in the future.
