### ISSUE TITLE
Clone repository into visual studio result in missing solution file.

### ISSUE THREAD

**Issue by fletchsod-developer** [free-jqgrid/jqGrid#129]
Step to produce the bug.   I'm using Visual Studio 2015.

1) Launch web browser (Google Chrome in my case).
2) Enter "https://github.com/free-jqgrid/jqGrid" into web browser url textbox & wait for it to load.
3) Click the "Open in Visual Studio" button.
4) Finish login to GitHub & other stuff configurations such as download path, etc. when prompted.
5) When done, there is no solution file (and/or directory folder to hold those project files).

So, can't tell the proper configuration when adding files/folders to solution for use, as well as unit testing, etc. which all of those setup responsibilities fall onto solution file.

**Comment by OlegKi** [comment]
Sorry, but which "Open in Visual Studio" button you mean? Do you use some plugin of Google Chrome which starts Visual Studio 2015 or you use some GitHub Extension for Visual Studio 2015? https://github.com/free-jqgrid/jqGrid don't contains any Visual Studio 2015 project, so it's unclear for me how you can open it in Visual Studio 2015. Please describe more exactly the problem inclusive installing of any plugins. I have the latest Google Chrome and Visual Studio 2015 Enterprise installed on Windows 10 Enterprise computer. I hope that I should be able to reproduce the problem.

**Comment by fletchsod-developer** [comment]
Thanks for the quick response.    

The VMWare disk image of Window 10 Enterprise was created a week ago.  Then Visual Studio 2015 Enterprise was installed, using custom installation (leaving alone most of the default selection).  Then Google Chrome was downloaded and went through default installation so I didn't touch the Chrome plugin setting.   Awesome that we both have similiar setup.

The GitHub extension was included in VS 2015, selected as part of custom installation.   I tried that option but GitHub pop-up search textbox for repository is greyed-out.  I think my GitHub user account is not set up for it or something.  GitHub extension is pretty new.

So, I went to Google Chrome browser and enter that url address and this "Open in Visual Studio" showed up here (see snapshot below).  There I clone it to my workstation.

![image](https://cloud.githubusercontent.com/assets/5113337/9177389/fb658ecc-3f5e-11e5-8882-e2b6f089bb10.png)

**Comment by OlegKi** [comment]
Sorry, but I still don't understand your goals. What you expect after click on "Open in Visual Studio" button? If any problem exist than it's not a JavaScript problem in free jqGrid, but some installation problem or the problem in using of GitHub Extension for Visual Studio.

I suppose that "Open in Visual Studio" button helps you to use GitHub as replacement of Source Safe, Visual Studio Team Foundation Server 2015 or other version control system. What I mean is the following scenario: you have GitHub Account and you places *your existing Visual Studio Project* on GitHub in the area where you have write access. For example I can place new project under https://github.com/free-jqgrid/ or under https://github.com/OlegKi. Then you should be able to open the Visual Studio project from GitHub using the button "Open in Visual Studio". The button should exist only if you chosen "GitHub Extension for Visual Studio" during installation of Visual Studio 2015 (see [here](http://blogs.msdn.com/b/visualstudio/archive/2015/04/30/announcing-the-github-extension-for-visual-studio.aspx)) or if you would downloaded it and installed from [here](https://visualstudio.github.com/) or from [here](https://github.com/github/VisualStudio). In any way the problem seems to me not a problem of free jqGrid, but the problem of correct using of  "GitHub Extension for Visual Studio". I'm trying to repair my Visual Studio 2015 installation, but I don't expect any new results.

**Comment by fletchsod-developer** [comment]
>> What you expect after click on "Open in Visual Studio" button? 
I expect to be able to open jqGrid in Visual Studio.   How?  No Visual Studio solution file are present.  (*.sln filename).

[Snapshot of jqGrid that was already cloned onto my workstation]
![image](https://cloud.githubusercontent.com/assets/5113337/9178638/294f9a1a-3f66-11e5-8fcf-c6376c4a1f65.png)

[Snapshot of being unable to open jqGrid in Visual Studio]
![image](https://cloud.githubusercontent.com/assets/5113337/9178736/73020ab2-3f66-11e5-9134-d9d9b8d4cea6.png)

**Comment by OlegKi** [comment]
Sorry, but it seems to me that your question is **not about free jqGrid**. Instead of that you have common question about the usage of *any GitHub repository* in Visual Studio 2015 with respect of GitHub Extension for Visual Studio. If I correctly understand your question then you can post the same issue to *any GitHub repository*, for example https://github.com/jquery/jquery or https://github.com/jquery/jquery-ui/. So I would recommend you to look [the video](https://channel9.msdn.com/Series/ConnectOn-Demand/217) for example which shows typical usage of GitHub Extension for Visual Studio. I hope it will help you.

**Comment by fletchsod-developer** [comment]
Never mind.  I'm gonna have to suffer.  But thanks for trying.  I'll let you finish other free-jqgrid issues.
