### ISSUE TITLE
Predefined values in FilterToolbar

### ISSUE THREAD

**Issue by smartcorestudio** [free-jqgrid/jqGrid#13]
I think that is a very common case, but I didn't find any elegant solution for this. Let's imagine that we have jqQrid with user actions log, for example. By default it has no predefined filters. Also we can have links like "Show user actions" on users profile pages, which open logs for this user. So, user will be selected in the FilterToolbar and table will be prefiltered
![2015-02-22 09_54_19- dekonadzor ru](https://cloud.githubusercontent.com/assets/2891792/6317765/0634da3a-ba79-11e4-8fd7-0aefbf58f3ff.png)
I tried to find solutions for this simple use case, but I had no luck. This solution http://stackoverflow.com/questions/2440417/jqgrid-filter-toolbar-initial-default-value/3165512#3165512 looks a bit tricky, don't you think so? Is it possible to have this built-in, without need to prevent initial loading by changing datatype and manual triggering? I.e. we have jqGrid tuned for loading data from server. If we don't have any predefined values in the filter toolbar it just loads all the data, if we have some - grid respects it and loads prefiltered data

**Comment by OlegKi** [comment]
Sorry, but I don't full understand the post. Do you have some suggestion how to improve the default behavior of the `filterToolbar`? Is it a question? What problem exactly you have? You reference to [the answer](http://stackoverflow.com/a/3165512/315935) *before* you formulated exactly your problem. It's unclear how you load the data for the "User" column. Is it `searchoptions.value` or you use `searchoptions.dataUrl`? Which `datatype` you use? Do you want just to fill the grid with *predefined filter*? Do you use *local* filtering of data or load the data from the server? If you load the data from the server then the format of the filter could be important (I mean: do you use `stringResult: true` option of `filterToolbar`). Please describe the problem which you have more clear and in details.

**Comment by smartcorestudio** [comment]
Hmm. If it's not possible now, you can consider it as a featue request for the future versions.
In this particular case I use `searchoptions.value`, but in some others I can use `searchoptions.dataUrl`. Ideally it will be better if we'll have universal solution. I load data from the server in json format. Here is the code:
```
jQuery("#grid").jqGrid({
   	url:'z-logs.php',
	datatype: "json",
   	colNames:['Операция','Объект','Код объекта','Название объекта','Пользователь','Дата'],
   	colModel:[
   		{name:'action',index:'action', width: 90, stype: 'select', editoptions:{value:"<LIST OF VALUES HERE>"}},
   		{name:'what',index:'what', width: 120, stype: 'select', editoptions:{value:"<LIST OF VALUES HERE>"}},
   		{name:'which',index:'which', width: 50},
   		{name:'name',index:'name', width: 150},
   		{name:'who',index:'who', width: 120, stype: 'select', editoptions:{value:"<LIST OF VALUES HERE>"}},		
   		{name:'when',index:'when', width: 100, formatter: 'date', formatoptions:{srcformat: 'Y-m-d H:i:s', newformat: 'd.m.Y H:i:s'},searchoptions:{dataInit:function(el){$(el).daterangepicker(droptions, function() {$("#grid")[0].triggerToolbar();});}}}		
   	],
   	scroll: 1,
    rowNum: 50,
   	pgbuttons: false,
   	editable: false,
   	pginput: false,
   	sortname: 'when',
    sortorder: "desc",
    autowidth: true,
	height: 400, 
    viewrecords: true,
  	pager: '#pagernav'
});
jQuery("#grid").jqGrid('navGrid','#pagernav',{add:false,del:false,edit:false,search:false});
jQuery("#grid").jqGrid('filterToolbar', {searchOnEnter: false});
``` 
Everything, including standard filterToolbar behaviour, works fine! I just want to have an ability to predefine some of the fillers without changing datatype, extra ajax requests etc.

**Comment by OlegKi** [comment]
Sorry, but I still don't understand the problem. I don't see any problem to implement all what you need in the existing (or old) jqGrid. I don't understand why you just not describe the problem **exactly**? You posted some part of the code. You use `datatype: "json"` **without** `loadonce:true` in the example. So you implemented probably filtering of data **on the server side**, but you don't describe which one. I always use `stringResult: true` to have one common searching/filtering implementation for all cases, but your code don't. It's not really a problem, but the implementation can depend from the choice. I asked you the question about it, but you don't answer. The problem is the following: if I understand your problem correctly than I see *multiple alternative solution* of the problem, but the implementation depend from the format of filtering which you use (`stringResult: true` or not). Some solution are very simple, but not so common.

You posted the code, but you don't defined any filter (at least an exact example of the filter). The first post looks more like you need to set filter on `who` column, but I don't see any `searchoptions` options in the column and no `searchoptions.value`. You specified just `editoptions.value`. The format of `value` is also not clear. Do you use string format or object format? 

Loading of *filtered data* with *predefined* filter is very easy. If you implemented some kind of filtering (with or without `stringResult: true`) then the server ('z-logs.php') expect additional parameter added to URL which specify the filter. It's `filters` option in case of usage `stringResult: true` and the name of the column if you use legacy filtering. In any way you can just add `search: true` option to the grid and add the required filter inside of `postData`. In the case the server will get the same request like during filtering and the server will returns the filtered data.

The only small problem will be to display the filter, which you used for loading the data, in the filter toolbar. In case of simple example, which you posted initially, it's just one line of code where you use `jQuery.val` on the corresponding `<select>` of the filter toolbar. In case of usage more common filter you can use the code, which I posted in [the old answer](http://stackoverflow.com/a/6884755/315935) many years ago. The only problem could exist if one don't use `value` in `searchoptions` because the select could be filled *after* you try to use `jQuery.val`. One can use the problem too in different ways, but you wrote that you don't use `dataUrl` currently.

There are some other absolute alternative solution of the same problem. One can for example set `datatype: "local"` in the grid to prevent loading unfiltered data from the server during creating the grid. Then one can use `jQuery.val` to choose the user in select of `who` filter. After that one can set `datatype: "json"` and trigger `.change` event on the `who` filter. The filtered data will be immediately loaded from the server.

If I misunderstood your requirements, please send **more detailed description of your problem**, so that I don't guess. If you speak about some predefined filter - you should include an example of someone and to include some example of `value` instead of `value:"<LIST OF VALUES HERE>"`. We can solve the problem *exactly* on some example and you can use the solution in more common case.

**Comment by smartcorestudio** [comment]
Oleg, I hope you don't mind if I explain you the problem in Russian. It will be easier to me.
Да, я могу добавить в код searchoptions.value, это будет выглядеть примерно так:
```
...
{name:'who',index:'who', width: 120, stype: 'select', editoptions:{value:":;2:Администратор;4:Резник Т.П.;5:Рыжова Ю.С.;7:leonteva;10:well-2203;11:николаенко;14:DBurkov;15:аккредитация;16:Хромченко Мария Владиславовна "}, searchoptions:{defaultValue: 2, value:":;2:Администратор;4:Резник Т.П.;5:Рыжова Ю.С.;7:leonteva;10:well-2203;11:николаенко;14:DBurkov;15:аккредитация;16:Хромченко Мария Владиславовна "}},
...
```
Как я уже говорил, нет никакой проблемы собственно с фильтрацией. В файле 'z-logs.php' все прописано и все фильтры корректно обрабатываются. Все работает как надо если значения в фильтры вводит пользователь. Если же я установлю defaultValue, то при открытии страницы в фильтре указанное значение окажется выбранным (с этим все ОК), но на сервер оно не отсылается и jqGrid заполняется значениями без учета выбранного фильтра. Я думаю, если применить вот это:
> One can for example set datatype: "local" in the grid to prevent loading unfiltered data from the server during creating the grid. Then one can use jQuery.val to choose the user in select of who filter. After that one can set datatype: "json" and trigger .change event on the who filter. The filtered data will be immediately loaded from the server.

то все будет ОК. Но, как я уже написал выше, мне не нравится это решение. Попытаюсь объяснить почему:
Использование предварительной фильтрации является опциональным, по умолчанию никаких фильтров не установлено и именно этот случай я рассматриваю в качестве основного. Поэтому заданиe `datatype: local` мне кажется нелогичным, если на самом деле я использую `datatype: json`. Т.е. предфильтрация может быть, а может и не быть. В большинстве случаев ее нет и использовать какие-то динамические смены datatype и триггеры всегда, только лишь из-за того, что здесь в принципе могут быть предустановлены фильтры - это не совсем правильно на мой взгляд. Мне бы хотелось чтобы было примерно так:
Если в searchoptions установлен defaultValue, то он не просто отображается в фильтре, но и отсылается на сервер при первоначальной загрузке данных. Ну и конечно, таких предустановленных фильтров может быть несколько и все они должны учитываться уже при самом первом обращении к серверу. И всё, в остальном же никакой разницы в конфигурации между тем когда фильтры предустановлены или нет быть не должно. Т.е. тот же самый обычный, честный `datatype: json` и т.п.
Конечно же, это не вопрос жизни и смерти и если действительно нет иного выхода, то можно поступить как в описанном выше решении и поиграться с datatype и триггерами. Я же пока просто отказался от возможности предфильтрации, чтобы не нарушать ради нее логичности подхода

**Comment by smartcorestudio** [comment]
Вот скриншот как выглядит страница стразу после открытия, если я передал в нее необязательный параметр для фильтрации по одному из полей. Он корректно прчитался и отобразился в фильтре, но не был отослан на сервер.
![2015-02-22 22_09_48- dekonadzor ru](https://cloud.githubusercontent.com/assets/2891792/6319921/c3b294fa-bae0-11e4-8a9f-403034af252e.png)

**Comment by OlegKi** [comment]
I think that there are one important misunderstanding. If you create jqGrid which has `datatype: "json"` the jqGrid send request to the server **during creating the grid**. So what you see in HTTP trace is the request during creating the grid. The grid have no searching toolbar at the time. The request uses only `postData`, `page`, `rowNum`, `search`, `sortname` and `sortorder` parameters.

If you want to have `_search: true`  and `who: 2` you need include `search: true, postData: { who: 2}`. If your server support `filters` parameter then you should use `search: true, postData: { filters: JSON.stringify({ groupOp: "AND", rules: [ { field: "who", op: "eq", data: "2" } ]})}`. It's the first way which I suggested you.

By the way the current definition of the column `'who'` seems to me still not full correct. It seems that you fill the data for the column with **textes** like `Администратор`, `Резник Т.П.` and so on instead of **values** `2` and `4`. The option `editoptions:{value:"value:":;2:Администратор;..."}` is incorrect in the case. It will break the content of the grid after editing. Either you use the option `editoptions:{value:"value:":;2:Администратор;..."}` **and `formatter: "select"`** additionally and you fill the grid with data `2`, `4` instead of `Администратор`, `Резник Т.П.` or alternatively you fill grid with  `Администратор`, `Резник Т.П.`, don't use `formatter: "select"`, but you have to use `editoptions.value` in the form `"Администратор:Администратор;Резник Т.П.:Резник Т.П.;...`. I hope you understand what I mean.

**Comment by smartcorestudio** [comment]
Thanks Oleg!
> you need include search: true, postData: { who: 2}

It works! I think this solution is better than tricks with datatype. Maybe it's not ideal for me as an end user, because I have to define the same parameter in 2 places: `defaultValue` just to select an option in select control and `search: true, postData: {...}` - to send this value to the server. But it's anyway better and I think I'll try to implement it. 
You explained me the internals, so now it seems a bit more logical to me. Alhough I still think that maybe it will be useful to have an option, something like 'respectDefaultValues', which will do some internal operations (based on any of this solutions or something else), so that it will be enough for an end users just to set the default values and enable this option and jqGrid will do the rest. And if it's not possible, so maybe it will be useful for some other users to know about the solution, that you gave me (Ii you want I can repeat my question at stackoverflow for example).

> By the way the current definition of the column 'who' seems to me still not full correct

Thanks. You are right. But I don't use editing in THIS grid. I just used `editoptions.value` instead of `searchoptions.value` for populating filterToolbar selects. It worked, but I think that it will be better to use `searchoptions` now. Thanks for pointing this.

**Comment by smartcorestudio** [comment]
By the way, maybe it will be a good idea to create something like FAQ section here, for example, in wiki. This solution and many others could be placed there for the users, who don't know some of jqGrid internals.

**Comment by OlegKi** [comment]
You are welcome! The options like `respectDefaultValues` seems to me not possible. `defaultValue` is for the choosing default value for searching dialog or for searching toolbar, but it should don't force any search request to the server. The meaning would be better to understand with searching dialog. If you open it and choose `who` column the you will have choose some option from select. If `searchoptions` don't have any `defaultValue` then *the first* option will be selected by default, but no search request will be still sent of case. Which option will be *the first* option can depend from the web browser. In some scenarios (like in case of using object form `value: {"":"", "2":"Администратор", "4":"Резник Т.П."}`) the options will be sorted by name in some web browsers. So the first option could be not the best choice. The property `defaultValue` could makes searching dialog more deterministic.

The usage of FAQ in wiki is a good idea. I started to fill [wiki](https://github.com/free-jqgrid/jqGrid/wiki). I want to publish soon the version 4.8. The information from [readme.md](https://github.com/free-jqgrid/jqGrid) is still not full and too long. I want to create many Wiki pages and include the references on the pages in the readme.

Best regards
Oleg

**Comment by smartcorestudio** [comment]
Now I've got it! There were some misunderstanding of the purpose of `defaultValue` for my part. Thank you for making that clear!

**Comment by OlegKi** [comment]
You are welcome!
