### ISSUE TITLE
jqGrid('getCell', foo, "column-name") returned strange result

### ISSUE THREAD

**Issue by fletchsod-developer** [free-jqgrid/jqGrid#144]
I believed I found a bug.   The demo is found at https://dealerapp-dev.bookitout.com/zzjqgrid/web/2/zz.html 

3 different ways to produce the results.   The 3rd one is the bug.

1) Click checkbox in column header (to checked all of checkboxes) then click "Get Saved Ids" button.   This one works (It showed all of Saved IDs).

2) Start over.  Click few checkboxes in column rows then click "Get Saved Ids" button.  This one works.  (It showed proper Saved ID values).

3) Start over.  Don't touch any of the checkboxes, leave them blanks & unchecked.  Then click "Get Saved Ids" button.   (It show all of Saved ID values but the bug is the 1st value being displayed as "false" instead of Saved IDs value).

    var JqgridGetCheckboxesValues = function () {
        var Ids = $('#' + _jqgridSpreadsheetId).getGridParam('selarrrow');
        var cellValues = [];
        var columnName = "SavedId";

        //Get all records if checkboxes aren't selected...
        if (Ids.length == 0) {
            for (x = 0; x < $('#' + _jqgridSpreadsheetId).getGridParam('records') ; x++) {     
                //Notice: This is the bug when row count  is at 0.
                cellValues.push($('#' + _jqgridSpreadsheetId).jqGrid('getCell', x, columnName));
            }
        }
        else {
            for (x = 0; x < Ids.length; x++) {
                cellValues.push($('#' + _jqgridSpreadsheetId).jqGrid('getCell', Ids[x], columnName));
            }
        }

        return cellValues;
    }

**Comment by OlegKi** [comment]
It seems to me that the error in in your function `JqgridGetCheckboxesValues` which will be called if the button "Get Saved Ids" will be clicked. It's not a jqGrid error. The function use `.getGridParam('selarrrow')` to get the array with ids of selected rows. In the case 3) jqGrid correctly returns an empty array. The next code of function `JqgridGetCheckboxesValues` is wrong. First of all you use undefined variable `x`, which will be assigned as property to the global `window` object. It's bad of cause. Next you use `.getGridParam('records')` to get the number of rows in the grid and enumerates `x` starting with 0 and till the `.getGridParam('records')`. **You use `x` value in `getCell` which is wrong**. The grid have no row with id=0 so you get `false` from `getCell`.

Instead of that you could use `.getDataIDs()` to get array with **ids** of rows in the grid. You can assign the resulting array to `Ids`. Then you can do the same as in the next loop where you goes through `Ids` array and use `Ids[x]`. 

Additionally you can see that your custom CSS setting breaks alignments of column headers, because you set `padding-left` to `15px` on the cells of the grid but not on the column header too. It could be something like `.ui-jqgrid .ui-jqgrid-htable th {	padding: 0 15px 0 15px;}` exacly like another CSS rule from `ui.jqgrid-bio-extended.css`.

**Comment by fletchsod-developer** [comment]
I see.  Okay, I fixed it now.  I thought it was jqGrid.

As for the CSS, are you referring to the checkbox in column header?

**Comment by OlegKi** [comment]
Yes I mean wrong CSS of the first column, which break column alignments of all other columns. I think that you should increase the `padding-left` and `padding-right` to `15px` and adjust `margin-left` and `margin-right` of the children `<div>` to negative value, like `-10px`. You can do this by CSS rule or by JavaScript code like
```JavaScript
$("#Jqgrid_Spreadsheet_cb").css({"padding-left": "15px", "padding-right": "15px"});
$("#jqgh_Jqgrid_Spreadsheet_cb").css({"margin-left": "-10px", "margin-right": "-10px"});
```

**Comment by fletchsod-developer** [comment]
I see.  JQuery is the one I will have to make do with because jqGrid generate the `style="padding:0px; width:21px"` meaning setting the CSS in `ui.jqgrid-bio-extended.css` wouldn't work, as it woudld get overwritten by jqGrid auto-generate CSS.

If you find a way with jqGrid internally then that would be awesome.  :-)

Thanks again for all you do.
