### ISSUE TITLE
GridToForm and parsedata possible bug

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#145]
When i use a field data into table mysql and this field is 0000-00-00 and i use GridToForm for editing form, this field is fill with one space at first of field. I think it should be empty.

**Comment by OlegKi** [comment]
Tanks for the bug report. I personally never use `GridToForm` or `FormToGrid` methods. I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/5c0cd9e952813fb0e0da8bec422fda17614104de). Please try the latest sources of free jqGrid from GitHub. Plase close the issue if the problem is solved now.

**Comment by davgino** [comment]
It's ok. Thank you.
