### ISSUE TITLE
Suggestion - Incorporate Lib.Web.Mvc JqGrid code as a reference implementation

### ISSUE THREAD

**Issue by DH0** [free-jqgrid/jqGrid#146]
I'd like to suggest creating a fork of Lib.Web.Mvc, which contains a comprehensive server side implementation for JqGrid, and incorporating it as part of the free-jqgrid group or repository (perhaps removing the parts that are not specific to free-JqGrid). 

Although JqGrid is designed to work with any server side back-end, a single server side implementation in MVC that is kept in-sync / up to date with changes in free-jqgrid/jqGrid would serve as a useful reference/example of a server side implementation for anyone wishing to build on other platforms. 

Many of the examples on Guriddo in fact use server side libraries that are not open source, and as such are not relevant or particularly useful with respect to free-jqgrid development. By incorporating a server side source code / reference implementation within free-Jqgrid, and thereafter making updates to both the client side and server side code that are compatible, free-jqgrid would be even more useful.

**Comment by OlegKi** [comment]
Thanks for your post, but I want to remind you that I started free jqGrid fork only after Tony have changed the license agreement of jqGrid in version 4.7.1. Before that I posted during many years my suggestions for improvement of jqGrid as pull requests (see [here](https://github.com/tonytomov/jqGrid/pulls?q=is%3Apr+author%3AOlegKi+is%3Aclosed)) or as posts in [jqGrid forum](http://www.trirand.com/blog/?page_id=393) (1255 posts). [Tomasz Pęczek](https://github.com/tpeczek) publishs Lib.Web.Mvc on GitHub (see [here](https://github.com/tpeczek/Lib.Web.Mvc)). So the only reason of making a special fork of Lib.Web.Mvc would be implementation of new options, which are specific for free jqGrid. It's the goal of your suggestion, if I understand you correctly. I recommend you to post your suggestion to Tomasz first of all.

I personally like both C# and JavaScript and I use ASP.NET MVC myself. The only real problem, which I personally see in integration of jqGrid in MVC, is the generation of `colModel`, which corresponds to model from the server. I personally don't like the implementation of C# wrapper classes for all options of jqGrid and all properties of `colModel`. In my opinion, it's not important *where* (in C# or JavaScript) one write the options. It would be just very practical if one would code the information **on one place**. I would more prefer to use something like `GetType().GetProperties()` or using other reflection methods to get the information from MVC Model and generate `colModel` based on the information.

One interesting approach is implemented in [grid.odata.js](https://github.com/free-jqgrid/jqGrid/blob/master/plugins/grid.odata.js) developed by [Mark Babayev](https://github.com/mirik123) and included in `plugins` folder of free jqGrid. See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/OData-plugin-for-jqGrid) for additional information. He uses OData on the backend and OData provides [metadata](http://www.odata.org/blog/queryable-odata-metadata/) information out of the box (by request to the server using `.../odata/$metadata` URL). The data can be provided either in XML format or as [JSON format](http://www.odata.org/documentation/odata-version-3-0/json-verbose-format/) (or in both formats). Mark wrote the plugin, which get the information about the backend data dynamically by querying the OData's metadata and generating the `colModel` *dynamically* based on the information. In the way one can modify the model on the server without requirement to adjust the code of jqGrid manually.

I personally is opened to every way. I registered free-jqgrid as organisation and created jqGrid as repository of the organisation instead of posting it under my own account [OlegKi](https://github.com/OlegKi). I thought about possible extensions. I want to create web site with documentation and demo examples. I have some other ideas too. If Tomasz, you or somebody else would like to create some other repository under free-jqgrid I would only advertise this. On the other side I don't find enough time even for creating the site with documentation and demos, which I find very important. I posed only some articles in [the wiki](https://github.com/free-jqgrid/jqGrid/wiki). It's really difficult to develop a project without the corresponding financial support. It was only a few peoples who donates free jqGrid.

So if somebody would implement Lib.Web.Mvc, which uses new free jqGrid features, I would stimulate this, but I can't do this myself. In any way I would suggest to start with asking Tomasz, whether he like the suggestion and whether he would like to create free jqGrid specific classes inside of existing Lib.Web.Mvc project.

Best regards
Oleg

**Comment by OlegKi** [comment]
Do you have some progress in the problem. I wrote you that I don't see that extension of Lib.Web.Mvc is the part of free jqGrid. I closing the issue. You can reopen it at any time.
