### ISSUE TITLE
Pivot frozenStaticCols is not working for column data cell.

### ISSUE THREAD

**Issue by eppsaksh** [free-jqgrid/jqGrid#148]
Hi Oleg,

pivot frozenStaticCols is not working for x dimension column cells.
It works for X column header section, it freezed header, but below data cells move with horizontal scroll bar.

Thanks,
eppsaksh

**Comment by OlegKi** [comment]
Please provide the demo which can be used to reproduce the problem. Simple test, where I insert `frozen: true` in items of `xDimension`, include `frozenStaticCols: true` in jqPivot options and add `shrinkToFit: false` and some fixed `width` value in jqGrid options, works at me. So the demo is really required.

**Comment by eppsaksh** [comment]
Hi Oleg,
Cannt give you demo, but i can post screen shot of issue..
below is screen when no horizontal scrollbar move,

![image](https://cloud.githubusercontent.com/assets/13976360/10358821/db8b7466-6daf-11e5-84ac-b559836ae918.png)

below is issue when we move horizontal scroll bar, column header are fixed/frozen, but data cell below are moved with horizontal scrollbar.

![image](https://cloud.githubusercontent.com/assets/13976360/10358849/342d0f62-6db0-11e5-93a2-c2ce861c2a63.png)

**Comment by eppsaksh** [comment]
Hi Oleg, 
Even after adding frozevn: true in x dimension columns & frozenStaticCols: true,
shrinkToFit: false  in jqPivot options, its not working as expected.

**Comment by OlegKi** [comment]
Sorry, but I can't debug the screenshorts. I need the demo which reproduces the problem. Look at the demo http://jsfiddle.net/OlegKi/pLxur189/ for example. It have not perfect alignment of the column header, but it have no problems which you describes in the issue. I suggest you to modify the demo to reproduce the problem which you have. Only having the demo I can analyse it, localize the problem and later fix it.

**Comment by eppsaksh** [comment]
Hi Oleg,

is frozenStaticCols property setting in CSS file?
If yes, which one, Can I have that version?

**Comment by OlegKi** [comment]
Sorry, but `frozenStaticCols` is the option of jqGrid and it has no relation to CSS. Nonetheless one have to use the CSS and JavaScript files from the same free jqGrid version. It's the only requirement. Do you verified that you use correct `ui.jqgrid.css` file?

**Comment by eppsaksh** [comment]
Hi Oleg,

We are using jqGrid  4.5.2 - jQuery Grid, is there any problem with version?
Your example using version jqGrid 4.9.2.
 We cannot change our working version 4.5.2, so please provide solution as problem is not yet resolved.

Thanks,
eppsaksh

**Comment by eppsaksh** [comment]
Hi Oleg, 
I am using grid.pivot.js from github folder for jqGrid pivot functions, Can we do some configuration in this file, as this pivot functionality is newly added in my application.

Thanks
eppsAksh

**Comment by OlegKi** [comment]
Hi eppsAksh,

it's of cause a problem. You post bug report to **free jqGrid**, which is for of jqGrid. It's based on jqGrid 4.7. So your question have no relation with **free jqGrid**. Old version 4.5.2 of jqGrid is published more as 2.5 years ago. Especially frozen columns functionality is buggy in old jqGrid. I posted many old answers on stackoverflow (see [here](http://stackoverflow.com/a/16517257/315935) and [here](http://stackoverflow.com/a/8771429/315935) for example) which describes the problem and which describes some tricks and workarounds required for using frozen columns in old versions of jqGrid. I made a lot of changes in free jqGrid to fix the problems. No one from old workarounds are needed in free jqGrid 4.9 because it handle all adjustments of width/height of the frozen column divs internally. Thus you *have to migrate* to the current version of free jqGrid if you need to use pivot in combination with frozen columns.

Best regards
Oleg
P.S. Please don't post here any issues which are not about free jqGrid.
