### ISSUE TITLE
Filtertoolbar ans SetFrozenColumns

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#165]
I think it is a bug between these two combinations
pls. seee. http://jsfiddle.net/9ezy09ep/44/

**Comment by davgino** [comment]
Please now press button * Cauta *
However a problem.

**Comment by OlegKi** [comment]
Thank you very much for reporting the bug! The latest merges [this one](https://github.com/free-jqgrid/jqGrid/commit/5dc8fecae2c5636cc5bdecd163438274c9a9da93) and [another one](https://github.com/free-jqgrid/jqGrid/commit/9bbc3de4768069afa5db60495b82d326123b04e0) should fix the problem. Please confirm that and close the issue if the problem is solved.

**Comment by davgino** [comment]
It's ok now.
