### ISSUE TITLE
groupSummaryPos: ['header '] is broken?

### ISSUE THREAD

**Issue by Yagg** [free-jqgrid/jqGrid#173]
See http://jsfiddle.net/1otjsmg7/4/

**Comment by OlegKi** [comment]
Thank you for reporting the bug! The problem seems come from all old versions of jqGrid (4.7, 4.6). For example http://jsfiddle.net/OlegKi/1otjsmg7/6/ uses jqGrid 4.6 and http://jsfiddle.net/OlegKi/1otjsmg7/7/ uses jqGrid 4.7. Both have the same problem. I will analyse the problem and inform you after posting the fix to GitHub.

**Comment by OlegKi** [comment]
@Yagg Thank you one more for your bug report. I posted [the changes](https://github.com/free-jqgrid/jqGrid/commit/44ed2589b3fe7f8fe533554164cd483bd91f5184) and [this one](https://github.com/free-jqgrid/jqGrid/commit/93615b71f610a76d45069162681e0e46a1507b22) to fix the bug. Please test the new code carefully. I hope that the latest changes don't introduce some new bugs.

The demo http://jsfiddle.net/OlegKi/1otjsmg7/8/ uses the latest code from GitHub.

Please confirm that the bug is fixed and close the issue finally.

**Comment by Yagg** [comment]
Excellent! All is working now for me. Thank a lot.
