### ISSUE TITLE
Issue with ResetSelection when using multiPageSelection.

### ISSUE THREAD

**Issue by tony98789** [free-jqgrid/jqGrid#181]
Im using multiPageSelection to preserve the selected rows in my grid. Im using json data but the paging is done with the server so it sends a new request each time i page. The issue im having is that when i call reset selection id expect all the rows to be deselected. So for example i have a grid that has 20 records and displays ten rows per page, i select one row on each page and then call resetselection. The selection on the current page is cleared but when i move to the next page the row is still selected. I thought that calling reset selection would simply clear out the selected row array. have i got this wrong?

**Comment by OlegKi** [comment]
I know the behavior. I included [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.11.0/js/grid.base.js#L5594-L5596) only because of compatibility with previous versions. The problem is that existing code could have many calls of `resetSelection` for resetting the selection on the current page. I though to add additional parameter to `resetSelection` in the future. I din't implemented it yet. What you need to do is very simple. To reset the selection of **ol pages** one need just set `selarrrow` parameter to empty array. You can just add one-two additional lines after `resetSelection`:
```JavaScript
var $grid = $("#grid");
...
$grid.jqGrid("resetSelection");
var p = $grid.jqGrid("getGridParam"); // get reference to all parameters
p.selarrrow = []; // reset selection on other pages
```
assigning `selarrrow` to empty array after `resetSelection` will fix your problem.

**Comment by tony98789** [comment]
Yer that solves it, thank you.
