### ISSUE TITLE
Hiding/Showing columns for group detail and summary

### ISSUE THREAD

**Issue by jimmccarthy** [free-jqgrid/jqGrid#183]
I have been working with groups and have run into some issues.  I want to do something like this:

						Date        Hours   Amount  Manager
    Group: Project
      Group: Resource   11/20/15                    Joe Smith
        Actuals                     100      2050
        Planned                      50      1025

So I want two groups where I do not want to summarize data from the detail level to parent groups.  The problem I am having is with showing things like dates and strings (manager name) in the Resource Header (or Footer).  It seems to only allow me to but numerics on the summary row.

Is it possible to work around this

**Comment by OlegKi** [comment]
Hi Jim, it's difficult to understand what you do because you don't posted any code example with the corresponding test data. It's unclear for me, which part of data belongs to summary and which for header, where is the origin for the value `11/20/15`. Nevertheless I created the demo based on how I understand your question.

First of all the hard core implementation, which uses custom formatter, I posted in [the old answer](http://stackoverflow.com/a/7622718/315935). It's flexible, but the code is not so easy to read and to understand.

During writing [the answer](http://stackoverflow.com/a/33394743/315935) I extended functionality of data grouping to allow to use `summaryTpl` and `summaryType` defined as array. It allows to specify **different** type and template for summary on different levels. On can combine the approach with the usage of functions for `summaryType`. As the result one can create relatively flexible, but simple code. I have to mention that the feature is implemented in the last version of free jqGrid. Thus I recommend you to upgrade to version 4.11.1 if you not yet did it.

I made [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping2-summaryTypeAsArray2.htm) for your to clear what one can do. It displays 
![g](https://cloud.githubusercontent.com/assets/249117/11607390/b050ea8e-9b44-11e5-95ec-24b1dc1a5b2c.png)
I used in the last column the following summary definition:
```
summaryTpl: [
	"{0}",
	"{0}"
],
summaryType: [
	function (value, name, record, newGroup) {
		return value ? value + ", " + record[name] : record[name];
	},
	function (value, name, record, newGroup) {
		return record[name];
	}
]
```
The `value` is the summary calculated before. I used the first callback for the first level grouping header 
only to demonstrates the meaning of the first parameter of the callback. You can use `"&nbsp;"` instead of `"{0}"` as the `summaryTpl` for the level.

**Comment by jimmccarthy** [comment]
Hi Oleg,  thanks for the quick response.  Sorry I was a little vague with the example.

Here is what the data would look like for this report

    Proj# Mgr   Date    Resource  Type    Amt   Hrs
    
    1     Smith 1/1/15  Jones     Actual  2050  100
    1     Smith 1/1/15  Jones     Planned 1025   50
    1     Smith 1/1/15  Designer  Actual   300   30
    1     Smith 1/1/15  Designer  Planned  200   20

etc

So I want the lowest level of detail to just show amounts and hours for actual and planned and I need some flexibility on where I show things like Proj, Mgr, Date, etc.  Like if grouping by project I would want to show something in the cell for Project Manager at that group header cell only.  Same goes for resource, some static string fields need to be shown just at the resource group level like the resource name.

I was running into NAN issues trying to show non numerics using a custom summary type based on a method.  Let me grab the latest and see if I can get this working with your latest changes.  Thanks again.

Jim

**Comment by OlegKi** [comment]
Could you post simple demo with the data. I don't understand the relation of Mgr and Date to Resource. What is absolutely unclear for me on the table from your first post: why you need to have separate columns Date and Manager if the information should be displayed only for the grouping headers and all other lines of the grid should be empty.

I still not understand what kind of information you really have and what/how you need to display the information. Probably grouping the data is the wrong way and you should better use TreeGrid or pivot tables (see [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9)).

Nevertheless I try to suppose that you really need to use data grouping. It seems to me that you have two levels of grouping: ProjectId and ResourceId. The Hours and Amount columns are the result of aggregation (probably "sum" operation). If you have would display only ProjectId and ResourceId and you have classic data grouping, but without the data (collapsed view of grouping with summary rows of the bottom). Probably you just have *additional information* about every Project and Resource and you want to display `ProjectName` instead of `ProjectId` and `Date` and `ResourceName` instead of `ResourceId`. In the case you would just need to define `groupText` either as template or as callback function or to define `formatDisplayField` and to display custom information. See [the answer](http://stackoverflow.com/a/25014675/315935) and [this old answer](http://stackoverflow.com/a/16152739/315935) for the coresponding code examples.

**Comment by jimmccarthy** [comment]
Hi Oleg,  It took me a little while but I was able to upgrade to the latest code base 4.11.1.  I am using the summaryTpl and summaryType arrays now to control data shown at each group level.  Last question.  Is there also a way to control what is shown at the detail level as well.  In your eaxmple about for the date column, the date at the lowest level of detail will be the same on every row for a given group.  I want to hide the date at the lowest row level of the report.  Is that possible?

Thanks,

Jim

**Comment by OlegKi** [comment]
In my example (see the picture from [the comment](https://github.com/free-jqgrid/jqGrid/issues/183#issuecomment-162172090)) the value for the grouping header of "Date" for the first grout are "" for the top level, but for the second level: `"02-Oct-2007"` and `"0a-Oct-2007"`. You asked about the date **at the lowest row level**. I suppose that you mean **displaying the data itself**. The `formatter` is responsible for the formatting of row data. Thus you have to use cusom formatter instead of `formatter: "date"`.

There are many ways how to detect inside of custom formatter whether it's request for formatting the row of data (the data itself) of the grouping header or grouping footer.

[The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping2-summaryTypeAsArray2_.htm) uses the following simple custom formatter:
```JavaScript
formatter: function (cellValue, options, rowdat, action) {
    return options.rowId === "" ? cellValue : "&nbsp;";
}
```
The value `options.rowId` is empty, both `options.rowData` and `action` are `undefined` only in case of formatting grouping headers. You can use the fact to remove (to display) the row data with `&nbsp;` (empty cell).

**Comment by jimmccarthy** [comment]
Got it, ok, let me give that a try.  Thanks again for the quick response.
