### ISSUE TITLE
multiboxonly:true bug

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#185]
When set multiselect to true and multiboxonly to true, as my practice, there is a big chance to misclick on checkbox( not exactly click on the checkbox but a little outside of it but still in the cell. ) to cause deselection of all other previous selected rows.

Can you please improve this so as long as I click on the selection cell, it won't cause deselect.

**Comment by OlegKi** [comment]
You don't described the exact test case, but I hope that I understand you correctly.

It's the behavior initially implemented in old versions of jqGrid. You can find the following statement in the documentation of old jqGrid (see here):

>Clicking in any other row (suppose the checkbox is not clicked) deselects all rows and selects the current row.

I don't like the behavior and I don't use `multiboxonly: true` option in any my grids. Nevertheless I believe that's the matter of taste.In any way I don't break the compatibility to the previous old version if it would be not really required.

I'm not sure, which behavior you want to implement, but `beforeSelectRow` callback allows you to implement any behavior, which you need, in very simple way. Look at [the answer](http://stackoverflow.com/a/33402985/315935). It describes very simple way how to allow to select/deselect rows if the user clicked on the chechbox only. I hope it's what you wanted to implement.

**Comment by ryanlin1986** [comment]
Sorry for the unclear description(don't know how to upload a picture before), please see following picture, I mean whenever we click the red rectangle area in picture, the deselection occurs.
![qq 20151213020705](https://cloud.githubusercontent.com/assets/11850439/11763285/f588bffa-a13e-11e5-9ac7-8b6aecea6a17.png)

**Comment by OlegKi** [comment]
I think that I do understand what you mean. I created some demos, which demonstrates my point of view.

[The first demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiboxonly-free-jqgrid0.htm) just uses the current code of free jqGrid with the options `multiselect: true, multiboxonly: true`. You can uses the code to reproduce the problem.
[The second demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiboxonly-jqgrid46.htm) uses jqGrid 4.6. You can compare the behavior of jqGrid and free jqGrid to see that both works in the same way.

[The documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options) of old jqGrid says:
> ... when multiboxonly is also set to true, the multiselection is done only when the checkbox is clicked (Yahoo style). Clicking in any other row (suppose the checkbox is not clicked) deselects all rows and selects the current row.

The text is not clear enough, but it sound that every click **outside of checkbox** will deselect all rows and select only the current row. The red rectangle area of your picture is outside the checkbox. Thus I don't interpret such behavior as the bug.

I still understand that the above behavior is not good for the users. Because of that I created three additional demos, which demonstrates how one can use `beforeSelectRow` to change the multiselect behavior so that it looks close to `multiboxonly: true`, but which don't have the problem which you describe.

[The third demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiboxonly-free-jqgrid1.htm) just uses
```JavaScript
beforeSelectRow: function (rowid, e) {
    return $(e.target).hasClass("cbox");
}
```
and the user can use checkboxes to select/deselect rows, but any click outside of the checkbox don't change the selection.

[The next demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiboxonly-free-jqgrid2.htm) just **ignore** the click on the red rectangle area of your picture. Nothing happens: no selection, but no deselection of old rows. The demo uses the following `beforeSelectRow` callback:
```JavaScript
beforeSelectRow: function (rowid, e) {
	var $td = $(e.target).closest("tr.jqgrow>td"),
		iCol = $td.length > 0 ? $td[0].cellIndex : -1,
		colModel = $(this).jqGrid("getGridParam", "colModel");

	if (iCol >= 0 &&
		colModel[iCol].name === "cb" &&
		!$(e.target).hasClass("cbox")) {
		
		// it's the checkbox column is clicked,
		// but OUTSIDE of the checkbox itself
		return false; // ignore such click
	}
	return true;
}
```
[The last demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiboxonly-free-jqgrid3.htm) have almost the same code as the previous example, but the click in the cell with the checkbox will be interpreted as the click on the chechbox:
```JavaScript
beforeSelectRow: function (rowid, e) {
	var $td = $(e.target).closest("tr.jqgrow>td"),
		iCol = $td.length > 0 ? $td[0].cellIndex : -1,
		colModel = $(this).jqGrid("getGridParam", "colModel"),
		rowid = $td.parent().attr("id");

	if (iCol >= 0 &&
		colModel[iCol].name === "cb" &&
		!$(e.target).hasClass("cbox")) {
		
		// it's the checkbox column is clicked,
		// but OUTSIDE of the checkbox itself
		$(this).jqGrid("setSelection", rowid, true, e);
		return false; // ignore such click
	}
	return true;
}
```

Thus you can do implement any behavior, which you like. You need just write some code of `beforeSelectRow` callback or `jqGridBeforeSelectRow` jQuery event.

**Comment by ryanlin1986** [comment]
Thanks, I just thought this behavior should be improved a little bit, or it will be meaning less to provide this option right?
Anyway thanks again for the example, it works perfectly.
