### ISSUE TITLE
sorting in chrome with equal value (return 0)

### ISSUE THREAD

**Issue by nigu0401** [free-jqgrid/jqGrid#190]
Firstly, thanks for the effort of this great grid! =). I found a minor glitch during column sorting and I traced until this function, this._compare = function (a, b, d) { ..... return 0;}. Seems like it has unstable sort in chrome V8 engine if the values are equal. Here's a simple sort demo that I did in jsfiddle (try in both IE and Chrome, results will be different),  https://jsfiddle.net/axb30jvu/. I'll try to think of a workaround in my app if any. Just letting you know of this minor glitch and thanks again. Sorry for my English though. :)

**Comment by OlegKi** [comment]
Sorry, but I don't full understand your statement. You sort by `sn:''` in your demo. Thus **every order of items** is correct. It's well known, that Google Chrome (V8) have *another sorting algorithm* as Internet Explorer. It's the reason why one sees different order of items in the web browsers. It's important to tress that both order is correct because the demo sorts by `sn` property which have the same values `''` in all items.

If you still want to sort your grid then you can use multisort strategy or to use `sorttype` defined as function. Inside of the function you can combine some new string, which combines the value from multiple columns. See [the answer](http://stackoverflow.com/a/8001822/315935) or [this one](http://stackoverflow.com/a/5296935/315935).

**Comment by nigu0401** [comment]
Hi Oleg,

Thanks for the quick reply and explanation :). Here's my situation :):
I have a grid that has 50 rows and 50-100 customized columns with pagination (10 pages and total records will be around 400 plus). This grid will connect to a server via websocket. Initially, the 50 rows will have empty rows with ids less than 0 (means negative values). When the server send data to client (the grid), I'll update the negative ids to actual positive unique ids (this positive ids are sent from server to differentiate each record. E.g. -1 becomes 1055, -2 becomes 50, -3 becomes 778 etc), meaning that I have to alter the p._index, p.rowIndexes and p.data. The orders work fine for each rows. 

1) So, I try to sort "sn" column in alphabetical order on page 1 which works fine using the sorttype function in cmtemplate. Both p.sortname and p.sortorder have values now.
2) Then I navigate to page 2 by reloading the whole grid with the same 50 empty rows (that has negative unique ids) before the server send me back the data for page 2, replacing those negative ids with the positive unique ids for page 2. Before replacing those negative values, the ordering in chrome sorted wrongly for me. Instead of -1, -2, -3, -4 til -50, what I saw is -25, -1, -3....-50. This won't happened in IE.

Forgive me if my explanation is not that clear. I'll try to use the multisort method and see how it works out. Thanks again.

**Comment by OlegKi** [comment]
It seems that the problem is already solved. If you would get some problems with the implementation I would recommend you to create small demo (in JSFiddle for example) which includes test data and to post it me. I suppose that the usage of `datatype: "local"` or `datatype: "json", loadonce: true` would be the best choice for you. The sorting of data will be done locally (on the client size by jqGrid). You would need just provide the `sorttype`, which mostly corresponds to the results, which you would like to have.

**Comment by nigu0401** [comment]
Thanks. I'll try to send to you via email once I'm done. Actually I've already used datatype:"local". I'm doing a client-server real time stock market by converting the legacy ActiveX application to HTML5 by mixing websocket, web worker and also this jqgrid communicating with a C++ server program that will send me top ranking of different stocks in real time (the data sent to the client will be quite frequent). That's why my p.rowIndexes, p._index and p.data will be changing all the time. The C++ server program remains at it is (I'm not allowed to change it! :( ). So, I have to change extend/alter the grid to meet the requirement of the current flow. I have to cater the grid sorting and the sorting of the ranking sent by server. And thanks again for your suggestion, I'm still tuning it though. Also, I'm a big fan of your work!Most of the jqgrid knowledge I've learned, I got it from the answer from you in various websites. :)

**Comment by OlegKi** [comment]
I'm like that I could help you. In case of dynamical modifying of jqGrid rows you have choice between two alternatives 1) replacing/modifying of `p.data` (modification of `p._index` typically not needed, all depends on the exact implementation) and reloading the grid by usage `reloadGrid` and 2) usage of `addRowData`, `setRowData` and `deleteRowData` to change the existing grid.

The usage of other parameters of jqGrid could be important too on the choice between two above options. Additionally the options of `reloadGrid` (like `current: true`) and the new options like `multiPageSelection: true` (in case of usage multiselect in the grid) could be important.

In general the usage of `reloadGrid` could probably gives the best results because the modified date will be correctly sorted filtered and paged before displaying.
