### ISSUE TITLE
Problem with sorting based on multiple columns and `sorttype` callback

### ISSUE THREAD

**Issue by servocoder** [free-jqgrid/jqGrid#192]
Hi Oleg,

My config for the grid:
```
url: requestUrl,
datatype: "json",
loadonce: true,
iconSet: "jQueryUI",
mtype: "POST",
pager: false,
cellEdit: false,
cellurl: null,
colNames: colNames,
gridview: true,
multisort: false,
sortname: "dueDate",
sortorder: "asc",

colModel: [
    {
        name: "dueDate",
        index: "dueDate",
        align: "center",
        editable: false,
        sorttype: function (cellValue, item) {
            return cellValue + '_' + item.taskId + '_' + item.isFinal;
        }
    },
    {
        name: "taskId",
        editable: false,
        hidden: true,
        hidedlg: true
     },
    {
        name: "isFinal",
        editable: false,
        hidden: true,
        hidedlg: true
     }
]
```

In my case I have to sort records by few colums, so my `sorttype` concatenates data of 3 columns and imitates server-side sorting to preserve correct order.

As you can see I use `loadonce: true` and I faced a problem that a regular sorting behavior applies `sorttype` callback function only for client-side reloading of the grid, when there is no request to server. So I am not able to rely on `sorttype` upon initial request and for this case: `$grid.trigger('reloadGrid', {fromServer: true});`

There is another problem. For some reason (perhaps you'll clarify it to me) if `sortname` is not empty the grid ignores server sorting and applies its own sorting, based on `sortname` and `sortorder`, but ignoring `sorttype` in the same time. As a result I am not able neither to keep server-side sorting nor rely on `sorttype` as described above.

The only way I have managed to use is as you answered in point 3 here:
http://stackoverflow.com/a/16383288/1789808
```
if ($grid.jqGrid("getGridParam", "datatype") === "json") {
    setTimeout(function () {
        $jqGrid.trigger("reloadGrid");
    }, 1);
}
```

As I found `setTimeout` is required but 1 ms is enough to make it works to force client-side sorting. But even with 1 ms I am able to observe as grid changes order of records. I believe this not te best solution. I would glad if there a way to specify sorting behavior. It could be an option like `forceClientSorting` to apply `sorttype` for every grid reloading, include server requests.

Another one might point to keep server-side order for ajax requests - not to apply sorting based on `sortname` and `sortorder` when `'datatype' === 'json'` as it implemented now.

Both can be useful I believe.

**Comment by OlegKi** [comment]
Sorry, Pavel, but it's difficult for me to classify your issue. Is it bug report or a feature request `forceClientSorting` or a question: how to implement multi-column sorting on the client side.

Please post the demo with the test case (step by step instruction, what one should do with the demo to reproduce the problem with description of expected results and the results which one have instead).

I thought already about implementation of `forceClientSorting` option. I agree that it would be helpfull in some scenarios. I didn't implemented it till now just because it required more deep changing the order of some parts of jqGrid. I still plan to implement such feature in the future.

The current state is the following. Even if you use `loadonce: true` option, the server required to return **sorted data**. It's the current requirement. If the server don't do this (you calls for example the web method of some public server) then you can force resorting the grid after the loading from the server. The function `setTimeout` don't support intervals less as 50ms (at least it's the guaranteed minimal interval), but even the interval 0ms would be enough. The web browser first execute the current thread till the end and only after that start execution of the function inside of `setTimeout`.

I'm not sure which scenario you try to implement in the grid. The current `sorttype` means the following: if one would sort locally by `dueDate` column then jqGrid will sort by `dueDate`, `taskId`, `isFinal`. But even the posted code makes me not enough information what would do the code exactly because I have no test data. Which values have `isFinal`? Is it `true` and `false`, `1` and `0`, `"yes"` and `"no"` or some another values? Have all `taskId` values the same number of digits? If you could have `1`, `2`, `11` values for example then you would have the order `1`, `11`, `2` after sorting because you convert the numbers in strings inside of `taskId`. I want just show, that the demo would clear many things.

If you would have more visible columns as `dueDate` then you would have **no multisort sorting** if the user would click on the server of the column another as `dueDate`. Only if the user would click back on the `dueDate` column then you would have sorting by `dueDate`, `taskId`, `isFinal`. could you describe exactly which behavior of sorting you need to implement?

The last remark. It would be helpful if you remove unneeded properties of `colModel` (all `index` properties and `editable: false`) and some unneeded jqGrid options (`iconSet: "jQueryUI"`, `pager: false`, `cellEdit: false`, `cellurl: null`, `gridview: true`, `multisort: false`, `sortorder: "asc"`).

Thanks for your post, but please include the demo with the test case and divide issues to one problem only (one issue for feature request, another for the bug report and third one for the question). One could close some issues and holding another one (with feature request) longer as a reminder.

**Comment by servocoder** [comment]
I guess it might be classified as a request to improvement.

Thank you for the clarification of the sorting process.
I'll post a demo a bit later to give you more understanding of my case.

Just to highlight and clarify: I don't use multi-column sorting in my scenario as `multisort` option does. You can see `multisort: false` in my config. But I really tried to sort single `dueDate` column based on values from multiple columns. So I am not sure it is correct to call such type of sorting as "multi-column sorting". Hope it is clear now. Anyway I think the subject might applies to `multisort: true` scenario too.

In my scenario I intended to keep sorting correct: apply client-side sorting which is respects `sorttype` column param. But this only works for client-side grid reloading, and I wasn't able to achive this for server requests. Because if `sortname` and `sortorder` in not empty the grid substitutes server-side rows order with a sorting based on `sortname` and `sortorder` but doen't respect `sorttype` param. Very strange behavior as for me. Option like `forceClientSorting` shoud solve the problem I think.

I can describe the main problem as follows:
It is not possible to sort grid rows correctly for single-column sorting for a column that should be sorted by values from multiple columns, as defined in `sorttype` param.

As for values I use in rows, thay are all integers:
dueDate - unix timestamp
taskId - integer
isFinal - 0 | 1

With the current implementation of `sorttype` I wished to imitate server side sorting that is based on SQL order: "dueDate ASC, taskId ASC, isFinal ASC". It gives the similar result. But I suppose not the same, as you mentioned because of string type sorting. The current result of `sorttype` satisfies me now, but I would appreciate if you know and share the way to make `sorttype` result match SQL order result for my case.
(It is an additional question and not the main subject for sure)

**Comment by OlegKi** [comment]
I hope, that I correctly understand the problem. I posted just now [the small changes](https://github.com/free-jqgrid/jqGrid/commit/000c6e72c299daea4372c2768d52dba699884900) in the code of free jqGrid. I would suggest you to use `sortfunc` instead of `sorttype`. Alternatively you can continue to use `sorttype`, but you should prepend converted integers with `"0"` to have string representation of numbers of the same size.

I made for you the demo https://jsfiddle.net/OlegKi/zkvwoj31/. It don't take in consideration the case when some properties in the input data are undefined. I was not sure which one unix timestamp you use. It could be that you should use `srcformat: "u"` instead of `srcformat: "u1000"` which I used in the demo.

I use `additionalProperties: ["taskId", "isFinal"]` parameter in the demo to remove unneeded hidden columns from the HTML table, but still hold the `taskId` and `isFinal` properties in the data saved locally. See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/additionalProperties-option-makes-unneeded-hidden-columns-in-local-scenario) which introduced `additionalProperties`.

If my suggestion don't solve your problem then you should modify the demo to demonstrate the existing problem.

**Comment by servocoder** [comment]
Great! Now it is possible to sort comparing with other rows. Your fix and example is the exact solution for my case in terms of sorting. Thank you, Oleg.

But one more thing, as I described in my first comment:
>As you can see I use loadonce: true and I faced a problem that a regular sorting behavior applies sorttype callback function only for client-side reloading of the grid, when there is no request to server. So I am not able to rely on sorttype upon initial request and for this case: $grid.trigger('reloadGrid', {fromServer: true});

Now I can use `sortfunc`, but still have to use workaround in `loadComplete` to force sorting for requests to server:
```
if ($self.jqGrid("getGridParam", "datatype") !== "local") {
    setTimeout(function () {
        $self.trigger("reloadGrid");
    }, 0);
}
```

>As I found setTimeout is required but 1 ms is enough to make it works to force client-side sorting. But even with 1 ms I am able to observe as grid changes order of records.

So I hope you can find a solution to implement client-side sorting without using `setTimeout` in `loadComplete` to not observe rows moving after they are displayed. I believe `forceClientSorting` could solve this problem.

Actually I expect `forceClientSorting` should replace the workaround condition in `loadComplete` and apply client-side sorting **before** grid rows are shown.

**Comment by OlegKi** [comment]
I thought about the problem of local sorting and examined the current jqGrid code once more. Finally I do implemented the new option `forceClientSorting: true` (see [the last commit](https://github.com/free-jqgrid/jqGrid/commit/119ea4a2e98354afbbe61cdaa26694fedac2240b)). See the demo https://jsfiddle.net/OlegKi/zkvwoj31/1/

**Comment by servocoder** [comment]
Thank you, I have tested it with an actual data in my grid and it works like a charm!

I think the issue could be closed, just want ask a related question:

If type of value in `dueDate` column is a Date or DateTime ("2015-12-25" or "2015-12-25 18:51:45") , should I convert it to unixtimestamp inside `sortfunc` before comparing? Or there is some solution out of the box?

**Comment by OlegKi** [comment]
You are welcome!

About the usage of Date or DateTime I suggested you multiple times to post the demo. I created even the demo for you (https://jsfiddle.net/OlegKi/zkvwoj31/1/). You need just modify it, save and to send me the URL of the new demo. Only having the demo with *exact input data*, which you use, and the *exact format of the displayed data* (with or without some formatter) one can help you. In general `sortfunc` gives you full freedom and you can implement any custom compare function.
