### ISSUE TITLE
Question about getRowData function.

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#194]
Hi, Oleg! I'm using jqGrid 4.7.0 and have faced a bug that I can't resolve quickly. Yes, I know that the version is too old, but it worked for me so far... Anyway, now I'm testing if it is possible easily to change the old library version to your last free-jqGrid library version. And I have faced that "getRowData"  function works differently. In the treeGrid mode it for some reasons doesn't return the whole row it got from the server. The function omits some properties like "parent", "isLeaf", etc. [Here](https://jsfiddle.net/ovkadurin/b6w6d1v8/) is a jsFiddle to check what I do. 
I have checked README files but have found nothing about it. Am I missing something? Thanks for reply!

**Comment by OlegKi** [comment]
The reason is very easy. The short answer: you need just replace `getRowData` to `getLocalRow` and everything will be OK: https://jsfiddle.net/OlegKi/b6w6d1v8/3/

More detailed answer:
You used `getRowData`, which get the data **from columns of the table (DOM)**. On the other side jqGrid saves the TreeGrid data to local `data` parameter starting with some very old  version (I think with 3.7 !!!). Thus starting with 3.7 it was more effectively to get the data of TreeGrid using `_index` and `data` parameters as using `getRowData`. Staring with version 4.0.0 exists `getLocalRow` which can be used mostly like `getRowData`, but it gets the data from *local* `data` parameter.

Nevertheless jqGrid 4.7 placed still all the helper properties `level`, `parent`, `isLeaf`, `expanded`, `loaded` and `icon` as hidden columns of the HTML table. It was not effective, get more memory of web browser and reduced the performance.

I introduced in free jqGrid 4.9 new option: `additionalProperties`. It allows to extend the input data, which will be read by jqGrid, with additional properties which will be saved in the *item of data* represented every row, but which will be not placed to DOM. The properties  `level`, `parent`, `isLeaf`, `expanded`, `loaded` and `icon` used by TreeGrid in adjacency model will be automatically filled in `additionalProperties`. In general one can save **any input property** to the local row. Thus you can for example load the row and the subgrid data for the row as custom property. It reduces the requirement of using any hidden columns. The additional properties are accessible in custom formatters, `cellattr`, `rowattr` and will be saved in `data` parameter in case of usage TreeGrid, `datatype: "local"` or `loadonce: true`. It can simplify the code and improve the performance. The last version 4.12.0 allows to sort and filter by `additionalProperties`.

The https://jsfiddle.net/OlegKi/b6w6d1v8/4/ is simple modification of the previous demo. I just added `"id"` in `additionalProperties` to have `id` property additionally to `_id_`. Moreover I added `custom` property with some complex data. All the data of every item will be saved in local data and `getLocalRow` returns there.

**Comment by okadurin** [comment]
I got it. Thank you for reply. Should I deep copy a row returned from *getLocalRow*? Previously I noticed that changing properties of that row change it like using *setRowData*, Btw, should I use *setRowData* in conjunction with *getLocalRow* in order to change properties of the row (not css class or something)?

**Comment by OlegKi** [comment]
It's depend on your goals.

`getLocalRow` returns **the reference** to internal object which represent the row. In the same way work `getGridParam` too. If you *need modify* the data and then trigger `reloadGrid` then you should don't make any deep copy. Thus you will not need to use `setRowData`.

In general `setRowData` do two things: 1) calls formatters to convert the data to strings and places the results to DOM of the row 2) changes internal `data` of the row. One can use `getLocalRow` and modify the data it one need to implement the second part only.

It's important to understand, that working with DOM is slow. It's especially slow if you modify some data. The web browser have to recalculate CSS properties of child elements and the position of almost all elements on the page. One names the process *reflow* (see [here](https://developers.google.com/speed/articles/reflow)). Because of that it could be more quickly to modify the local data of 2-3 rows (using `getLocalRow` or `data` parameter) and reload the whole grid as to modify the rows using `setRowData`. During reloading the grid *the whole* grid body will be first collected as one HTML string and the tbody will be replaced as one DOM operation. Because of such implementation the reloading of the grid is much more quickly as one could though, especially if one uses local paging and the page size is not large. The best way is measuring the time and to choice the way, which better corresponds to the used scenario.

**Comment by okadurin** [comment]
I got it. Thank you!
