### ISSUE TITLE
Improve the handling of corrupted server response (enhancement)

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#196]
Hi! In the case described in [this](https://jsfiddle.net/ovkadurin/q9bf4gb6/) jsFiddle I try to simulate a corrupted server response. To reproduce the issue you just need to expand the row and "the server" is supposed to return a corrupted JSON string. JsFiddle there helps not so much because it doesn't allow to simulate those things. In its response it says that response is corrupted and returns nothing.
But the real server (not jsFiddle simulation) can return any string. In particularly case it can return the array of rows with trailing comma. And JSON parser can't parse it properly. And it's OK. But what I think is not OK that jqGrid just silently does nothing. It doesn't throw an exeption, doesn't show a pop-up window that something goes wrong. And the reason of that behaviour is not obveouse.  
So, once again, to reproduce the issue it is needed to use the real server and not jsfiddle simulation.

---
I suggest you somehow increase the level of communication between developers and free-jqGrid. Of course it is a minor enhancement request, not a bug report.

**Comment by OlegKi** [comment]
Thanks for the suggestion. The error will be not displayed because your code don't contain any implementation of `loadError` callback. I thought already to include *default* implementation of such callback and your post remind me about that.

I posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/3cd4e0c381dd68c64592f16af4ad56a94ac4ace2), which provides the functionality. If displays the error message, which come from the server, in the new div, which I placed between bdiv and hdiv. The option `errorDisplayTimeout` (like `errorDisplayTimeout: 3000`) allows to hide the message after some timeout.

I tried to make the text of the message be readable, but it should be tested with different default errors from different frameworks. Currently I test whether the error message is in JSON format or in HTML format. I makes some formatting for both cases. For example I remove `<script>` tags from HTML response and get only the content of `<body>` in case if the `<body>` exist in HTML fragment. The formatting could should be improved after the tests.

Could you verify how looks the new *default* error message in your projects? Thank you.

**Comment by okadurin** [comment]
I've just tested a JS library (mockjax) to fake ajax calls. It works as expected. So I prepared some [tested](https://jsfiddle.net/ovkadurin/4bby86c2/) for you in jsFiddle. There you are supposed to "switch" tests by setting the true/false value after needed tests (in "tests" object). The default test is "test0" when everything works fine. Don't forget to set unneeded tests to "false".

---
My thoughts about new way of errors handling.
**1)** If a server responses with HTML it may looks ugly. See tests "test1" and "test3". It seem that it's better just say that error happend. And let front end user talk to back end.
**2)** When response type is JSON it looks much better. But in cases when a grid is a part of a "high"  web-page with scroll the top of the grid might be not visible. A user might scroll a page so the only bottom part of a grid is visible (if it's not clear let me know - I will send you a screenshot). And in this case the error message can be invisible as well. And it will be not clear for a user what is happening. Like he/she expands a row but nothing happens. See tests "test2", "test4".
**3)** Take a look on tests "test5", "test6". Cases with invalid JSON. Before your commit when invalid JSON happened free-jqGrid just ignored it. But now the error is thrown (see console). Something with jQuery Sizzle.

**Comment by OlegKi** [comment]
Thank you for the demo! I made some changes in the code and I think that the results looks better now. Be careful to use the latest version of `ui.jqgrid.css` from GitHub together with the latest `jquery.jqgrid.src.js` or `jquery.jqgrid.min.js`. See the modified demo https://jsfiddle.net/4bby86c2/64/.

**Comment by okadurin** [comment]
It looks better and it's obvious when errors happens. Thanks for your job!

**Comment by OlegKi** [comment]
You are welcome! I don't see the code, which displays error messages as final. For example I think that one should set `max-height` on the new `div.ui-jqgrid-errorbar`. Something like
```css
.ui-jqgrid-errorbar {
    max-height: 100px;
    overflow: auto;
}
```
I've modify `ui.jqgrid.css` to include the changes. Probably more changes will came later.

In any way all the settings are just *default* settings and can be changed by developers.

Your other suggestions or bug fixes are welcome.

**Comment by okadurin** [comment]
> I don't see the code, which displays error messages as final.

Sorry, I didn't get what you mean. What code are you talking about?

---

I've just checked the new css and see that the height of the error div is the constant now. It looks better.

**Comment by OlegKi** [comment]
If you just set `test1: true` in the previous demo https://jsfiddle.net/4bby86c2/64/ you will see the differences.  You can add the CSS rule
```
.ui-jqgrid-errorbar {
    max-height: 50px;
}
```
with *another* `max-height` value then you will see the differences with the JSON errors from the same test. I just included the value `max-height: 100px;` as the standard, but everybody can easy change the value like https://jsfiddle.net/OlegKi/4bby86c2/65/ corresponds to his preferences.

**Comment by okadurin** [comment]
I can manage the error div by css. I got it. I see the difference. Thanks!
