### ISSUE TITLE
showCol, hideCol are very slow

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#198]
Hi!

This is fragment of my code to show/hide cols in jqGrid:
```javascript
$.each(ZamTrasaWstepnaCols.colModel, function(index, elem) {
    if (elem.hideBUS) {
        grid.jqGrid("hideCol", elem.name);
    } else {
        grid.jqGrid("showCol", elem.name);
    }
});
```
There's about 40 cols in my grid where some of them have hideBUS attribute. Looping through those cols and show/hide them takes about 5-6 seconds which is quite slow. I've tried trick with 'classes' attribute in colModel and then:
```javascript
$('.col-to-hide').hide();
$('.col-to-show').show();
```
and it works much, much faster, but not working on header's table th's. I've tried this solution:
```javascript
var ZamTrasaWstepnaCols = {
    colNames: [
        "<span class='col-to-show-span'>Show this column</span>",
        "<span class='col-to-hide-span'>Hide this column</span>"
    ], 
    colModel: [
        {
            name: 'ColToShow',
            index: 'ColToShow',
            width: 30,
            align: 'center',
            hideBUS: true,
            classes: 'col-to-show'
        },
        {
            name: 'ColToHide',
            index: 'ColToHide',
            width: 30,
            align: 'center',
            hideBUS: true,
            classes: 'col-to-hide'
        }
    ]
};
```
and then:
```javascript
$('.col-to-hide-span').parent().parent().hide();
$('.col-to-hide').hide();
$('.col-to-show-span').parent().parent().show();
$('.col-to-show').show();
```
but header's cols are not disapearing.

Is there any idea to get better performance for show/hide cols?

**Comment by OlegKi** [comment]
First of all, please test, whether one have performance degradation in jqGrid 4.12.1. You can temporary change the URLs to use jqGrid 4.11.0 for example and compare the time of hiding/showing the same number of columns.

I would strictly recommend you to use [showHideCol](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.base.js#L6141) instead of [hideCol](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.base.js#L6200-L6202) and [showCol](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.base.js#L6203-L6205) in the loop. The problem is that `setGridWidth` will be called at the end of `showHideCol` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.12.1/js/grid.base.js#L6180)). The method `showHideCol` an be used to show multiple columns or to hide multiple columns. You should include the columns which visibility state will be changed. If the column is already shown and you try to show it then it could still have time for the operation.

Thus if you would need to show some columns and to hide another set of columns you can make two calls of `showHideCol`: once for showing some columns and once for hiding
```JavaScript
$grid.jqGrid("showHideCol", ["col1", "col2", "col3", "col4", "col5"], "");      // show
$grid.jqGrid("showHideCol", ["col6", "col7", "col8", "col9", "col10"], "none"); // hide
```
As the results the `setGridWidth` will be called twice instead of 10 times in case of separate calls of `hideCol` and `showCol`. The execution of `setGridWidth` can be relatively slow depend on the size of the grid.

**Comment by Wooya** [comment]
@OlegKi thanks a lot! Using `showHideCol` for array of cols instead of `showCol`/`hideCol` for each col improved my code performance abut five times :+1: Proposal: maybe optional parameter for `showCol`/`hideCol` like `recalculateWidth` with default `true` can be useful?

**Comment by OlegKi** [comment]
@Wooya : You are right, thanks! I'll think about the best additional options of `showCol`, `hideCol` and `showHideCol` which could allow to use the options in the loop. I'll post the changes later.

**Comment by OlegKi** [comment]
@Wooya : Try the performance of `columnChooser` after [the latest commit](https://github.com/free-jqgrid/jqGrid/commit/3abf87972e8542dea2bbf867565c3686cf84dfa3). It introduces new options of `hideCol`/`showCol`/`showHideCol`, which one can use independent from `columnChooser` to improve the performance to hiding/showing the columns of the grid. You feedback would be interesting for me, whether it allowed to improve your application additionally.
