### ISSUE TITLE
Question: Save button action while in edit mode

### ISSUE THREAD

**Issue by rcpacheco** [free-jqgrid/jqGrid#213]
Hello Oleg, while editing a cell of the grid, it is known that the getRowData will contain the input element but not the real content of the cell. I tried several alternatives, including an example that you posted for a slightly different case: http://www.ok-soft-gmbh.com/jqGrid/SaveRow.htm.
In my case I'm not editing the row, but just a cell.

My questions are:
1) Is there a better alternative to getRowData without arguments to get all the local data?
2) Is there a command to force the end of the editing mode prior saving the grid content?

Thanks a lot

**Comment by OlegKi** [comment]
Hi Ricardo,

the grid, which have `datatyle: "local"` holds all local data in `data` parameter. Thus the best way to get all the data is the usage of `.jqGrid("getGridParam", "data")`. The only problem exist if some rows are currently editing. In the case you should decide whether to save the current state of editing rows or to discard there. I suppose that you have somewhere on the page "Save All" button. If the user clicks the button, then he/she expect that the changes will be saved and not discarded.

Thus you can use first
```JavaScript
var savedRows = $("#grid").jqGrid("getGridParam", "savedRow");
```
to get **the reference to array** with old values of currently editable rows. Every item include `id` property with the rowid additionally. Thus you iterate over all the items of the array and get `id` property. It's the rowid of editing rows. Finally you should call `saveRow` method for all the rows:
```JavaScript
var $grid = $("#grid"), savedRows = $grid.jqGrid("getGridParam", "savedRow");
while (savedRows.length > 0) {
    $grid.jqGrid("saveRow", savedRows[0].id);
}
```
Because the `savedRows` will be modified after every call of `saveRow` one can use always the same 0 index in `savedRows[0].id` (see above).

Finally you can just use `$grid.jqGrid("getGridParam", "data")` to get all the data.

**Comment by rcpacheco** [comment]
Thanks a lot your Oleg ! You gave me some very good ideas.

I was having some problems with the while (saveRows...), so I end up doing
the following:

in the onCellSelect I store the values iRow (lastSel) and iCol (lastCol) of
the last selected cell. Within my save All method I do:

var cell = grid.jqGrid('getCell', lastSel, lastCol);
if (cell && cell.indexOf('<input') >= 0) {
         grid.jqGrid("saveRow", gridObject.lastSel);
}
var gridData = grid.jqGrid("getGridParam", "data");

In that way I only have to worry about updating the cell that is currently
being edited. Works great!!

Thanks a lot

2016-02-24 14:25 GMT-06:00 Oleg Kiriljuk <notifications@github.com>:

**Comment by OlegKi** [comment]
Hi Ricardo,

I'd not recommend you to use `getCell` in the way. Your original row can contains `formatter: "checkbox"` for example and the method `getCell` can works incorrectly in the case, moreover the content could contains `<select>` element for example instead of `<input>`.

The parameter `savedRow` will be used in inline and cell editing internally. It will be filled correctly in all scenarios with all types of `formatter` or `edittype`. You need just get `id` properties of all items of `savedRow` array and you don't need to hold any `gridObject.lastSel` externally. Moreover the external object `gridObject` is not associated with the grid. If you would have multiple grids on the page you will have to hold the same separate objects. It's better to use internal parameters, which jqGrid maintains automatically for you.

Best regards
Oleg

**Comment by rcpacheco** [comment]
Oh great, Oleg,  thanks for the warning.
I will review my implementation and document it back here, for others to
know if they have the same question.

Best regards,

Ricardo

2016-02-25 13:55 GMT-06:00 Oleg Kiriljuk <notifications@github.com>:

**Comment by OlegKi** [comment]
It seems that the question is answered and I close it. You can any time reopen it or to post new question.
