### ISSUE TITLE
Toolbar search and hidden columns

### ISSUE THREAD

**Issue by RobertoLda** [free-jqgrid/jqGrid#220]
I need to sort and filter a column based on another hidden column, so I used the index option. The problem is that the toolbar search input is always clearing, not showing the input value, after the filtering. For instance:
```JavaScript
colModel: [ ...
    {name:"numProcessIndex", index:"numProcessIndex", hidden: true, searchoptions: {sopt: ["cn"], searchhidden: true }},
    {name:"numProcessFormated", index:"numProcessIndex", width: 130, stype:"text", searchoptions:{sopt: ["cn"]}},		
	...
];
```

**Comment by OlegKi** [comment]
Could you post more details about what you do or better to prepare the demo, which demonstrates the problem? Which `datatype` you use? If you use remote `datatype` (like `datatype: "json"` or `datatype: "json"`) then it's important to know, whether you use `loadonce: true` option. It's unclear whether you have problem with **local** filtering or with **remote** filtering (for example, some wrong searching parameters are send to the server, ...).

You wrote about the problem with searching toolbar. Thus you call `filterToolbar`. Which options you use?

It would be helpful if you include some test data in the issue. Which format have the input data for the columns?

Which version of free jqGrid you use?

Independent from your main question it's unclear for me why you use hidden column `numProcessIndex` at all. Do you want to display the column in some cases to the user or you want just save the corresponding data somewhere? There are many options to save the data, but the best choice depend from the answer on the questions, which I asked above (mostly from `datatype`, `loadonce`).

**Comment by RobertoLda** [comment]
First of all, thanks for the answer and sorry about the uncleared question.

I used to use the jqgrid 4.6, but I was having some problems with virtual scrolling, multiselect and row numbers, two weeks ago I updated to the version 5.1.0, but but the problems persisted, so I changed to your fork, free-jqgrid, and it is working perfectly with this features.

I will try to explain more properly my problem. I get remote data using url and datatype: json options, and loadonce: true, to sort and filter on client side. The data come with some hidden columns used for sort and filter purposes.  Eg. there is a column, displayed to the user, that is just an icon representing
some aspects of the record, there is another hidden column that I use as an index to this icon, so the user can order and filter. There are others situations where a column is displayed formated to the user but ordered by another format, eg. sequential_number.year (0312.2016) to the user, but ordering by year.sequential_number (2016.0312), so I also use a hidden columns on this cases.

It works well on the jqgrid, on the free-jqgrid it orders and also filters, but the input value of the filterToolbar is cleared after the filter process, with searchOnEnter true or false.

I have reproduced the problem getting the demo GetFilteredData (http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData.htm) adding a hidden a column (nameIndex) and seting this as an index of another column (name).

```

var mydata = [
                    { id: "1",  invdate: "2007-10-01", name: "test",   nameIndex: "1test",  note: "note",   amount: "200.00", tax: "10.00", closed: true,  ship_via: "TN", total: "210.00" },
                    { id: "2",  invdate: "2007-10-02", name: "test2",  nameIndex: "2test",  note: "note2",  amount: "300.00", tax: "20.00", closed: false, ship_via: "FE", total: "320.00" },
                    { id: "3",  invdate: "2007-09-01", name: "test3",  nameIndex: "3test",  note: "note3",  amount: "400.00", tax: "30.00", closed: false, ship_via: "FE", total: "430.00" },
                    { id: "4",  invdate: "2007-10-04", name: "test4",  nameIndex: "4test",  note: "note4",  amount: "200.00", tax: "10.00", closed: true,  ship_via: "TN", total: "210.00" },
                    { id: "5",  invdate: "2007-10-31", name: "test5",  nameIndex: "5test",  note: "note5",  amount: "300.00", tax: "20.00", closed: false, ship_via: "FE", total: "320.00" },
                    { id: "6",  invdate: "2007-09-06", name: "test6",  nameIndex: "6test",  note: "note6",  amount: "400.00", tax: "30.00", closed: false, ship_via: "FE", total: "430.00" },
                    { id: "7",  invdate: "2007-10-04", name: "test7",  nameIndex: "7test",  note: "note7",  amount: "200.00", tax: "10.00", closed: true,  ship_via: "TN", total: "210.00" },
                    { id: "8",  invdate: "2007-10-03", name: "test8",  nameIndex: "8test",  note: "note8",  amount: "300.00", tax: "20.00", closed: false, ship_via: "FE", total: "320.00" },
                    { id: "9",  invdate: "2007-09-02", name: "test9",  nameIndex: "9test",  note: "note9",  amount: "400.00", tax: "30.00", closed: false, ship_via: "TN", total: "430.00" },
                    { id: "10", invdate: "2007-09-08", name: "test10", nameIndex: "10test", note: "note10", amount: "500.00", tax: "30.00", closed: true,  ship_via: "TN", total: "530.00" },
                    { id: "11", invdate: "2007-09-08", name: "test11", nameIndex: "11test", note: "note11", amount: "500.00", tax: "30.00", closed: false, ship_via: "FE", total: "530.00" },
                    { id: "12", invdate: "2007-09-10", name: "test12", nameIndex: "12test", note: "note12", amount: "500.00", tax: "30.00", closed: false, ship_via: "FE", total: "530.00" }
                ]
...

colNames: ["nameIndex", "Client", "Date", "Amount", "Tax", "Total", "Closed", "Shipped via", "Notes"]

...

colModel: [
			{ name: "nameIndex", hidden: true, stype:"text", searchoptions:{sopt: ["cn"], searchhidden:true} },
            { name: "name", align: "center", width: 65, editrules: {required: true}, index: "nameIndex", stype:"text", searchoptions:{sopt: ["cn"]} },

....


```

**Comment by OlegKi** [comment]
Thanks for the demo. I can mostly easy fix the problem if I could reproduce it. I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/bd1ac4c33b75c7a1bfa87a8ae22eb15cf498281e) to GitHub repository. You can verify on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData-sortBug.htm), which uses GitHub sources, that the problem is solved now.

Small remark. I implemented `additionalProperties` feature in free jqGrid, which informs jqGrid to save *additional properties* from the server response in the local `data`. It's important in case of `loadonce: true` scenario. One have access to the properties almost in the same way like to the hidden columns, but the data will be hold **only as JavaScript properties and will be not placed on the DOM of the page**. It reduce the page size and improve the performance. One can use the properties in sorting, searching and filtering. See some examples in [the answers](http://stackoverflow.com/search?tab=newest&q=user%3a315935%20additionalProperties) and some more demos: [here](http://ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalProperties.htm), [here](http://ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalPropertiesAndSearchingDialog.htm) and [this one](http://ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalPropertiesAndSearchingDialog1.htm). The last demos demonstrates the usage of `sortfunc` callback which makes possible easy to implement custom sorting.

Your original demo can be modified to [the following](GetFilteredData-sortBug1.htm).

I recommend you to read [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Custom-filtering-searching-Operation), which describes one more feature from the close subject.

Please, don't forget to close the issue after you confirm that the reported problem is solved.

**Comment by RobertoLda** [comment]
Great!! I got the code from GitHub and my application is running fine.

I would just like to let you know that on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData-sortBug.htm) I had to include the property `search: false` in the index column, otherwise, I can't clear the input value after the filtering.

`{ name: "nameIndex", hidden: true, sorttype:"integer", searchoptions:{sopt: ["cn"], searchhidden:true}, search: false },`

Thank you very much!

**Comment by OlegKi** [comment]
:-) The problem with deleting of the symbol is really funny! It shows that how dangerous is the usage of hidden columns. The column `nameIndex` is searchable, but hidden. Thus the `filterToolbar` creates hidden `<input>` field for the column too. The last version of free jqGrid have the feature of filling the filter toolbar based on the values from `postData.filters`, which will be set either from the previous searching of from Searching Dialog or from manual pre-loaded filter. The usage of both filter toolbar and the searching dialog is relatively common case. Many problem exist if the user first filled some values in the filter toobar for searching and then used Searching Dialog. One can see in the old version of jqGrid in the filter toolbar in such case the *old filters* which are not more applied in the grid. The new version of jqGrid fills the toolbar based on the values from `postData.filters`. Because one have now **two** columns `nameIndex` *and* `name`, which both corresponds to the filter rule `nameIndex=1` then *both* fields of the toobar (for the columns `nameIndex` *and* `name`) will be filled with the value `1`. After the user delete the value the change event will be triggered and the values from the filter will be read. The user have changed `name` to `""`, but `nameIndex` has still the old value. Both columns will produces the filter with `nameIndex` searching rule, but one will uses `nameIndex=` and another `nameIndex=1`. The hidden column `nameIndex` is **before** of the column  `name`, thus the value from `name` wins. On the other side, the empty value in the column  `name` will be **not** used as the searching rule, so no `nameIndex=` will be used in the case. As the result, the incorrect rule `nameIndex=1` will be **not overwritten** by `nameIndex=`.

[the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData-sortBug2.htm) is almost identical to [the first demo](http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData-sortBug.htm), but it has **`search: false`** property in the hidden `nameIndex` column. As the result, no hidden input box for `nameIndex` column exist any more. 

After some time thinking about the above problem I made [one more fix](https://github.com/free-jqgrid/jqGrid/commit/91bde8167332022372774db40ba7874ce3f323f5) in the code to reduce the probability of such problems. I hope that the filter toolbar will be easier be used now.

**Comment by RobertoLda** [comment]
Hi, I understood the problem of the columns orders. Thanks again!!
