### ISSUE TITLE
UI tab and setGroupHeaders

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#230]
If i use jquery UI tab and setGroupHeaders , in first tab setGroupHeaders working ok , but in second tab setGroupHeaders not working.

**Comment by OlegKi** [comment]
Thank you for the bug report! Working with DOM elements inside of hidden parent element is very tricky. Nevertheless I made some [small changes](https://github.com/free-jqgrid/jqGrid/commit/4867fce3c154f1bdc350e4406596ebf9b9a20e9c), which should fix the most common problems of working `setGroupHeaders` inside of hidden/inactive tab. See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/MultilevelHeadersTabs.htm), which uses the latest sources of free jqGrid from GitHub.

I'm closing the issue. Please, verify new code of free jqGrid and confirm, that the problem is solved in your environment. If you will find still some problem, please reopen the issue and provide the demo which can be used to reproduce the problem.
