### ISSUE TITLE
Styled Checkboxes for multiselect get re-checked on deselect

### ISSUE THREAD

**Issue by Grubsnik** [free-jqgrid/jqGrid#235]
Since version 4.9 (went back through the release history to locate this), if you use a select all button to select everything and then try to deselect something by clicking on the styled checkbox, the checkbox (or rather the spanbox) gets set back to checked if you click it. The actual row gets selected / deselected correctly, but a rogue event somewhere re-checks the checkbox as part of the event flow.

**Comment by OlegKi** [comment]
Sorry, but I can't reproduce the problem, which you report. For example, try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/multiPageSelection.htm) referenced [here](http://free-jqgrid.github.io/examples/index.html).

Moreover I don't understand, what you mean under "rogue events".

Could you provide the demo, which use non-minimized free jqGrid 4.13.3 and which can be used to reproduce the problem, which you describe?

**Comment by Grubsnik** [comment]
Hi Oleg, thanks for your swift reply.

I have put up a minimized repro of the issue at http://dummy.infare.net/
1. Select all 
2. Click on a checkbox from a row in the grid. The row will change as if not having been selected, but the styled checkbox retains it checked class.

I have further discovered that this bug does not present itself in IE, but does show up with Firefox and Chrome.

What I meant with rogue event was that if you place a breakpoint in the rowselected event handler, you will see that the checked class is removed properly initially, but that something later in the grid event flow overrules it and re-applies the checked class

**Comment by OlegKi** [comment]
Sorry, but the code from your demo is **very buggy**. Moreover your code modifies all the checkboxes used by jqGrid for multiselecttion. Such manipulation break the existing code of jqGrid.

Now I explains the same more detailed. Your code have heavy errors in the JavaScript and CSS files which you included. For example you include **multiple times** either the same files or different files from different versions. For example you includes JavaScript file of jQuery 1.8.3, then jQuery UI 1.11.1, then jQuery UI 1.9.2 (!!! it breaks jQuery UI 1.11.1), then Modernizr v2.6.2, then Modernizr v2.8.3 (!!! wrong), ..., then `jquery.jqGrid.src.js` of free jqGrid 4.13.3, then `grid.locale-en.js` (the settings are already included in `jquery.jqGrid.src.js` and you don't need to include `grid.locale-en.js`), then you includes some other JavaScript files and include `jquery.jqGrid.src.js` and `grid.locale-en.js` **once more** (!!!).  In the same way you include multiple CSS files from different versions (CSS Bootstrap v2.2.1 and CSS Bootstrap v2.2.2) and you include **wrong jqGrid CSS** (!!!). Instead of including `ui.jqgrid.css` from free jqGrid 4.13.3 you use some very old `ui.jqgrid.css` from some jqGrid in version <4.5.0. All this is absolutely wrong!

Then you make some havy manipulation of the grid, created by free jqGrid, inside of `afterGrid` method. You execute the line
```JavaScript
$(elem).wrap('<div class="custom-checkbox"><label class="spanbox"><span class="tick" /></label></div>');
```
which changes the structure of the column with multiselect checkboxes from
```html
<input name="jqg_grid_1961594" class="cbox" id="jqg_grid_1961594" aria-checked="false" type="checkbox">
```
to 
```html
<div class="custom-checkbox">
  <label class="spanbox checked">
    <span class="tick">
      <input name="jqg_grid_1961594" class="cbox" id="jqg_grid_1961594" aria-checked="false" type="checkbox">
    </span>
  </label>
</div>
```
Such manipulation breaks existing code of free jqGrid, see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.3/js/grid.base.js#L4997) for example, which suppose that `"input.cbox"` is **direct child** of `<td>` element. The wrapping of the checkbox break it.

I tried to optimize the code of free jqGrid to improve the performance. For example I use the method `.children` in many places to access internal structures of jqGrid because `.children` have better performance as, for example, `.find`. Your changes of internal jqGrid structure breaks the code. It's wrong t change the internal structures of jqGrid!

Your code have more problems and it's bad from performance point of view. For example, you use
```JavaScript
onSelectRow: function (rowId, status) { RowSelected(rowId, status, $grid); }
```
where `var $grid = $("#grid");`. All callbacks (inclusive `onSelectRow`) will be called with `this` initialized to DOM of grid. Thus `$(this)` inside of `onSelectRow` callback would be equal to `$grid` and the usage of `RowSelected.call(this, rowId, status, $grid);` could forward the value of `this` to `RowSelected` function. You could remove unneeded `$grid` parameter in the case. In any way if you use `$grid` option then the usage of
```
var row = $('#' + rowId, $grid);
```
and `$('.custom-checkbox .spanbox', row).removeClass('checked');` later in the code of `RowSelected` is ineffective too. If you would use `$('#' + rowId)` instead of `$('#' + rowId, $grid)` then jQuery will use the selector like `#1961595`, which can be resolved using `.getElementById()`, implemented native in DOM. The web browser create the index of elements by id attributes and `.getElementById()` get effective the corresponding DOM element using the index. If you use `$('#' + rowId, $grid)`, then the selector `"#grid #1961595"` will be used. It means getting `#grid` by id and *searching of all its children* for the element with `id="1961595"`. One can't use id index for such searching.

The most effective and the recommended way to get row by id is the usage of `getGridRowById` method:
```JavaScript
var row = $grid.jqGrid("getGridRowById", rowid);
```
It works the mostly quickly.

In general, one can see that your code is *very old* and it's written for Bootstrap 2.x. Free jqGrid have native support of Font Awesome 4.x and Bootstrap 3.x. If you would just use the standard multiselect possibility of free jqGrid you will get the results like on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-bootstrap1.htm). In other words no your customization are probably needed.

If you still want to create your custom checkboxes, then you should not modify the existing one, but to use custom formatter to create the chekboxes, which you need, in the column of the grid. Free jqGrid supports `hasMultiselectCheckBox: false` option, which allows to implement multiselect selection *without* creating `cb` column with the standard multiselect checkboxes. Thus you can implements any your custom selection behavior without conflicts with free jqGrid code.

**Comment by Grubsnik** [comment]
You are correct in that the code is a very smelly pile of... Sadly I just inherited it and was hoping that I could get away with an in-place upgrade of JQGrid to get the multipageselect bits (which miraculously works correctly except for this one case). 

Thanks for your thorough read through and feedback on the sad state of affairs. I'll note down all your feedback and include is under the cost of getting multipage selection.
