### ISSUE TITLE
Mobile-friendly responsible table planned?

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#236]
For now mobile support is basically a essential requirement for business apps.
Is there any plan to improve user experience for mobile devices?
For example:
http://demos.jquerymobile.com/1.3.0/docs/widgets/table-reflow/

**Comment by OlegKi** [comment]
I hope that I understand you correctly. The feature exists in free jqGrid since a long time. What you need to do is setting the responsive class like `my-custom-breakpoint` on some cells of the columns and the same class on the headers of the column. One can use `classes` and `labelClasses` properties of `colModel` to do this. I described the feature initially in [the answer](http://stackoverflow.com/a/30824040/315935). The next thing, which one should do, is resizing of jqGrid on resizing of the outer container:
```
$(window).bind("resize", function () {
    $grid.jqGrid("setGridWidth", $grid.closest(".ui-jqgrid").parent().width());
}).triggerHandler("resize");
```
(see [the old answer](http://stackoverflow.com/a/25036623/315935))

Bootstrap CSS, for example, defines different CSS classes with the names `visible-*` or `hidden-*` (see [the documentation](http://getbootstrap.com/css/#responsive-utilities-classes)), which can be used.

[The demo](http://jsfiddle.net/OlegKi/andm1299/26/) created for [the answer](http://stackoverflow.com/a/34226305/315935) or [another demo](https://jsfiddle.net/OlegKi/w7pxts0z/7/), created for [the answer](http://stackoverflow.com/a/37259416/315935) demonstrate the approach.

Is it what you need?

**Comment by ryanlin1986** [comment]
Thanks, That is really cool, ;)
