### ISSUE TITLE
innerHTML is slow in IE.

### ISSUE THREAD

**Issue by devginie** [free-jqgrid/jqGrid#239]
before : 
`self.firstElementChild.innerHTML += rowData.join(""); // append to innerHTML of tbody which contains the first row (.jqgfirstrow)						`

after : 
```
self.style.display = 'none';
$(self).first().append(rowData.join(""));// append to innerHTML of tbody which contains the first row (.jqgfirstrow)						
self.style.display = '';
```

Chrome is fast using any code.
But this code is fast performance in IE.

**Comment by OlegKi** [comment]
Could you provide more details and the demo with the test case? Which version of IE you used (IE8 - IE11)? Which version of jQuery you used? If your main suggestion to hide the grid *before* filling `<tbody>` and to show it back after that, then it would work independent from the usage of `jQuery.append`. On the other side I'd recommend you to use non-minimized code of jQuery and to debug the code of `append`. It will consist from many preliminary steps and will use assigning of `innerHTML` as the final step. Thus the performance of `jQuery.append` can't be better as the performance of assigning `innerHTML`.

In any way, if you claim that some code is "slow" and another one is "fast" then you should provide an exact demo and the test case. You should *measure* the time and to write the exact results in ms of the time before and after the changes. You should distinguish both steps of suggested changes (hiding/showing and append or innerHTML). See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-5000-25-free-jqgrid.htm) or [this one](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-40000-20-free-jqgrid.htm) as an example of measurement.

**Comment by devginie** [comment]
I am totally misunderstand about jqGrid various feature.
**The problem is innerHTML performace.** approach is my mistake.
I try to display treegrid in the single page with ajax at once.
It is very slow. Because of DOM display speed for so many elements. (10,000+ rows)

But, What I really need is 'treegrid with pager'. (Pagination in treegrid #105)
I want to re-issue 'treegrid with pager'.
What do you think about that?

**Comment by OlegKi** [comment]
I don't think that paginating in TreeGrid is the solution of the problem because there are exist really serious design problems in the implementation. Let us you have really deep Tree, you opened some nodes, and want to go to the next page. Displaying the items *without parent hierarchy* would produce misundertandable results. Displaying the parents can fill the full page and one will be not able to display really required data.

I know how one could rewrite the TreeGrid module to solve your current problem, but I just don't have the corresponding time for that. It's not easy to develop a large product, which is provided for free. I get too few donations from companies, who uses free jqGrid. The main idea, which could solve the problem: filling the DOM elements of TreeGrid *on demand* (only if the Tree node be opened and to *remove* the items instead of hiding). It will dramatically reduce the size of DOM and to improve the performance of free jqGrid.
