### ISSUE TITLE
After last commit remapColumns function not work

### ISSUE THREAD

**Issue by globian** [free-jqgrid/jqGrid#245]
After last commit remapColumn not worked:
```JavaScript
onClickButton: function () {
	var a = pitlist.width();
	pitlist.jqGrid('columnChooser', {
			done: function (perm) {
				if(perm){
					pitlist.jqGrid("remapColumns", perm, true);
					var mymodel = pitlist.getGridParam('colModel'); // this get the colModel array
					var hiddenCols = [];
					$.each(mymodel, function(i) {
						if(this.hidden == true ) {
							hiddenCols.push(this.name);
						}
					});
					var configuration = {perm: perm, hiddenCols: hiddenCols};
					configuration = JSON.stringify(configuration);
					$.post(ajaxUrl + '/savepitlayout',{config:configuration,view:'tyres'});
				}
			},
			width: 580,
			modal: true
		}
	);
}
```

**Comment by OlegKi** [comment]
Could you describe the problem more clear and more detailed? The statement "After last commit remapColumn not worked" gives almost no information. What exactly "not work"? Which "last commit" you mean? Which version of free jqGrid you used in your tests (4.13.3, the latest source from GitHub or some another old version)? With which version of free jqGrid you had no problems? What should the code, which you posed, do? What is `pitlist`? Do you probably mean `var pitlist = $(this);`?

If you want to report the bug you should prepare the demo, which reproduce the problem. If I could debug the demo which uses non-minimized version of free jqGrid, I could quickly localize the problem.

By the way, I would recommend you to use `onRemapColumns` callback or `jqGridRemapColumns` event to make some actions after `remapColumns`.

**Comment by Shinidoki** [comment]
I made a JSFiddle with the problem:
[JSFiddle](https://jsfiddle.net/jmLfyect/1/)

If you now remove the "total" column for example, you can see that the filter toolbar isn't updating correctly. The "closed" filter moves under the "shipped via" column.

**Comment by OlegKi** [comment]
Sorry, but the demo, which you posted doesn't work. I can it fix to [the following](https://jsfiddle.net/jmLfyect/3/). I could found that the code of `showHideCol` have to be adjusted after changing the `role` attribute of the searching toolbar to `"row form"` (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/88d6fbaabb8d8231ebd7a05232950c697ffdfcf8) posted after 4.13.3). **Thank you very much for the bug report!** I posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/a9e34b5d6f49c0a1cbf3fe2727839066cd814c1d) just now, which should fix the problem. Please verify that the problem is solved in the latest code from GitHub and close the issue after that.

**Comment by globian** [comment]
It work's fine, big thanks.
