### ISSUE TITLE
jQuery MultiSelect UI Widget does not retain selection when jgrid is reloaded

### ISSUE THREAD

**Issue by AshK14** [free-jqgrid/jqGrid#254]
Hi Oleg,

I am not able to get around this issue.
I am loading data through json and with loadonce:true. We can filter data using multiselect widget, and then update any row. When the row is updated, I am destroying the filtertoolbar and then creating it again after reload from server.
I also have to make sure that the previously selected values are retained after reload.

Everything works, filtertoolbar has the selection retained and also the data is filtered using previous selection on reload from server, but the multiselect widget does not have the previous options selected. All the selections in the multiselect dropdowns are cleared(unselected).

Selection is retained in multiselect dropdown if we filter by one value and then update the row, however if we are filtering by multiple values in multiselect dropdown and then updating the row, all the values of multiselect dropdown are unselected after the grid reloads.

However postdata.filters has all the previous selections intact, it is getting applied to filtertoolbar on reload, just that multiselect widget is not showing the previous selections.

If I do not do 'destroyFilterToolbar', the selections are retained in the multiselect widget, but then new values of the column if any after the update, are not reflected in the multiselect dropdown.

I prepared a small fiddle using local data,
https://jsfiddle.net/AshK14/5gnvxvke/1/

Also tried to simulate it using json, but it does not exactly reflect the issue due to data(the approach is similar to what I am using),
http://jsfiddle.net/AshK14/3mff9pg9/5/

Hope you understood the issue that I am facing.
Let me know your thoughts.

Thanks.

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand your scenario. Do you load the data from the server in your main code? Do you use `loadonce: true`? Do you apply the filter **locally** or on the server? If you edit the data then you send the data on the server or you edit local data?

I don't understand some parts of your code:

- you set `datatype: 'local'` explicitly. Why? the part seems me  wrong in all scenarios which I imagine me.

- you call `destroyFilterToolbar` inside of `loadComplete`. It seems to me incorrect or at least very suspected. The `loadComplete` will be called for example at the end of filtering. If you want recreate the filter after loading the data *from the server* you can use `beforeProcessing` instead of `loadComplete`.

- I would recommend you to call `destroy` method of the multiselect widget **before** calling of `destroyFilterToolbar`. I suspect that missing destroying could be one of the main problem in the existing code. It could prevent destroying of select element and two selects with the same id could exist after recreating the filter toolbar.

- if you want that the filter will be applied *locally* even in `loadonce: true` scenario then you should use `forceClientSorting: true` option. It means that the data, returned from the server, will be sorted and filtered *locally*.

- one more tip. The filter toolbar of free jqGrid supports `jqGridRefreshFilterValues` event which can be used to refresh the values in the filter toolbar. By calling `$("#grid").trigger("jqGridRefreshFilterValues")` the values in the filter toolbar will be refilled based on the `postData.filters`. It's important that `search: true` should be set before too. The event `jqGridRefreshFilterValues` should select the options of `<select>` (which has `multiple="multiple"` attribute in your case). After the filter toolbar will be filled and the select options are selected you can call `.multiselect("refresh")` on the corresponding element.

If you construct the demo in JSFiddle then you can use Echo service (see [here](http://doc.jsfiddle.net/use/echo.html)). In context of the usage jqGrid you can use the following options:
```JavaScript
    url: "/echo/json/",
    datatype: "json",
    postData: {
        //delay: 1,
        json: function () {
            // we use function here to be able to send
            // UPDATED data (after editing)
            return JSON.stringify(myData);
        }
    },
    mtype: "POST"
```
The Echo service will return the data which you send in `postData.json`. The usage of function as the value of `postData.json` allows to send *modified* `myData`. For example you can use *local* editing and then to change `myData` by assigning `myData = p.data` (where `p = $(this).jqGrid("getGridParam");`).  I recommend you to use `reloadAfterSubmit: false` option of form editing to have better control over reloading the grid (you can add `formEditing: { reloadAfterSubmit: false }` option of jqGrid to force the option) and to reload the grid manually by calling `$(this).triggerHandler("reloadGrid", {fromServer: true});` at the end of the code of `afterComplete` callback. You can set `search: true` for example and many any other changes *before* reloading the grid.

Please share the final solution with other users of jqGrid.

**Comment by AshK14** [comment]
Hi Oleg,

Thanks for your suggestions.

I have managed to simulate my issue by using the Echo service as you suggested.
Now the demo is similar to the actual code that I have. 
Yes, I am using json data from server with loadonce:true option and I apply the filter on the local data after it has been loaded from the server.
After Edit, I send the data back to server in order to perform some updates.

The demo is located here,
http://jsfiddle.net/AshK14/dj35p611/3/

As you can see from the demo, after we update and reload from server, the selections of multiselect widget are lost. However the other filtertoolbar textbox values are retained after reload from server.
Selecting one option however in the multiselect widget, is retained on reload from server.

Also, due to some reason, the data is not getting filtered locally with the prevoiusly selected filters on server reload, but I am able to achieve this in the application.

My only problem at this point is that the selected checkboxes of the multiselect widget are unchecked if we reload from server after Edit operation and if we had filtered by multiple options and then clicked on Edit. 

Please let me know your suggestions.

Thanks.

**Comment by OlegKi** [comment]
Hi AshK14,

I analysed the demo and made changes in the code of `filterToolbar` (see [here](https://github.com/free-jqgrid/jqGrid/commit/4e1ad883bab7922b9a253c5741d76eb78eb46051)).

After the above changes and modifications of your demo to the following http://jsfiddle.net/OlegKi/dj35p611/7/ the code become working. Please examine carefully the changes which I made (the code of `dataInitMultiselect`, `beforeProcessingHandler1`, the option `forceClientSorting: true`, the options of form editing: `reloadAfterSubmit: false` and `afterComplete` and so on).

**Comment by AshK14** [comment]
Hi Oleg,

Thanks for your help!!
I implemented all your suggestions. I found your demo very useful.
The demo was working, but now it seems not to work. Not sure if any other changes in the plugin is causing this.

If you run the demo,
http://jsfiddle.net/OlegKi/dj35p611/7/

and try to update, one of the selected options is getting uncheked. 
Can you please verify.

Thanks.

**Comment by OlegKi** [comment]
It's a little strange, but the code of the demo was really changed. It should not contain the block `if ($options.length > 0 && $options[0].selected) {$options[0].selected = false;}`

Look at the demo: http://jsfiddle.net/OlegKi/dj35p611/9/ . It works at me.

**Comment by AshK14** [comment]
Hi Oleg,

Thank you very much.
It is now working as expected with all the filters retained.
So, closing the issue.
