### ISSUE TITLE
Allow 100% height?

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#256]
I knew I cal use setGridHeight to dynamic set height to 100% of parent div container, But sometime the height may change without window resize change, I have to use resize sensor( which is not efficient ) to call setGridHeight when parent container size changed.

But if the browser support css3 calc, why not use it to improve performance and usability, here is my code to do this:

                var height = parentContainerHeight;
                            //Get rid of column header height
                            var columnHeaderHeight = $(this.componentInfo.element).find('.ui-jqgrid-hdiv').outerHeight(true);
                            height -= columnHeaderHeight;
                            //Get rid of footer height
                            var footerHeight = $(this.componentInfo.element).find('.ui-jqgrid-sdiv').outerHeight();
                            if (footerHeight == null)
                                footerHeight = 0;
                            height -= footerHeight;
                            height -= 1;
                            //Use cass calc if available
                            if (Modernizr.csscalc) {
                                $(this.componentInfo.element).find('.ui-jqgrid')[0].style.height = "100%";
                                $(this.componentInfo.element).find('.ui-jqgrid-view')[0].style.height = "100%";
                                $(this.componentInfo.element).find('.ui-jqgrid-bdiv')[0].style.height = "calc(100% - " + (columnHeaderHeight + footerHeight) + "px)";
                            }
                            else {
                                this.jqGrid.setGridHeight(height.toString() + "px");
                            }

I'm wondering if you can add an option to allow use css3 calc let the height to be 100% of parent container?

**Comment by OlegKi** [comment]
Sorry, but I would ask you to formulate the problem, which you report, or the bug more clear. First of all you should describe the scenario which you have. Seconds you should describe the problem in some way and only after that you should suggest the solution of the problem.

In the issue your write about "parent div container" without specifying what you mean.

In the code fragment you set `height` attribute on all bDiv (`ui-jqgrid-bdiv`), gView (`ui-jqgrid-view`) and gBox (`ui-jqgrid`) on the page. I don't full understand the goal of that. In some use cases it will break the structure of jqGrid.

Probably you want to suggest to prefer to use `.style.height` instead of `jQuery.height`, but both ways works in different way. In some parts of free jqGrid code I use `jQuery.css` to do the same like you do with `.style.height`. Look at [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L5482) of free jqGrid code for example. If you would use the option `height: "100%"` then the code like `$(grid.bDiv).css({ height: "100%" })` will be executed.

In any way it's important to write absolutely clear what you exactly suggest (which changes, in which part of jqGrid code) and why you suggest it. If you say that some changes in the code of free jqGrid improves the code then you should **measure** it. Look at [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-5000-25-free-jqgrid.htm) as an example. It shows the time in ms of initial loading of the grid with 13 columns, 5000 total rows and 25 rows per page. one can see the time used for sorting, paging and filtering. One can use the demo to measure the performance in some web browser (like Chrome 52 for example), makes some changes in the code of free jqGrid and then repeat the same tests. If one would see some essential changes in the performance then I would adjust the code of free jqGrid based on your suggestions. I personally had many ideas of improvements the performance of jqGrid based on some "common performance suggestion", but I could not see any essential improvements in the tests and thus I didn't made the changes. You should understand that many changes could have side effects. Thus I prefer the make the changes only if I see some benefits of the changes.

**Comment by OlegKi** [comment]
Please post some additional information about the problem or close the issue.
