### ISSUE TITLE
Column Chooser with Grouped Headers

### ISSUE THREAD

**Issue by Luca7993** [free-jqgrid/jqGrid#261]
Hi
the column chooser with grouped headers is not workin well:
1) The reordering of columns is not applied
2) If you hide one of the columns of the group, the group headers are not applied correctly 
[Here is a demo](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooserGroupHeaders?type=original)

I think it can be a good idea to work with the entire Group header in column chooser instead with single columns:
[Solution](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooserGroupHeaders?type=edit)

**Comment by OlegKi** [comment]
The URLs, which you posted, contain references to `http://localhost:58145/` and there could not be used. Could you post the information in another way?

**Comment by Luca7993** [comment]
Sorry, forget to publish the site and to use the correct link...I need some vacation :)

I have edited the first post with working links

Luca

**Comment by OlegKi** [comment]
Thank you! I have to do my main job. I will look your demos later.

**Comment by OlegKi** [comment]
Sorry, but the changes, which you suggest, removes another important feature - the possibility of to hide/show columns which are groupped. I will see how to fix the code to have both: column reordering and hiding/showing the columns.

One more remark. The method `setGroupHeaders` used for column grouping has one important option: `useColSpanStyle: true` (see [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:groupingheadar) for example). One should always made two tests: one with `useColSpanStyle: true` and another with `useColSpanStyle: false`.

**Comment by OlegKi** [comment]
Thanks for the bug report! I confirm that hiding of groping columns is broken now (already in 4.13.3) [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/columnChooserCustumButton_4.13.2.htm) uses 4.13.2 and it shows how it should work. I suppose that some change of the code (probably [this one](https://github.com/free-jqgrid/jqGrid/commit/4867fce3c154f1bdc350e4406596ebf9b9a20e9c)) was wrong in 4.13.3. I suppose that `colspan` value is changed in the wrong way. It was correctly to remove `&& !$(ths[i + iCol].el).is(":hidden")` part, but other changes were wrong. Sorry, but I'm busy now. I'll analyse and fix the problem later.

**Comment by Luca7993** [comment]
Hi Oleg,
absolutely no problem of course, and thank you for all of your work!
Anyway I prefer to use my custom solution for groupped columns and I will give that to my customer (it could be an idea also to make the "treat groupped columns as unique column" optionable

thank again
Luca

**Comment by OlegKi** [comment]
I had to think about the problem and could not do my main job. Thus I reverted [the changes](https://github.com/free-jqgrid/jqGrid/commit/4867fce3c154f1bdc350e4406596ebf9b9a20e9c), which I described before and made only really [required part](https://github.com/free-jqgrid/jqGrid/commit/26980579a85607233dcd8546d833c9faf7298b42) of changes. I hope that the problem is fixed now. See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/columnChooserCustumButton_git.htm), which uses the latest code from GitHub. Please test it if you find the time for it...

**Comment by OlegKi** [comment]
Sorry for the late answer. I committed just now [the changes](https://github.com/free-jqgrid/jqGrid/commit/5c4728d377d6fbe3b3af2089b9b178036e17df53). `columnChooser` should support now reordering (or hiding) of columns if header grouping are used. New callback options `sortUpdate` and `init` can be used additionally in `columnChooser`. The commented changes are relatively large and probably more tests are required. My current tests work good.

The only restriction of `columnChooser` now: one can't change the order of groups in the header. I thought to extend the Column Chooser dialog later with the feature to "collapse" items in the group. The dialog contains currently multiselect control only, but one still call jQuery UI `dialog`. One can add later for example checkbox in the dialog which can be used to fill multiselect with groups only instead of the items of the group (like in your original suggestion). I consider to use this some time later. The current changes are more important in my opinion.

**Comment by OlegKi** [comment]
Do you tried the new code of free jqGrid from GitHub? I plan to publish next version of free jqGrid soon and it would be good to fix any bugs before.

**Comment by Luca7993** [comment]
Hi Oleg,
No sorry i still didn't try it because i'm in vacation now.
I will check it on 11-12 of September

Thank you
Luca

**Comment by OlegKi** [comment]
OK, no problem. I wish you to have fun in the vacation!

**Comment by Luca7993** [comment]
Hi Oleg,
I've tried the new version and I found a problem on it:
[jqgrid problem](http://testjqgridalimede.azurewebsites.net/Home/ColumnChooserGroupHeaders?type=original)

**Comment by zajc** [comment]
**"If you hide one of the columns of the group, the group headers are not applied correctly"**

This is still an issue in version 4.13.4.

**Comment by OlegKi** [comment]
@Luca7993: I wanted to publish new version of free jqGrid, but I see that the issue is still opened. The demo, which you posted is not more available. You don't posted the demo and the test case somebody else. I suppose that you had some combination of hidden columns inside of grouped headers or between the grouped headers, but I can't reproduce the bug now on my old demos. Could you post the demo, which uses the code from [RawGit](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs) and which I could uses the debug and to fix the bug?

**Comment by Luca7993** [comment]
Hi Oleg,
sorry for late answer:
we have had some changes in our azure service and that was the reason because the demo wasn't available.
I've moved the demo here: [jqgrid test](http://testjqgridalimede2.azurewebsites.net/Home/ColumnChooserGroupHeaders?type=original)

I've edited the demo for using the code from RawGit.
There aren't any hidden columns in the demo

let me know if I can help you

**Comment by OlegKi** [comment]
Thanks for the demo! I posted 3 small changes: [this one](https://github.com/free-jqgrid/jqGrid/commit/eb2b98e26a799c2134d413a8a4c8b13dc9083d02), [this one](https://github.com/free-jqgrid/jqGrid/commit/e3a36e95433be30237398dd6a0c5d8b7ca576b0b) and [this one](https://github.com/free-jqgrid/jqGrid/commit/cb2d6733cf5225aab4ee19e577c1e8a652fea22a), which seems to fix the bug, which you reported. Please test the last version of `columnChooser` and close the issue if everything works correctly now.

**Comment by OlegKi** [comment]
@Luca7993: Is the bug is fixed? Please, close the issue in the case.

**Comment by spektumus** [comment]
Thanks for your great work on the free jqGrid. 

Unfortunately [this](https://github.com/free-jqgrid/jqGrid/commit/b8cd89bfaca8e57f72db4f894fdddccdf1908a4d) commit has broken the reordering for grids that don't have any grouped headers.

**Comment by Luca7993** [comment]
everything is working for me

thank you!

**Comment by OlegKi** [comment]
@Luca7993 and @spektumus : You are welcome!
