### ISSUE TITLE
Customizing checkbox HTML

### ISSUE THREAD

**Issue by Blipz** [free-jqgrid/jqGrid#262]
Hi,

In grid.base.js the checkbox creation is done this way:

`checkboxHtml = "<input type='checkbox'" + " id='jqg_" + p.id + "_" + rowid +
							"' class='cbox' name='jqg_" + p.id + "_" + rowid + "'" +
							(checked ? " checked='checked' aria-checked='true'" : " aria-checked='false'")`

Would it be possible to allow customization of the checkbox attributes (like the name or the value), in order to have more control over what is sent to the server at form submission?

Thanks and keep up the good work!

**Comment by OlegKi** [comment]
In general all is possible, but if you ask for the feature you should understand that somebody have to invest some time for the corresponding implementation. The first look at the code shows that it **require** that `checkboxHtml` be `<input>` element (without wrapping inside of any other one) of the type checkbox (`type='checkbox'`). The rules for building of `id`, `checked` and `aria-checked` is fixed too. The checkbox have to have class `cbox` additionally. The value of `name` attribute, existence of other classes as `cbox` or existence of any other attributes (for example `style`, `title` and so on) is possible in general. It's difficult for me only to provide a exact suggestion for the new feature. The new callback or option should be easy in use and still hold the compatibility with old versions of jqGrid.

The only simple implementation, which I see, would be providing callback with Boolean `checked`  and `rowid` as parameters. The callback have to build correct formatted string, which represent `<input type='checkbox'"`. The callback have to **hold all above rules and jqGrid will *not validate* the rules additionally**. Any other implementation seems to me too complex.

**Comment by Blipz** [comment]
OK that's fine for me, I'd be happy to start working on a pull request with your suggested implementation.

Alternatively, would it be too complex for the callback to return an array like `{name: "myname", title: "check me"}`, and to let the addMulti function do the string formatting?

**Comment by Blipz** [comment]
Hi, here are my implementation attempts:

- with a callback returning a string: 8e2411670bb772ab68c4c61cda6e1a2bc0060f84
- with a callback returning an object: 2b1886fab327e61d5f63a8772ff2a62f19cf144e

**Comment by OlegKi** [comment]
Sorry, for the late answer - I was busy the last week. The code from [callback returning a string](https://github.com/free-jqgrid/jqGrid/commit/8e2411670bb772ab68c4c61cda6e1a2bc0060f84) is in general good, but it use old style conversion for parameters (`rowid` and `checked`). The new style, which I try to use in new callbacks consist from having **one parameter** with named properties. Such callbacks can be easy extended and such style is practical if one need to forward many parameters, but only someone can be really important. The callback `hasMultiselectCheckBox` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L2255-L2258)) is an example. I posted [the changes](https://github.com/free-jqgrid/jqGrid/commit/475df0d26f934c897985960ed6f3312878d5a642). One can use now `checkboxHtml` in the form for example:
```JavaScript
checkboxHtml: function (options) {
	return "<input type='checkbox' id='jqg_" + this.id + "_" + options.rowid +
		"' class='cbox' name='jqg_" + this.id + "_" + options.rowid + "'" +
		(options.checked ? " checked='checked' aria-checked='true'" : " aria-checked='false'") +
		"/>";
}
```
The callback [callback returning an object](https://github.com/free-jqgrid/jqGrid/commit/2b1886fab327e61d5f63a8772ff2a62f19cf144e), which you suggested can't be used because of performance reason. All callbacks used during filling the grid (custom formatter, `cellattr` and `rowattr`) returns **strings** because processing of strings is very quickly in all version of web browsers. The usage of `checkboxHtml = $("<input>", attr)[0].outerHTML;` is **much slowly**. One could use alternatively the code like in `rowattr` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L3424-L3457)) or like in `cellattr` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L3121-L3204)), but the corresponding changes will be relatively long and will required good testing. Because of that I decided to implement the simple version of `checkboxHtml`.

I hope that the committed changed are good enough for the practical usage.

**Comment by Blipz** [comment]
Thank you for your time and your detailed explanations, that's great!
