### ISSUE TITLE
SortableRows and cellEdit

### ISSUE THREAD

**Issue by Blipz** [free-jqgrid/jqGrid#263]
Hello,

Not sure whether it is a bug or not, but the behavior of `sortableRows` used together with `cellEdit` has changed between versions 4.13.2 and 4.13.3.

See here: https://jsfiddle.net/s18gg05v/

As soon as a row is dropped at a new position, the cell edition becomes active, which I don't think is the expected behavior.

**Comment by OlegKi** [comment]
Sorry, but I can't reproduce any problem in your demo. Which web browser you used in your tests? Probably there are misunderstanding in the terminology. You wrote "the cell edition becomes active". I understand that that some cell become editing after drag&drop. I can't reproduce the effect (at least in Chrome 52, IE11 and Mictosoft Edge). The only change in the `sortableRows` was [this one](https://github.com/free-jqgrid/jqGrid/commit/5834625cf40198a979833552c96ad1dbd529bd95). Please report how one can reproduce the problem. Please use only non-minimized versions of the free jqGrid (`jquery.jqgrid.src.js`) and use the latest version of jqGrid from GitHub (like `https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js` see [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit) or the latest published release: 4.13.4).

**Comment by Blipz** [comment]
You are right, it seems to be Firefox-specific (I tested with both versions 38 and 42), but couldn't reproduce the issue with Chrome.

The demo was updated to use a non-minimized 4.13.4 jqGrid version: https://jsfiddle.net/s18gg05v/1/

**Comment by OlegKi** [comment]
Sorry for the late answer. I think that the problem, which you describe is the problem of correct working of jQuery UI Sortable in Firefox. The problem is that it trigger in some situations unneeded (wrong) `click` event after the end of dropping. The problem is old and there are some workarounds, like the usage of `helper: 'clone'` option. See [the answer](http://stackoverflow.com/a/2977904/315935) posted 6 years ago. You can verify on the demo https://jsfiddle.net/s18gg05v/2/ that the problem is not exist now. There are small problem with the width of columns of the moved row (only at the first time).

**Comment by Blipz** [comment]
Thank you, the workaround works well.
