### ISSUE TITLE
subgrid dynamic Select Dropdown

### ISSUE THREAD

**Issue by boulepick** [free-jqgrid/jqGrid#267]
Hi Oleg,

in my application I'm implementing a subgrid where the data is remote based on the row that is being expanded. the issue that i'm having is getting a dynamic Select in inline edit mode to correctly display the selected value and the inline edit to correctly populate the Select dropdown based on another cell value in the same row. I could not find a solution based on your past post posted solutions. My situation is a little bit different where each row can have different value for the lookup cell therefore different list for the select. below is the code for the subgrid. both the table and the select data are coming from server.

"getGridParam" and "getCell" are not working, i cannot use "getRowData" since the row is in edit mode.
is "getGridParam" an issue for subgrids where data is loaded remotely?

		function subItemGrid(subgrid_id, row_id) {
			var childGridID = subgrid_id + "_table",
				childGridPagerID = subgrid_id + "_pager";
			
			$("#" + childGridID).jqGrid({
				url 		: getUrl,
				editurl 	: updUrl,
				mtype		: "POST",
				datatype	: "JSON",
				page		: 1,
				regional	: lang,
				autowidth   : true,
				height      : '100%',
				rowNum		: 30,
				subGrid		: true,
				sortorder   : "asc",
				hidegrid    : false,
				gridview    : true,
				pgbuttons   : false,
				pgtext      : null,
				viewrecords : false,
				guiStyle	: "bootstrap",
				iconSet		: "fontAwesome",
				autoencode	: true,
				threeStateSort		: true,
				forceClientSorting	: true,
				postData 	: gridPostData,
				idPrefix	: "u_" + row_id + "_",
				colNames 	: colName,
				caption 	: headerCaption,
				pager 		: "#" + childGridPagerID,
				ondblClickRow	: editRow,
				subGrid 	: false,
				footerrow 	: true,
				userDataOnFooter: true,
				colModel : [
					{	name	: 'pID',
						editable: true,
						width	: 5,
						hidden	: true
					},
					{	name	: 'sID',
						width	: 90,
						align	: 'left',
						editable: true,
						formatter: 'select',
						edittype: 'select',
						editoptions: {
							value : function() {
								
								console.log($(this)); // return object ok
								console.log($(this).rowId); // return undefined
								console.log($(this).jqGrid('getGridParam','selrow')); // return null
								
								// get row sId to pass to loadList
								// sID = $(this).sID;
								// loadList is an async ajax function fetching the list from the server
								return loadList(sID);
							},
							dataInit: function (elem) {
								$(elem).addClass('input-xs');
							}
						},
						editrules: { 
							required: true
						}
					},
					{	name	: 'quantity',
						width: 60,
						align: 'center',
						editable: true,
						editoptions : {
							dataInit: function (elem) {
								$(elem).addClass('inline-edit-cell form-control input-xs');
						  }
						},
						editrules : {
							required: true
						}
					},						
					{	name	: 'value',
						width	: 50,
						align	: 'center',
						editable: false,
						formatter: 'integer',
						summaryTpl: "<b>{0}</b>", // set the summary template to show the group summary
						summaryType: "sum",
						decimalPlaces: '2'
					}
				],
				loadComplete: function () {
					var	valueSum = $("#"+ childGridID).jqGrid('getCol', 'value', false, 'sum');
				
					$("#"+ childGridID).jqGrid('footerData', 'set', { 
						quantity: 'Total:',
						value	: valueSum,
					});
				},					
			})			
		}

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand the problem. First of all it seems more like the problem in independent from the subgrid problematic. You create just a grid and you use `formatter: 'select', edittype: 'select'`. You posted relatively long code, but without the most important part: the code of `loadList` used in `value`. There are no test data too. Thus I have to guess some things.

First of all you wrote in comment that "loadList is an async ajax function fetching the list from the server". If it's really so that you use jqGrid in the wrong way. The `value` function have to work **synchronous**. You can't make async ajax call and immediately return the value (see `return loadList(sID);`). jqGrid supports `dataUrl` for asynchronous filling of the select used during editing. The `dataUrl` can be used as callback function, which returns URL based on the options (see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.common.js#L465-L479) of code). Moreover, the usage of `formatter: 'select'` is either very suspected or wrong. `formatter: 'select'` will be used **during filling the grid body**. Thus the `value` have to be known at the moment and the `value` is *independent from the row selected*. I described in [the answer](http://stackoverflow.com/a/19427444/315935) the way of setting column properties (like `value`) inside of `beforeProcessing`. It allows to extend the server respond with the `value` used by `formatter: 'select'`. You can, for example, set `formatoptions.value` and to use `editoptions.dataUrl` additionally. I suppose that it should solve your problem.

**Comment by boulepick** [comment]
Thanks Oleg,
below is the code for loadList.

		`function loadList(gridID){
			var 	list,
					itemID = getCellValueInEdit(gridID,'itemID');
			
			$.ajax({
				url: urlFetchList,
				type: "POST",
				dataType: "JSON",
				data : {'lang':lang,'itemID':itemID},
				timeout: 60000,
				async: false,
				cache:false
			}).done(function(response){
				if (response !== undefined && response.length > 0) {
					list = response;
				}
			});
			return list;
		}

		// function get cell value in edit mode
		function getCellValueInEdit(gridID,colName) {
			var thisID = $("#" + gridID).jqGrid('getGridParam','selrow'),
				 itemVal = $("#" + thisID + '_' + colName).val();
				 currItemID = itemVal;
			return itemVal;
		}`

so basically each row when in edit mode would query the server for the corresponding list of the sID of that row. something like this

row 1 => sID = product1 => list {id1:eproduct1, id2:eproduct2, id3:eproduct3}
row 2 => sID = product2 => list {id123:eproduct24, id243:eproduct43, id45:eproduct345},
.....
row 8 => sID = productxy => list {idxyz:eproductxyz, idrte:eproductert}.

i understand your point about the formatter:'select' as it would need to have all the values before end so jqGrid can build the select. Also if i understand well your example is assuming the select list is the same for all of the rows and small enough to preload, my data for the select dropdown is quite big and different; therefore i don't think it would not be as efficient. so i prefer to query the server for the data only when editing 

so i guess when loading the grid i will return the value of the select and build the select dropdown when in editing mode.
however my issue now is to get the value of sID in editing mode and the current code is not as 'getGridParam','selrow' is returning null.

Thanks

**Comment by OlegKi** [comment]
Look at [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3_.htm) and [this one](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3__.htm). Both use
```JavaScript
{ name: "ship_via", formatter: "select", formatoptions: { value: "TN:TNT;DH:DHL;FE:FedEx" },
    edittype: "select", editoptions: { dataUrl: ... }}
```
Thus `formatoptions.value` with **full** different values from the data of the column `ship_via`. The `dataUrl` be used to create **individual** list for every row editing. I used `dataUrl` defined as the function in the first demo
```JavaScript
dataUrl: function (rowid, value, cmName, options) {
	var item = $(this).jqGrid("getLocalRow", rowid);
	return "ShippedVia.htm?" + $.param({
		id: rowid,
		ship_via: value,
		name: item.name
	});
}
```
and `postData` defined as the function in the second demo
```JavaScript
postData: function (rowid, value, cmName) {
	var item = $(this).jqGrid("getLocalRow", rowid);
	return {
		id: rowid,
		ship_via: value,
		name: item.name
	};
}
```
One can use `getRowData` instead of `getLocalRow` if you have no local data.
[The third demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3___.htm) adds the option
```JavaScript
ajaxSelectOptions: { type: "POST", dataType: "html" }
```
to use HTTP POST instead of the default HTTP GET verb. In property `dataType: "html"` is default for `ajaxSelectOptions`, but you can use `dataType: "json"` to make Ajax call like in your existing code. One can use `buildSelect` to convert JSON data returned from the server to HTML fragment `<select>...</select>` with all options returned from the server. I used just static file
```html
<select>
    <option value="FedEx">FedEx</option>
    <option value="TNT">TNT</option>
    <option value="DHL">DHL</option>
</select>
```
for the demo.

I think you can implement all your requirements in the way.

**Comment by boulepick** [comment]
Thanks Oleg,

i have tried that implementation already based on previous post that you answered in stackOverflow. The issue here is that this line var item = $(this).jqGrid("getRowData", rowid); is returning a blank object. And as per the Documentation i should not be using getRowData in edit mode and this is exactly what i'm doing. when the user double-click on the row or click the edit button to select the dropdown. So i need to get the value of a column when editing. i'll guess i'll use jQuery something like 
itemVal = $("#" + prefix + rowid + "_colName").val();  with prefix being the idPrefix of the subgrid.

**Comment by OlegKi** [comment]
You can use `jQuery.val()` to get the data, but I guess that the origin of your question is filling of jqGrid in the wrong way. It seems that `itemID` in the most important information about the row. Why you don't use the value as the rowid? You don't posted `colModel`  which you use, but one uses typically `key: true` in the column, which contains the rowid. Alternatively one can use `jsonReader: { id: "itemID" }`. After that one can typically **remove** unneeded column `itemID`. You will don't need to use neither `getRowData` nor `getLocalRow` and to use `rowid` instead.

**Comment by boulepick** [comment]
I have other columns in the colModel and a unique rowID already defined. the code i posted was strip down to show the issue. thanks for your help. 
You should also consider adding the option to get a column information in edit mode, whether for validation or comparison I will look to implement your recommendations. I'm closing this

Thanks.
