### ISSUE TITLE
js Error on clicking right to the freezed column multiple times

### ISSUE THREAD

**Issue by imvkumar** [free-jqgrid/jqGrid#269]
fbRows undefinied

**Comment by OlegKi** [comment]
Sorry, but I can't reproduce the problem. Which version of free jqGrid you use? Which web browser used used in your tests? In which line of `jquery.jqgrid.src.js` code you get the error "fbRows undefinied"? You should be able to see the line number if you would start debugging of your demo in Developer Tools of IE/Chrome/Firefox. Could you provide the demo, which uses non-minimized version of jqGrid and to describe the test case more detailed? I can fix the problem only if I can reproduce it.

**Comment by imvkumar** [comment]
This problem was there in jqGrid 4.9.2 - free jqGrid as well as this is there in latest version jqGrid 4.13.5-pre - free jqGrid.
at line #5394 if (p.singleSelectClickMode === "toggle" && !p.multiselect && oldSelRow === ri) {
f (this.grid.fbRows) {..

We fixed it locally as follows:
if (typeof this.grid == 'undefined') {
							        $tr = $tr.add($self0[0].rows[ri]);
							    }
							    else if (this.grid.fbRows) {
							        $tr = $tr.add(this.grid.fbRows[ri]);
							    }

Please let me know, if you need more information.

**Comment by OlegKi** [comment]
Thank you very much for the bug report! The main reason of the problem is the usage of `this.grid.fbRows` instead of `ts.grid.fbRows`. I committed [the changes](https://github.com/free-jqgrid/jqGrid/commit/fb496e91e6fa684a450d7fe716bd67bf33b0e4fa). Please test the code from GitHub (see [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit) for example) and close the issue after your confirm that the bug is fixed.

**Comment by imvkumar** [comment]
> Thanks for fixing this issue.
