### ISSUE TITLE
Cell focus problem

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#271]
I have a custom column, which display a TextBox directly, and the ediable is set to false(I just want user to edit textbox directly, instead of click the cell and go into edit mode to create textbox).
But the problem is , in editCell method, I found the following code executed always
setTimeout(function () {
     $("#" + jgrid.jqID(p.knv)).attr("tabindex", "-1").focus();
}, 1);

Since I'm using it in mobile browser, the mobile keyboard will shown and gone.
Any advice to improve this?

**Comment by OlegKi** [comment]
First of all it's very helpful if you always provide the demo which can be used to reproduce the reported problem. Please include more detailes of your tests, like which version of free jqGrid you use, which "mobile browser" (there are the most web browsers for mobile devices) on which device (some model of iPad, iPhone or Android phone). Moreover, I don't understand the reported problem. You want to allow that the user edit the data and you created TextBox directly (probably with respect of formatter). It's not the good idea in my opinion because the modifications should be *saved* or *discarded* at one moment of the time. The usage of direct TextBox gives the user illusion that the data are already modified, but it's not so. You will have to implement some kind of saving. Moreover it's absolutely unclear for me why you still use cell editing, if you create direct TextBox. Finally it's unclear why the showing of the mobile keyboard can be a problem. If the user need to edit the text of the TextBox then the user have to use the keyboard. Isn't so? Please, describe the problem more clear.

**Comment by ryanlin1986** [comment]
Never mind, thanks I get it solved, in onCellSelect I set jqGrid.p.editable=false;
and then setTimeout(()=>{jqGrid.edtiable=true}); Which prevents jqGrid to call the focus code above.
