### ISSUE TITLE
Wrong ukrainian i18n filenaming

### ISSUE THREAD

**Issue by Globulopolis** [free-jqgrid/jqGrid#291]
Hi!
grid.locale-ua.js must be named as grid.locale-uk.js

**Comment by OlegKi** [comment]
Why the file `grid.locale-ua.js` **must** have another name? Any name is OK for the correct functionality of the jqGrid. **Any renaming of the files could follow breaking of existing projects** after updating to the next version of free jqGrid.

About the names of local files in general:
There are exist multiple international standards about the subject. Someone are more oriented on the language and another are oriented on countries. For example, [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Partial_ISO_639_table) contains  two-letter codes of **languages**, where **UK** means Ukrainian language. Another international standard [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) defines subdivisions (e.g., provinces or states) of countries, where **UA** means Ukraine country.

The old jqGrid 4.7, which was the basis of free jqGrid, contained [grid.locale-ua.js](https://github.com/free-jqgrid/jqGrid/blob/v4.7.0/js/i18n/grid.locale-ua.js) and I see no advantage for the existing users of jqGrid in any renaming of the files. Any naming conversion are good enough in my opinion.

**Comment by Globulopolis** [comment]
Very strange explanation... UA is a country code, but we speaking about language code.

PS! Still rename by the hands.

**Comment by OlegKi** [comment]
Sorry, but I can't follow you. Who is "speaking about language code"? I personally use "locale" terminology, which is more neutral. The names used as locales are described in [the comments](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/i18n/grid.locale-ua.js#L177-L181) of the file `grid.locale-ua.js`.

The JavaScript code of the file `grid.locale-ua.js` registers 3 locales: `ua`, `uk` and `"uk-UA"` (see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/i18n/grid.locale-ua.js#L182-L184)). You can include multiple locale files (for example, `grid.locale-ua.js` and `grid.locale-de.js`) and then use `locale: "ua"`, `locale: "uk"` or `locale: "uk-UA"` option of jqGrid to apply the locale settings from the file `grid.locale-ua.js` or `locale: "de"` or `locale: "de-DE"` to apply settings from `grid.locale-de.js`.

In any way `grid.locale-ua.js` is just a **filename**. I explained you that if I would rename it in free jqGrid then **everybody, who use it currently as `grid.locale-ua.js`, will *have to* make the same modifications of the filename**. Thus renaming of files just produce unneeded TODOs for many people without any  advantages.

You are still free to use any names of your local copy of the files, because both MIT/GPL-licenses allow such changes.

**Comment by Globulopolis** [comment]
Ok. Thank you for explanation. I confused with the `locale` settings.
