### ISSUE TITLE
Actions formatter not check grid checkbox

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#292]
I have an actions formatter with a custom edit button that has launches a jqueryUI dialog with an onClick. Every time I click on the edit icon it also checks the grid row (which I don't want). Is there a way for me to disable this for the actions formatter only?

I tried to use "beforeSelectRow" with "$(e.target).hasClass("hasmenu")" (that I use for normal links) but that event doesn't even fire for the actions formatter with the jqueryUI dialog.

I've included a screenshot of my problem:

![actions](https://cloud.githubusercontent.com/assets/379016/22789441/27e9c0ac-eea0-11e6-933c-8a383663a4ba.gif)

**Comment by OlegKi** [comment]
Selection of the row inside of `formatter: "action"` was already in old version of jqGrid. I hold selection for the compatibility reasons, because someone could used `selrow` or `selarrrow` inside of his event handles.

The existing code of `formatter: "action"` calls `setSelection` method explicitly (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/jquery.fmatter.js#L699)). Thus no `beforeSelectRow` callback be called in the case, only `onSelectRow`.

I would suggest you to use `onSelectRow` to unselect the previously selected row. The corresponding code could look like
```JavaScript
onSelectRow: function (rowid, status, e) {
    if ($(e.target).closest(".ui-jqgrid-actions").length > 0) {
        $(this).jqGrid("resetSelection", rowid);
    }
}
```
or something close to above.

**Comment by Gazoo** [comment]
Works like a charm. Many thanks!
