### ISSUE TITLE
SetRowData and keep the row editable

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#302]
I am trying to add a custom copy button in inline actions of a jqgrid with the following behavior: when the button is clicked, the data of the selected row are copied into the last row of the table, formerly set as empty. I am able to display the button and to copy the row data in the last line using setRowData method but, once updated with the data of the selected row, the fields of the last row are not in the edit mode, as shown in the following screenshoot:

![picture1](https://cloud.githubusercontent.com/assets/26380480/24204112/cb19cd7a-0f17-11e7-9b70-5c07bc24ebd0.png)

Here, the code of the function used to add an empty line at the end of the table on GridComplete (addEndRow) and the code of the function used to pass the data of the selected row to the last row (setLastRow).
```

 addEndRow = function () {
                var rows = $("#prodgrid")[0].rows,
                   lastRow = rows.length;
               
                var parameters =
                   {
                       rowID: lastRow,
                       initdata: {},
                       position: "last",
                       useDefValues: false,
                       useFormatter: false,
                       addRowParams: { extraparam: {} }
                   }

                $("#prodgrid").jqGrid('addRow', parameters);
            }

            setLastRow = function (rowId) {

               
                var rows = $("#prodgrid")[0].rows,
                    lastRow = rows[rows.length - 1].id;

                $('#prodgrid').jqGrid('setRowData', lastRow, $('#prodgrid').jqGrid('getRowData', rowId));
               
                $('#prodgrid').editRow(lastRow, true);
              }
```
I am looking for a solution in order to keep editable the last row, once updated with the data from the selected row. In addition, I wish that, once the last row has saved, a new line is added to the table and the last line return to be empty. Is there any walk around to reach this functionality?

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand your requirement. . If you use `addRow`, then you can use `initdata` option of `addRow` to fill the new row with some data. What `addRow` do is calling of `addRowData`. See [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/grid.inlinedit.js#L533-L542) of code. You can easy write your own code, which do almost the same, but which implement all additional functionality, which you need.

**Comment by Flanders89** [comment]
In order to simplify the issue, my problem is that I am not able to open a row to enable the inline editing of the data using a jqgrid method instead to click the `edit` button in the `actions` column.
Is there any method that allows doing that? I tried `editRow` but it does not work.
Thanks

**Comment by OlegKi** [comment]
You wrote: "I am not able to open a row to enable the inline editing". How a row could be "opened"? You write about **inline editing**, but I can imaging some kind of opening only in editing dialog, in case of usage form editing. Click on "edit" button of actions column starts editing of the row. Depend on the `formatoptions`, which you use it could be inline editing or form editing. One can start editing with respect of APIs. `editRow` starts editing of editable columns and `editGridRow` opens dialog wich includes editable columns in the form. **What problem you have? Which relation has `setRowData` method to the problem?**

I think, that it would be better if you create the demo, which demonstrates the problem. In any way, you should describe your problem more clear and post some JavaScript code, which explains what you do. Please use the following terminology:

- "editable" is the property in `colModel`, which shows whether the cells in the column *could be* edited. "Editable" means the *ability* to start editing of the cells of the column.
- "editing" row/cell means that the row/cell is **currently** in editing mode. It means that the user sees input/select or other controls in the cells instead of typically texts, displayed in non-editing cells/rows. The user is able to change the data and save the modification by pressing of <kbd>Enter</kbd> key, by click on "Save" button or by click on any other row of the grid. Which ways is allows for the user for saving depends on your implementation (your code).
