### ISSUE TITLE
Change shrinkToFit dynamically

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#307]
I'd like to set the shrinkToFit option dynamically depending on the size of the window. 
Is there a way to do it? 
Another question while I'm a it, What is the event, like onSelectRow: function (){}, for the click on the inline edit button? Thanks,

**Comment by OlegKi** [comment]
Could you describe more detailed, **why** you need to change `shrinkToFit`?

I'm not sure that you correctly understand what `shrinkToFit` do. The property be used during calculation of **initial** width of columns and the changed width of columns during indirect (implicit) **changing of the width of the grid**. If you call *explicitly* (directly) `setGridWidth`, then you can use the last parameter (`shrink`) independent from the value of `shrinkToFit`. By the way, the width of the grid will be not changed inside of `onSelectRow` and thus I don't understand, which advantage could have changing `shrinkToFit` inside of `onSelectRow`.

**Comment by bolzo5** [comment]
Thank you, the shrink parameter was exactly what I needed! everything works fine now, and about the onSelectRow, it doesn't have anything to do with the shrinkToFit, I was just wondering if there is an event for the click on the inline edit button( the font awesome pencil icon).
Thank you again

**Comment by OlegKi** [comment]
You are welcome! You can use for example `jqGridInlineEditRow` event. The event will be fired on start of inline editing independent whether it will be started directly by call of `editRow` or indirectly by usage of `formatter: "actions"` or `inlineNav`. You can use of cause `oneditfunc` callback instead of `jqGridInlineEditRow` event, but specify `oneditfunc` callback inside of `inlineEditing` option of jqGrid.

**Comment by bolzo5** [comment]
ok, thanks!
