### ISSUE TITLE
Fixed editable row

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#309]
I'd like to add a copy row button to my grid, such as that on the click of the button the data of the selected row gets copied into a fixed row which is always visible even with the infinite scrolling enabled.

I'm trying to make this row inline editable and then at the click of a save button add the edited data into a new row in the grid.
I've tried to use the footer for this, but I can't find a way to make it editable.
Thanks

**Comment by OlegKi** [comment]
Probably you mean virtual scrolling (`scroll: 1` or `scroll: true`) under "infinite scrolling". It's the option, which exist in free jqGrid only because of compatibility reasons. I don't recommend to use it because of existing many restrictions and disadvantages, which can't be easy gefixt. You should remove `scroll` option first of all and to use `initdata` of `addRow` to initialize the data of new added row. The code could be like on the demo https://jsfiddle.net/OlegKi/r0wbtdk1/
