### ISSUE TITLE
Columns Sort

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#312]
I'm using the standard column sort, but I'm facing some problems:
- at the first click the column order is ASC and at second click the order is DESC , there is any way at third click to remove the order and restore the original one?
- currently the column sort is not working for number order, If I sort by ASC a column with numbers (1 to 10) I get 1, 10,2,3 so it's ordering as they are string instead numbers, there is any way to solve it?

**Comment by OlegKi** [comment]
The option `threeStateSort: true` restore the original sort order on the 3-d click on the column header.

The columns will be sorted based on `sorttype` or `sortfunc`, which can be defined in `colModel`. One uses typically `sorttype: "number"` or `sorttype: "integer"` in columns, which should display the numbers. Free jqGrid provides some templates, which simplify definition of columns with numbers. You can use `template: "number"`, `template: "integer"`, `template: "booleanCheckbox`, `template: "actions"`, ... See [the code](https://free-jqgrid.github.io/getting-started/index.html#type_of_data_code) as an example.

**Comment by Flanders89** [comment]
It works thanks for the quick response! Also is possible to customize the sort icon currently displayed?

**Comment by OlegKi** [comment]
Look at the New Features section of the [README](https://github.com/free-jqgrid/jqGrid#new-main-features-implemented-in-the-version-4140-compared-with-4136) of the version 4.14.0. You will find the demo https://jsfiddle.net/OlegKi/ffgg9wdu/, which demostrierte customizing of the sort icons by extending `$.jgrid.icons` and by usage `sortIconName` callback. It allows to different icons in different columns. The demo depend https://jsfiddle.net/OlegKi/ffgg9wdu/ uses icons depends on the type of data in the columns: numeric, text and other (lake dates).

**Comment by Flanders89** [comment]
I tried to add 
 $.extend(true, $.jgrid.icons, {
                    customFontAwesome: $.extend(true, {}, $.jgrid.icons.fontAwesome, {
                        sort: {
                            common: "",
                            asc: "fa-sort-amount-asc",
                            desc: "fa-sort-amount-desc"
                        }
                    })
                });

and the  iconSet: "fontAwesome", parameter inside the jqgrid but I'm still seeing the old icons on sorting click, I miss something?

Also there is any jqgrid javascript event fired on the sorting icon click?

**Comment by OlegKi** [comment]
It's better you open new question where you describe exactly **what you try to implement**. Moreover, you should open *new issue* or to post the question to stackoverflow. My demo https://jsfiddle.net/OlegKi/ffgg9wdu/ uses additionally `sortIconName` callback for example and set some CSS rules. The minimal form of `sortIconName` from the demo would be
```JavaScript
sortIconName: function (options) {
    return $(this).jqGrid("getIconRes", "sort." + options.order)
}
```
jqGrid allows *many ways* to display the sort icons. The standard behavior means displaying **two** sorting icons at once making one from the icons gray. The icons will be displayed **one over another**. There are exist the option `viewsortcols`, which allows to display both icons near another (`"horizontal"` instead of `"vertical"`). The demo https://jsfiddle.net/OlegKi/ffgg9wdu/ displays **only one** sorting icon.

**Comment by Flanders89** [comment]
It works now thanks
