### ISSUE TITLE
JqGrid sizing

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#314]
I'm facing a problem with jqgrid about table sizing. 
When I create the jqgrid I load data dinamically from DB so I don't know exaclty how much space the column will need, if is possible the column has to auto adapt basing on their content lenght.
Also the grid should have a min and a max space and if the grid exceed the max space(due the column auto adapt basign on their content) should appear the horizontal scroll bar since the first load.

There is any example that I can use to manage this situation?

**Comment by Flanders89** [comment]
Please check my demo 
http://jsfiddle.net/FlandersA90/HJema/591/

**Comment by OlegKi** [comment]
Yes you can, but you should use the correct version of free jqGrid http://jsfiddle.net/OlegKi/HJema/598/

**Comment by Flanders89** [comment]
Your example is working as expected, but I've discovered that auto adapt column seems that cannot be bigger than 300px, is something that we can update or remove this limit?

**Comment by OlegKi** [comment]
there are exist `maxColWidth` and `minColWidth` properties of `autoResizing`, which can be specified either for all columns as `autoResizing` option of jqGrid or as property in `colModel` of the corresponding column. Look [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/grid.base.js#L2760-L2761) with defaults used by free jqGrid. You can increase the maximal column width either for all columns or for specific column.

**Comment by Flanders89** [comment]
Thanks!! And about the min table width is something that I can do? if I have a space of 1000px and my grid cover only 500px I wanna set a min width of 1000 and columns will auto adapt with the extra space, is something possibile?

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand you. Try the demo http://jsfiddle.net/OlegKi/HJema/599/. It uses the content of the columns to calculate initial width of every column. Then it expand/collapse the columns **holding the proportions** of the column widths. One can additionally resize the browser window and the width of all columns will be adjusted too. Is it what you need?

**Comment by Flanders89** [comment]
If I use the property autowidth: true,  it solves the problem when table is smaller than then container space, but if the table is bigger than the space of the container it squeeze my table instead to show the horizontal scroll bar as you can see here
 http://jsfiddle.net/FlandersA90/swyw066n/1/

there is any way to solve it?

**Comment by OlegKi** [comment]
Look at the demo http://jsfiddle.net/OlegKi/swyw066n/7/, which I created closed to the demos from [another old issue](https://github.com/free-jqgrid/jqGrid/issues/289). I think it does what you need.

**Comment by Flanders89** [comment]
your solution works very good, but there is still a small thing something during the page load seems that the grid needs some time to be correctly resized, there is any way to show my custom loading during this rendering time?

**Comment by OlegKi** [comment]
I don't see and performance problem on the demo http://jsfiddle.net/OlegKi/swyw066n/7/. If you use **paging**, which is strictly recommended, then you should not have any essential performance problems. Auto-resizing of the grid with 20 rows and no so many columns can be done quickly enough.

**Comment by Flanders89** [comment]
As you can see in demo http://jsfiddle.net/FlandersA90/swyw066n/9/ sometimes during the paging you will see the yellow color (is the backgroung color of the div) before the grid resize correctly

**Comment by OlegKi** [comment]
Sorry, but I'm not sure that I understand the goal of the conversation. I developer free fork of jqGrid based on jqGrid 4.7 and share the results with other. Any **bug reports** or **constructive suggestions** to improve free jqGrid are welcome.

You original question was about the usage of auto-resizing options of jqGrid and I informed you how you can use there in your case. The demo http://jsfiddle.net/OlegKi/swyw066n/14/ takes between 150 and 500 ms. If you set the optimal width of all columns and remove `autoresizeOnLoad: true` option then you will get http://jsfiddle.net/OlegKi/swyw066n/13/ with a little better timing. Comparing two demos you will see that auto-resizing is really quickly and takes about 50ms. It's so and I find it good performance.

The flicker exists because the width of the columns of the grid and the width of the grid will be *first* resized to small width corresponds to the *content* of every column and then resize the grid (and all the columns) once more based on the with of the outer div. The code of free jqGrid is opened. You can examine the code of  `autoResizeAllColumns`, `autoResizeColumn` [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/grid.base.js#L7908-L7988). You will see that the main work does the method `getAutoResizableWidth`, which get the optimal width of the columns. Thus you can use more large initial values of `width` for the columns and to call your implementation of auto-resizing in `jqGridAfterLoadComplete` event. It allows to skip one step, where the `width` of the columns and the width of the grid will be shrinked. You can calculate the *final* width of the columns based on the width of the outer div and to use the corresponding values as parameters of `setColWidth` and `setGridWidth`. As the results you will eliminate flicking and improve a little the total performance of autoresizing. You can share your results with other like I do.
