### ISSUE TITLE
Stack overflow with Inline Editing and Custom Function as 'editable'.

### ISSUE THREAD

**Issue by kmoens** [free-jqgrid/jqGrid#315]
In free jqGrid v4.14 a change was introduced in order to let the getRowData() function take the values of cell editing into account.

Unfourtunately this change is breaking when one uses the editable property in the colModel as a function (ref: https://github.com/free-jqgrid/jqGrid/wiki/editable-property-of-colModel-as-function).

Basically as soon as we attempt to save a row, we encounter a stack overflow in JavaScript. This stack overflow did not exist with an earlier version of free jqGrid.

Simple example which reproduces the bug:
https://jsfiddle.net/kmoens/j28uoo44/6/

The same example, but with free jqGrid v4.13.6
https://jsfiddle.net/kmoens/j4ney3us/

**Comment by OlegKi** [comment]
Thank you Kenny for reporting the bug! I will fix it in the next time.

Currently I suggest you to use the following workaround. First of all you should **always** prefer to use `getLocalRow` instead of `getRowData` if the grid has local data (`datatype: "local"` or you use `loadonce: true`). If works much more quickly because it returns just the reference to the local object, which hold the data of the row. The problem will be not exist in the case: https://jsfiddle.net/OlegKi/j28uoo44/9/. Only if you have to use server side paging and use `datatype: "json"` (or `datatype: "xml"`) without `loadonce: true` then the usage of `getRowData` inside of `editable` callback could be a problem. In the case I suggest you to modify
```JavaScript
function myTestEdit(options) {
  var rowdata = jQuery("#grid").jqGrid('getRowData', options.rowid);
  return rowdata[options.cmName] == 200;
}
```
to
```JavaScript
function myTestEdit(options) {
  var cellValue, editingInfo = $.jgrid.detectRowEditing.call(this, options.rowid);
  if (editingInfo != null && editingInfo.savedRow != null && editingInfo.savedRow[options.cmName]) {
  	// the row is in editing mode and the filed options.cmName was editable
    cellValue = editingInfo.savedRow[options.cmName]
  } else {
    // the row is not editing now we can use getCell to get the value of the cell 
  	cellValue = $(this).jqGrid("getCell", options.rowid, options.cmName);
  }
  return cellValue == 200;
}
```
which do practically the same, but which has no recursion.
See the modified demo here: https://jsfiddle.net/OlegKi/j28uoo44/8/

**Comment by OlegKi** [comment]
I committed [the changes](https://github.com/free-jqgrid/jqGrid/commit/a76362f894a6a4883c2367c5b0a9c4ecce69f353) to GitHub repository of free jqGrid. The problem, which you reported should be fixed now. Please test the latest code of free jqGrid and close the issue if you confirm that the problem is fixed now.

**Comment by kmoens** [comment]
I just tested it, and the issue is resolved.

For reference, I tested it with this version of the minified jqgrid:
https://github.com/free-jqgrid/jqGrid/commit/1d5099fa5582a22174ef0354f96acd48ade365f1
