### ISSUE TITLE
Custom Copy line button

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#321]
Hi Oleg, is possible to add a Custom Copy Line button(near Edit and Delete button in the Actions column) on each line and when button is clicked will copy all editable values(in my example https://jsfiddle.net/01th999n/12/ only name and address values) into a new inline row or will open the new record pop up and copy values there?

**Comment by OlegKi** [comment]
I recommend you to post common question to [stackowerflow](http://stackoverflow.com) and to use both "jqgrid" and "free-jqgrid" tags. The issues should be used mostly for reporting of bugs and suggestions for new features requests. The questions in stackowerflow will be better indexed and found by *other developers*, who uses jqGrid and free jqGrid.

The first two demos from the page https://free-jqgrid.github.io/examples/index.html shows how to add custom button to `formatter: "actions"` (or `template: "actions"`). See [the answer](http://stackoverflow.com/a/29735149/315935) for more details. The demo https://jsfiddle.net/OlegKi/rmsz529L/3/, created for [another answer](http://stackoverflow.com/a/42222717/315935), is another example of usage `actionsNavOptions` option. [The wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Enhancement-of-formatter:%22actions%22) describes the feature more details.

**Comment by OlegKi** [comment]
One more remark. You post multiple questions, which you the same code with many bugs. For example, look to `$('#')`, which is wrong selector, you use `$grid = $("#grid");` instead of `var $grid = $("#grid");`, the code calls undefined functions `ConfirmOnLineUpdate` and `showloadingIcon` an so on. I try to fix the bugs in my modifications of your code (see the answer of your first question), but you repeat posting of the same old buggy code. Please, be careful in the code, which you send.

**Comment by Ant02** [comment]
Sure Oleg thanks for your help and your suggestions
