### ISSUE TITLE
Inline edit, restore after server response

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#324]
Hi,
I'm using inline edit for adding, deleting and editing a row in my grid, and I'm using events such as saveRowValidation and aftersavefunc for my validations, both local and server-side.
The problem is that the ajax call returns an additional parameter to indicate if the save row has succeded,
What I'd like to do is: if the response is negative then restore the row as it was before the edit and keep it open in edit mode.

I can check this validation easily during the delete using afterSubmit() and returning false but I did not find an equivalent even for the inline edit
I'm using
 ```
 editurl: WSediturl},

 inlineEditing: {
                            restoreAfterError: true,
                            keys: true,
                            oneditfunc: function (rowid) {
                            ...
                            },
                            beforeSaveRow: function (o, rowid, editOrAdd) {
                           ... validations
                            },
                            serializeSaveData: function (data) {
                            ...
                                return JSON.stringify(...);
                            },
                            afterSubmit: function (response, postdata) {
                                if (response.responseJSON.d.status == "KO") {
                                    return [false, response.responseJSON.d.message];
                                }
                                return [true]; // allow to delete
                            },
                            saveRowValidation: function (options) {
                              ...
                            },
                            aftersavefunc: function (rowid, response) {
                              ...
                                if (response.responseJSON.d.status == "KO") {
                                    alert(response.responseJSON.d.message);
                              ....
                                }
                            },
                          
                            errorfunc: function (rowid, jqXHR, textStatus, errorThrow) {
                                ...
                            },
                        },
```

**Comment by OlegKi** [comment]
Hi!

You wrote "I'm using inline edit for adding, deleting and editing a row in my grid". First of all, it's important to understand that inline editing provides no deleting of rows. Delete buttons of `inlineNav` or `formatter: "actions"` uses **form editing for deleting**. Thus you should distinguish the options/callbacks for processing of error during inline editing and deleting the rows.

The main interface to the server is the following. jqGrid uses `jQuery.ajax` and it follows the processing of errors defined by jQuery. The main criteria or error is the HTTP status code of the server response. The server should return the information about the error message and other custom information about server side error (or server side validation error) in the body of the server response. The HTTP status of such response should be >=400 or >=500. Such error response will be not automatically processed based on the `Content-Type`, but just be interpreted as the common text data. Such responses will be automatically interpreted as errors and the editing row will be restored to initial data or to stay editing based on the value of `restoreAfterError` option of inline editing. On an error during deleting the row will be not removed from jqGrid and the corresponding error message will be displayed by jqGrid.

One can use additional callbacks for custom processing of server-side errors. Inline editing supports `errorfunc` which prototype looks like
```JavaScript
errorfunc: function (rowid, jqXHR, textStatus, null, options) {
    // it should process the server response, which you can get from jqXHR
    // and DISPLAYS the custom error message
}
```
See [the response](https://github.com/free-jqgrid/jqGrid/issues/317#issuecomment-293955563) for more details.
Only if the server side in not able to set HTTP status code, one can use `successfunc` callback to process the server response. The `successfunc` should return `[true]` in case of no error and `[false, "Error mesage decoded from the server response"]` in case of error. jqGrid will displays the corresponding error message:
```JavaScript
successfunc: function (jqXHR, rowid, options, editOrAdd, postData) {
    returns [false, "Error mesage decoded from the server response"];
}
```
Deleting is the part of form editing. It uses close, but still another interface. One can use `errorTextFormat` (which you can specify inside of `formEditing` option of jqGrid instead of `inlineEditing`), which return **string** (HTML fragment) with the error message. jqGrid displays the error message. The prototype is of the function is
```JavaScript
errorTextFormat: function (jqXHR) {
    return "Error mesage decoded from the server response";
}
```
In the same way, if the server can't set error HTTP status in the server response, one can define `afterSubmit` callback which can close meaning to `successfunc` of inline editing:
```JavaScript
afterSubmit: function (jqXHR, postData) {
    returns [false, "Error mesage decoded from the server response"];
}
```

**Comment by bolzo5** [comment]
Thank you,
that was exactly what I was looking for.
