### ISSUE TITLE
Request for getRowData fix in version 4.13.6x

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#326]
Is it possible to apply the fix for "getRowData when inline editing" in free-jqgrid version 4.13.6x ?

I mean, I know you applied that in version 4.14x, which fix the issue when getRowData returns the "inputs" instead of the real values of the cells.

If it's not possible, could you give me a "simple" solution to apply a patch by myself in my jquery.jqGrid.src.js ? (which is 4.13.6)

Thanks!

**Comment by OlegKi** [comment]
The feature "`getRowData` when inline editing" is implemented in 4.14.0. You can't just have new feature in the previous version. You can try to make the same (or close) changes in the old version, but you should do this yourself. MIT license of free jqGrid allows you to make your own fork and develop it independent from free jqGrid. On the other side, I don't recommend you to do this. Instead of that you should update 4.13.6 to 4.14.0 or to get the latest sources from GitHub. The sources includes [additional changes](https://github.com/free-jqgrid/jqGrid/commit/a76362f894a6a4883c2367c5b0a9c4ecce69f353), which could be important in case if you use `editable` property of `colModel`, defined as function.

The main rule of all free products: **only the latest version will be supported**. There are exist some exceptions, but only for projects, which get enough donations. Thus you should organize your development process so that you update open source components relatively frequently. For example, you use probably Google Chrome or Firefox. There are new version of the web browsers every 1.5-2 months and *only the latest version of web browser is supported*. Additionally one publishes minor versions with bug fixes more frequently.

I recommend you to migrate to the latest version of free jqGrid in short time after publishing of a new version. I suppose that you make some tests before. If you will find some bugs in the new version you should report it me and I'll fix the bugs (typically very quickly). It's the way, which I can recommend you. You can make developer instance of your web application, which loads jqGrid files directly from GitHub (`https://rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css` and `https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js`). You can verify from time to time, whether your application works correctly and report me any problems. In the way you can help me to find any bugs at the more early time.

**Comment by OlegKi** [comment]
It seems the question is cleared and I'm closing the issue. If you'll find some problems in the latest released version of free jqGrid or in the current code from GitHub, please post the information to me.

**Comment by aberel** [comment]
It's ok, thank you. Regards-
