### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by resistorsoftware** [free-jqgrid/jqGrid#327]
I changed the old styleUI to be guiStyle and set it to 'bootstrap4'. I have that as my default CSS. 

When I render the grid I get the old styles from ui.jqgrid.css 

Was wondering where I can find the ui.jqgrid.bootstrap4.css files that must be around somewhere?

**Comment by OlegKi** [comment]
You should post the demo, which reproduces the problem. The differences between `guiStyle: "bootstrap"` 
 and `guiStyle: "bootstrap4"` are in the JavaScript code and not in `ui.jqgrid.min.css` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/grid.base.js#L803-L893)). For example, one uses CSS class `card` in Bootstrap 4 instead of `panel-info` in Bootstrap 3.

**Comment by resistorsoftware** [comment]
it was bootstrap4, guess I missed the memo about what that actually looks like...
