### ISSUE TITLE
4.14.0 getCell gives undefind-alert in beforeEditCell, editmode if cellname same as editcell

### ISSUE THREAD

**Issue by PeterSandberg** [free-jqgrid/jqGrid#328]
Hello!
After upgrade to 4.14.0 i get an alertbox says 'undefined' when...

`
beforeEditCell: function (rowid, cellname, value, irow, icol) {

//Occurs here if 'cellname' is the same as the current cell in editmode)
var value = $grid.getCell(rowid, 'QTY'))

},
cellEdit: true,
`
Also occurs in afterSaveCell etc.
Can prevent it by adding code in the events. But wonder if it's a bug or it is by design?

Best regards
Peter Sandberg

**Comment by OlegKi** [comment]
Please, send **the demo, which can be used to reproduce the problem**, or at least more detailed JavaScript code (where the column `QTY` is defined). I suppose that you could have the same problem, which is fixed in [the commit](https://github.com/free-jqgrid/jqGrid/commit/a76362f894a6a4883c2367c5b0a9c4ecce69f353) (see [the issue](https://github.com/free-jqgrid/jqGrid/issues/315) for details). Thus please **test your demo with the latest code from GitHub**: you need just load free jqGrid files from `https://rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css` and `https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js`. If the bug still exist then I need be able to reproduce the code and to debug it. Thus I need to have the demo and the test case (step by step instruction, which can be used to reproduce the problem).

**Comment by OlegKi** [comment]
Do you tested whether the described problem exist with the latest sources of free jqGrid (see my previous post)? Please send me additional information or close the issue if the described problem is not exist more.

**Comment by PeterSandberg** [comment]
I am testing right now (sorry am late) ! Will return later tonight with the result!!

**Comment by PeterSandberg** [comment]
Can't get:           var qty = $grid.getCell(rowid, 'QTY');
to work in:          beforeEditCell: function(rowid, cellname, value, irow, icol)

See:  https://jsfiddle.net/2x8oddqx/65/

**Comment by OlegKi** [comment]
Thanks for the demo. I posted the small changes, which fixes the problem.

Nevertheless I'd recommend you don't use `getCell` or `getRowData` in case of using `datatype: "local"`. The method `getLocalRow` works much more effective:
```JavaScript
var qty = $(this).jqGrid("getLocalRow", rowid).QTY;
```
Even if your real application uses `datatype: "json"` without `loadonce: true`, the code
```JavaScript
var qty = 'QTY' === cellname ? value: $(this).jqGrid("getCell", rowid, 'QTY');
```
or
```JavaScript
var p = $(this).jqGrid("getGridParam");
var qty = p.colModel[icol].name === cellname ? value: $(this).jqGrid("getCell", rowid, 'QTY');
```
will be better as your original code. The above code works with 4.14.0. See https://jsfiddle.net/OlegKi/2x8oddqx/72/

**Comment by PeterSandberg** [comment]
Thanks!
