### ISSUE TITLE
functional editable property

### ISSUE THREAD

**Issue by cansinDurdu** [free-jqgrid/jqGrid#331]
Hello ,

First of all, i really appreciate your work. Bunch of thanx to you! You saved my life with your latest release.  I think i have a small issue. When i try inline edit a row firstly, i can get the column data  type(which is bool) correctly from if condition which i stated in below code . But on my second or another inline edit attempt the data type is converted to string type somehow. I couldn't understand/find the exact cause. Do you have any idea? Many thanks for your support
p.s.: I'm using version 4.14.0 js/css and jQueryUI is v1.12.1

```
editable: function (options) {
                        var item = $(this).jqGrid("getLocalRow", options.rowid);
                        if (item.IsApproved){
                            return false;
                         }
                        return true;
                    }
```

**Comment by OlegKi** [comment]
Please, send more JavaScript code, which you use or the demo, which could be used to reproduce the described problem. It's important to know how you define columns in `colModel`. It's unclear, which "data type" exactly you use in the input data and which you need to hold.

In general, I introduced some callbacks, which you could use. I described the features in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Editing-of-local-data). One can define `convertOnSave` callback in any column, which converts the results of editing. The callback will be called on any changing of data.

If you have the problem only with `boolean` field `IsApproved` than you can use `template: "booleanCheckbox"`, which defines the callback as you can see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/jquery.fmatter.js#L190-L201). The `template: "booleanCheckbox"` uses `stype: "checkbox"` (3-state checkbox) additionally, which is practical in the filter toolbar. If you don't need to display the boolean values as checkboxes, then you can create your own `convertOnSave` callback based on the code of `template: "booleanCheckbox"` (see above link) and to use the callback instead of column template. In the same way I'd recommend you to use `template: "number"` and `template: "integer"` (see the corresponding `convertOnSave` callbacks [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/jquery.fmatter.js#L181-L184) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/jquery.fmatter.js#L169-L172)).

I personally use templates permanently. You can look at [the demo](https://jsfiddle.net/OlegKi/yvbt6w54/1/), for example, which I included in the [README](https://github.com/free-jqgrid/jqGrid#new-main-features-implemented-in-the-version-4140-compared-with-4136) of the version 4.14.0.

**Comment by OlegKi** [comment]
Do you tried to use `convertOnSave` callback or the `template: "booleanCheckbox"`? Is the problem is solved or you still have opened questions? Don't forget to close the issue when the problem will be solved.

**Comment by cansinDurdu** [comment]
Heelo Oleg,

Sorry for my late reply. I've just red your answer. Actually i'm using jqGrid as an AngularJS directive in my application.  So please keep in mind this little info. Below you can find my code:

 ```
$scope.PpdmGridConfig = {
        id: "PpdmGrid",
        datatype: "local",
            colNames:
            [
                'Id', 'PPDM-Nb', 'Description', 'Cost Center', 'Date', 'PPDM-Duration in min -VT',
                'PPDM-Duration in min -Support', 'Approval Of CTG', "IsDirty"
            ],
            colModel:
            [
                { name: 'Id', index: 'Id', editable: false, width: 20, sorttype: "int" },
                { name: 'PpdmNo', index: 'PpdmNo', editable: ppdmGridEditableColumnCallbackFn, width: 90 },
                { name: 'AdjustmentDesc', index: 'AdjustmentDesc', editable: ppdmGridEditableColumnCallbackFn, width: 100 },
                { name: 'CcId', index: 'CcId', editable: ppdmGridEditableColumnCallbackFn, width: 80, align: "right" },
                {
                    name: 'TtTimeDate',
                    index: 'TtTimeDate',
                    editable: ppdmGridEditableColumnCallbackFn,
                    width: 80,
                    align: "right",
                    sorttype: "date",
                    formatter: "date",
                    formatoptions: { srcformat: 'd/m/Y', newformat: 'd/m/Y' }
                },
                {
                    name: 'SapHoursAdj',
                    index: 'SapHoursAdj',
                    editable: ppdmGridEditableColumnCallbackFn,
                    width: 80,
                    sorttype: "int",
                    sortable: true
                },
                {
                    name: 'ClockedHoursAdj',
                    index: 'ClockedHoursAdj',
                    editable: ppdmGridEditableColumnCallbackFn,
                    width: 80,
                    sortable: true,
                    sorttype: "int"
                }
                ,{
                    name: 'Approved',
                    edittype: 'select',
                    formatter: 'select',
                    editoptions: { value: "true:Yes;false:No" },
                    editable: function (options) {
                        var item = $(this).jqGrid("getLocalRow", options.rowid);
                        if ($scope.SelectedOperation.Id === 1)
                            return false;

                        return true;
                    }
                }
                ,{
                    name: 'IsDirty',
                    formatter: 'checkbox', edittype: 'checkbox', editable: false, hidden:true
                }
            ],
            multiselect: false
    };
```
So, i've just red your wiki article which explains convertOnSave callback. I've tried it and works perfectly for me. By the way IsApproved column should be in select format due to our business analysis requirements. So i have no any other question for you :) Thanks again for your help.

**Comment by OlegKi** [comment]
I'm glad to know that the problem is solved. You are welcome!
