### ISSUE TITLE
Date formatter returning incorrect date for PDT...

### ISSUE THREAD

**Issue by nvrnight** [free-jqgrid/jqGrid#343]
I seem to have run across this problem here using version 4.14.1 free jqGrid

https://stackoverflow.com/questions/7916881/jqgrid-formatting-date-returns-wrong-date

I replaced getDate() with getUTCDate() as one of the answers gave and it seems to work so going ahead and using it for my code, but would rather it get fixed so I don't have to maintain a different code base.

**Comment by OlegKi** [comment]
Sorry, but you should prepare **the demo, which demonstrates the problem, which you report**. If you claim, that free jqGrid 4.14.1 has a bug then you should post more information. Which options of `formatter: "date"` you use? Which format has the input data for the column (do you use `Z` symbol in the input data in case of usage ISO 8601 format)? Which locale you use? In which timezone is the client/server? For example, look at [the thread](https://github.com/free-jqgrid/jqGrid/issues/310), which describes the bug in `formatter: "date"`, which was fixed in free jqGrid 4.14.1.

**Comment by OlegKi** [comment]
Please, provide the demo, which demonstrate the problem. Posting a bug report without JavaScript code and test data provides practically no information.

**Comment by OlegKi** [comment]
Please, provide the demo, which demonstrates the problem, or close the issue.

**Comment by OlegKi** [comment]
@nvrnight:  I din't get any information from you since a long time. I'm closing the issue. You can still post the demo, which I asked you before and reopen the issue.
