### ISSUE TITLE
Incorrect sorting of pivot grid

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#344]
See following picture:
![image](https://user-images.githubusercontent.com/11850439/27286839-2608224c-5534-11e7-9bda-c689d4ecabef.png)

The xDimension configuration:

`
                    xDimension = [{
                        dataName: "学校名称"
                    }, {
                        dataName: "年份"
                    }];
`
the row with value 2016 should be below the row with value 2015.
The incorrect sorting only occurs in chrome. It works on IE, Firefox, and Edge, any hint?

**Comment by ryanlin1986** [comment]
Fixed the problem by comment out the following code:
					//if (!pivotOpt.skipSortByX) {
					//	for (i = 0; i < groupingView.groupField.length; i++) {
					//		query.orderBy(groupingView.groupField[i],
					//			gridOpt != null && gridOpt.groupingView && gridOpt.groupingView.groupOrder != null && gridOpt.groupingView.groupOrder[i] === "desc" ? "d" : "a",
					//			"text",
					//			"");
					//	}
					//}

Unnecessary to do sorting, in side pivot grid method,  because pivotSetup, the data is already sorted.

**Comment by OlegKi** [comment]
Please post always **the demo, which reproduce the problem**, which you report. It's important to know **the input data**, which you use and **the options of `jqPivot`**. Additionally you should describe the steps to reproduce the problem. You should always write, which version of free jqGrid you used in your tests. It's unclear, whether the picture, which you posted, is made directly after filling the data in `jqPivot` or after click on the header of the second column (`"年份"`).

If you need to skip initial sorting of data you can use `skipSortByX: true` option. You should use options of `jqPivot` instead of commenting some parts of the code of `jqPivot`. The usage `skipSortByX: true` option will prevent *initial* sorting, but not later sorting of the data. You could still have problems if the user force sorting by click on the column header. Thus it's recommended, that you use `jqPivot`, which inform jqGrid how to sort the input data correctly.

**Comment by ryanlin1986** [comment]
Thanks, skipSortByX works fine, thank you very much.
