### ISSUE TITLE
Data comes wrong when using "select" formatter, any ideas?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#350]
I am experimenting a weird issue which I can reproduce in jsFiddle. Maybe I am missing something here but I am not sure. In a brief:

If I don't use the `select` formatter:

```json
{
  "quote_detail.Multiplier": "0.6500",
  "quote_detail.quoted": "1",
}
```

And this is how the `colsFormat` look for such column in that case:

```json
{
    "name": "quote_detail.quoted",
    "width": 100,
    "fixed": false,
    "sortable": true,
    "resize": true,
    "formatter": "",
    "formatoptions": "",
    "index": "quote_detail.quoted",
    "align": "left",
    "hidden": false,
    "edittype": "",
    "classes": false,
    "editable": false,
    "label": "Quoted",
    "key": "",
    "autoResizable": true,
    "frozen": true,
    "resizable": true,
    "search": false,
    "hidedlg": false,
    "viewable": true
}
```

Here an example:
![screenshot-2017-06-2317-19-32](https://user-images.githubusercontent.com/627886/27500894-6603f6da-5838-11e7-9e34-d03a1a97bdaf.png)

If I use the `select` formatter:

```json
{
  "quote_detail.Multiplier": "0.6500",
  "quote_detail.quoted": "",
}
```
This is how the `colsFomat` look like in this case:

```json
{
    "name": "quote_detail.quoted",
    "width": 100,
    "fixed": false,
    "sortable": true,
    "resize": true,
    "formatter": "select",
    "formatoptions": "",
    "index": "quote_detail.quoted",
    "align": "left",
    "hidden": false,
    "edittype": "select",
    "editoptions": {"value": "1:TRUE;0:FALSE;", "defaultValue": "FALSE"},
    "classes": false,
    "editable": false,
    "label": "Quoted",
    "key": "",
    "autoResizable": true,
    "frozen": true,
    "resizable": true,
    "search": false,
    "hidedlg": false,
    "viewable": true
}
```

And here is an example with the grid not working (notice the undefined word on the column):

![screenshot-2017-06-2317-23-28](https://user-images.githubusercontent.com/627886/27500972-bf8b1f1c-5838-11e7-896e-286f09e129e2.png)

My first guess was the quotes on the `"value"` and  `"defaultValue"` but I tried [here](https://jsfiddle.net/reynierpm/1vnLnm6L/7/) and surprise it work with quotes and without them.

I have checked docs [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter#formatter_type_select) and the usage seems to be fine with the quotes exception.

Could any give me an idea in what could be happening here?

**Comment by OlegKi** [comment]
First of all, the value of `defaultValue` (in case of usage `"editoptions": {"value": "1:TRUE;0:FALSE;" },`) should be the `"0"` or `"1"` and not `"FALSE"`, which you use. See https://jsfiddle.net/OlegKi/1vnLnm6L/8/, which use "1", "0" und undefined values and it displays correctly.

Seconds your current model of the items of `colModel` is buggy. The value of `formatoptions` should be **object** and not string. Thus one should fix `"formatoptions": ""` to `"formatoptions": {}` for example. In the same way the property `key` is Boolean and you should fix `"key": ""` to `"key": false`. The value of `"classes"` property is string and you should fix `"classes": false` to `"classes": ""`. See `free-jqgrid.d.ts` for more information. For example, look at [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/ts/free-jqgrid.d.ts#L731) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/ts/free-jqgrid.d.ts#L758).

In general I'd recommend you don't serialize default values in `colModel` items and never set `index` if it's really required. Your example of column definition could be reduced to
```
{
    "name": "quote_detail.quoted",
    "width": 100,
    "formatter": "select",
    "edittype": "select",
    "editoptions": {"value": "1:TRUE;0:FALSE;", "defaultValue": "FALSE"},
    "label": "Quoted",
    "autoResizable": true,
    "frozen": true,
    "search": false
}
```
Many serializations allows to do it in the simple way. I personally use C# and JSON.net, which supports ` NullValueHandling = NullValueHandling.Ignore` property since a long time (see [here](http://james.newtonking.com/archive/2009/10/23/efficient-json-with-json-net-reducing-serialized-json-size)).

Additionally you can use `cmTemplate` and `template` property, which allows to reduce the size of column definition additionally. It simplifies maintains of the code essentially. One can define templates with some properties and use it in `colModel`. You can consider to use standard templates defined [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/jquery.fmatter.js#L162-L223). https://jsfiddle.net/OlegKi/su7ebs65/ is an example of using some templates. See `template: "booleanCheckbox"` and `template: "number"` used in the code of the demo. It's shortcuts of column properties defined [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/jquery.fmatter.js#L179-L203).

**Comment by reypm** [comment]
Perfect, closing this as fixed, many thanks
