### ISSUE TITLE
Why the datetime is not being formatted to the format I want to?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#352]
I am trying to format a date from `ISO8601Long` to my own format `m/d/Y H:i A` but for some reason isn't working for me. This is how I am doing it:

```json
{
      "name": "comments.created_at",
      "width": 100,
      "fixed": false,
      "sortable": true,
      "resize": true,
      "formatter": "date",
      "formatoptions": "{\"srcformat\":\"ISO8601Long\", \"newformat\":\"m\/d\/Y h:i A\"}",
      "index ": "comments.created_at",
      "align": "left",
      "hidden": false,
      "edittype": "",
      "classes": false,
      "editable": false,
      "label": "Created At",
      "key": "",
      "autoResizable": true,
      "frozen": true,
      "resizable": true,
      "search": false,
      "hidedlg": false,
      "viewable": true
}
```

But I am not seeing the `H:i A` on the column. Check [here](https://jsfiddle.net/reynierpm/1vnLnm6L/13/) for an example, what I am missing here?

**Comment by OlegKi** [comment]
The type of `formatoptions` property have to be **object** with properties `srcformat` and `newformat` and not **the string** with JSON encoded object. Thus you have to fix
```JavaScript
"formatoptions": "{\"srcformat\":\"ISO8601Long\", \"newformat\":\"m\/d\/Y h:i A\"}",
```
to
```JavaScript
"formatoptions": {"srcformat":"ISO8601Long", "newformat":"m\/d\/Y h:i A"},
```
See https://jsfiddle.net/OlegKi/1vnLnm6L/17/. I made some other minor changes in the demo: You use `pager: "grid1-gridpager"`, but the div `<div id="grid1-gridpager"></div>` is not defined. Free jqGrid allows you to use simplified form of `pager` parameter: `pager: true`, which is close to `toppager: true`. Methods `navGrid` and `navButtonAdd` allows to **skip** the pager parameter (`'#grid1-gridpager'`). It reduce the code and simplifies there maintenance. I added `iconSet: "fontAwesome"` to use vector-based Font Awesome icons instead of old jQuery UI icons.

**Comment by reypm** [comment]
Excellent, as usual many thx
