### ISSUE TITLE
Row gets selected using right-click, but beforeSelectRow doesn't get called.

### ISSUE THREAD

**Issue by zohanalexix** [free-jqgrid/jqGrid#356]
I am trying to make a grid with unselectable rows by returning false in the _beforeSelectRow_ method.
```JavaScript
beforeSelectRow: function(){
    return false;
}
```
Rows are not longer selectable when left clicking on them, but they get selected when I right click and `beforeSelectRow` doesn't get called.

[Demo](https://jsfiddle.net/zohalexix/vbw7qseL/)

**Comment by OlegKi** [comment]
Thank you for the bug report! The callback `beforeSelectRow` can be used for preventing selection on **click** on the row, but not in case of selection by usage of `setSelection` method. The callback `onRightClickRow` will be called if the user click on the right mouse button. I posted the fix just now, which allows to prevent selection in the case if one returns `false` from `onRightClickRow`:
```JavaScript
onRightClickRow: function () {
    return false;
},
beforeSelectRow: function () {
    return false;
}
```
Try the modified demo:
https://jsfiddle.net/OlegKi/vbw7qseL/5/

**Comment by zohanalexix** [comment]
Thank you for the quick response and the fix, but I believe it may cause confusion and other problems, as now the return value of _onRightClickRow_ will have two results: disable the context menu and the selection. What if I only want to disable one?

Since _setSelection_ is called from inside the _oncontextmenu_, shouldn't the _beforeSelectRow_ be called also in order to keep consistency with the left click? Or should we always have identical implementations for _beforeSelectRow_ and _onRightClickRow_ in order to assure that our users are experiencing the same features when selecting with right click by accident?

**Comment by OlegKi** [comment]
I think that there misunderstand the meaning of `beforeSelectRow` callback because of its name. The name has historical reason, but more correct name of the callback would be `onClickRow` (close to other callbacks like `ondblClickRow` and `onRightClickRow`). Thus I can repeat that calling of `beforeSelectRow` callback inside of `onRightClickRow` would be **absolutely wrong**. It could break existing code of many projects, which uses jqGrid.

I try to hold maximal compatibility to the old versions of jqGrid (in versions <=4.7). Thus I prefer to make changes in the code, which don't break the compatibility or at least to hold the option, which allows to simulate old behavior.

Some implementations of `onRightClickRow` supposes (directly or indirectly) that the currently clicked row is *selected* and `selrow` parameter is set to the rowid.

I reverted the previous changes and introduced new Boolean option `selectOnContextMenu`, which default value is `true`. The usage `selectOnContextMenu: false` will prevent selection of rows on right mouse click (on `contextmenu`). To be able to select the row conditionally one can do this inside of `onRightClickRow`. The callback could select the row, but still don't return `false` to prevent processing `oncontextmenu` event.

**Comment by zohanalexix** [comment]
Thank you for the clarification and the fix. This seems a much better approach.
