### ISSUE TITLE
[Bootstrap] Hover highlighting interferes with cell highlighting in cell editing mode

### ISSUE THREAD

**Issue by arrinmurr** [free-jqgrid/jqGrid#360]
When hovering over some grid row while cell editing mode is active, the highlighting of the active cell on that row is visible only if the active cell is the same you're hovering over. This only affects the Bootstrap theme, where there is a highlighting effect on hover.

Examples using code from the master branch:

* Bootstrap: https://jsfiddle.net/OlegKi/o8v2ybcp/1/ (issue exists)
* jQuery UI: https://jsfiddle.net/o8v2ybcp/2/ (no issue)

Steps to reproduce:

**Case 1**
1. Click on "abc1".
1. Move your mouse cursor over "def1" or "ghi1".
1. Notice that the cell highlighting of "abc1" is no longer visible even though that is still the active cell.

**Case 2**
1. Click on "abc1".
1. Keep your mouse cursor in place and move to "def1" or "ghi1" using keyboard navigation.
1. Notice that the cell highlighting of "def1" or "ghi1" is not visible even when one of them is the active cell.

**Comment by OlegKi** [comment]
Thank you for reporting the problem. It seems that the reason of the problem is the class `table-hover` used in the `guiStyle: "bootstrap"`. The CSS of Bootstrap contains CSS rules with `.table-hover > tbody > tr:hover ...`. Such rules are the origin of problem, which you reports.

One can create custom `guiStyle`, the the mostly simple way for me seems to remove the class directly after creating the grid. See https://jsfiddle.net/OlegKi/o8v2ybcp/4/, where I added `.removeClass("table-hover")`. Works the demo now like you expect?

**Comment by arrinmurr** [comment]
That certainly makes it work like it does with the jQuery UI theme, so it solves the problem in that sense. The hover highlighting is pretty useful though especially with large tables, so I was hoping to keep it. But if this issue can't be easily avoided when the hover highlighting is enabled, I will have to think about whether this is big enough of an issue to disable the hover highlighting.

In any case your solution makes it work exactly as it should, so I will close this. Thank you!
