### ISSUE TITLE
Zoom in

### ISSUE THREAD

**Issue by Yagg** [free-jqgrid/jqGrid#371]
On some mobile devices zoom **in** does not work currently in latest Chrome. I test it with a single example from documentation page (You can try at http://home.yagg.me/) with various devices and most have not worked zoom. Devices with Chrome 42 worked well but with Chrome 59+ does not.

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand the scenario, which you use. I suppose that the problem is related to the CSS properties
```css
.ui-jqgrid {
	-ms-touch-action: none;
	touch-action: none;
}
```
see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.15.0/css/ui.jqgrid.css#L12-L13) of `ui.jqgrid.css`. The reason of the setting was mostly preventing default double-tap-zoom on Windows Touch devices. I think that the setting `{ -ms-touch-action: none; }` would be enough for that (see [the article](https://blogs.msdn.microsoft.com/askie/2013/01/06/how-to-implement-the-ms-touch-action-none-property-to-disable-double-tap-zoom-on-windows-touch-devices/)). I recommend you to try to add
```css
.ui-jqgrid {
	touch-action: manipulation;
}
```
*after* the link with `ui.jqgrid.css`. Try [the demo](https://www.ok-soft-gmbh.com/jqGrid/OK/Zoom.html).

Additionally I'd recommend you to set the value `user-scalable` to `yes` explicitly in `<meta name="viewport" ...` (see [the specification](https://drafts.csswg.org/css-device-adapt/#viewport-meta)):
```html
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1">
```

**Comment by Yagg** [comment]
This style modification solved the problem. Thanks!
