### ISSUE TITLE
Can I fix the first column no matter what?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#375]
If I remove all the columns from the grid and then start adding them one by one the first column start moving to the right as image below show.

![8018_1](https://user-images.githubusercontent.com/627886/30694987-5de505fe-9ea4-11e7-82ea-58207ca0569d.JPG)

Any way to prevent this behavior?

**Comment by reypm** [comment]
Hi @OlegKi can you give me some help here?

**Comment by OlegKi** [comment]
It's a bug, but I have to do now my main job. I'll fix it later...

**Comment by OlegKi** [comment]
@reypm I posted changes to GitHub, which should fix the problem. It's difficult to debug and to test problems in `columnChooser` because of many possible options, the usage of old Multiselect plugin and different versions of jQuery UI. Please verify, whether the problem is fixed now in your tests and whether the last changes didn't break other parts of `columnChooser`.

**Comment by reypm** [comment]
@OlegKi do you want me to test from the master branch? if so should I use `src` or `dist`?

**Comment by OlegKi** [comment]
You can just use free jqGrid directly from GitHub. See every [README](https://github.com/free-jqgrid/jqGrid#free-fork-of-jqgrid):
```html
<link rel="stylesheet" href="https://rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css">
<script src="https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js"></script>
```
The files `jquery.jqgrid.src.js` is **the same** in `/js` or in `/dist` folders.

**Comment by reypm** [comment]
@OlegKi apparently the issue from here has been fixed but I am running into a similar issue like the one on #374

**Comment by OlegKi** [comment]
Sorry, but I don't understand your last comment. If the problem is fixed then you should **close** the corresponding issue (or both). If some problems still exist, then you should post the demo, which reproduces the problem, or to describe the existing problem detailed, so that I'll be able to reproduce it.

Are any problems still exist in the latest code of free jqGrid?

**Comment by reypm** [comment]
@OlegKi ok, the issue from here since to be fixed now.
