### ISSUE TITLE
jq selector missing context?

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#376]
In jqGrid 4.15.0 src, I found in the line 8439 this ...  

`if` ($("**_.ui-datepicker_**").is(":hidden")) { 

I think this selector miss the context, so may refer to ANY **_".ui-datepicker_**" in the page, not only the current grid. Am I wrong?

best regards.
Aberel

**Comment by OlegKi** [comment]
What problem exactly you see in the line of code? Some controls, like jQuery UI datepicker places DOM elements **on the root of the page** as the child of `<body>`. It's the only way to be sure that the pop-up menu with the datepicker will be over all other DOM elements. All datepickers share the same DOM element, which has id="ui-datepicker-div" and class "ui-datepicker". The parent of the element is `<body>`. The datepicker will be shown on focus of the corresponding input field. The position of the `#ui-datepicker-div.ui-datepicker` will be changed dynamically so that it will be displayed near the input with the focus. Only one datepicker will be displayed at the same time, at least if one don't use some exotic options.

Thus I don't see, *which context* could be used in the selector. Please, provide more exact description of the test case and the demo, which could be used to reproduce any real problem, which could exist.

**Comment by aberel** [comment]
Ok, I don't have any real problem, it was a theorical guess, I just supposed that multiple datepickers may be displayed at the same time, but if not as you said, so there's no any issue here, it was my error. 
Sorry for that, I close this issue.
Regards.
