### ISSUE TITLE
Img tag not shown in rows

### ISSUE THREAD

**Issue by antony84** [free-jqgrid/jqGrid#382]
Hi,
until some reviews ago i was able to display image tag <img> inside <a> tag in the rows, while now it shows the html code.

I have to change something now to display tag <a><img.../></a> inside the rows?

**Comment by OlegKi** [comment]
I suppose that you include HTML fragments inside of data instead of using custom formatters. Version 4.15.0 changes the default value `autoencode` property from `false` to `true` (see the README of the version 4.15.0 and search for "compatibility"). Adding the option `autoencode: false` should solve your problem. I still would suggest you to consider to use custom formatters in the future.

**Comment by antony84** [comment]
It works. Thanks.
I would use custom formatters, but i cannot find a good documentation for free-jqgrid.

**Comment by OlegKi** [comment]
@antony84 You don't answer me during the last 11 days. Do you read my last comment? Is the problem solved? Please post any response or close the issue if the question is already cleared.

**Comment by OlegKi** [comment]
I didn't get any response from use since a long time. I'm closing the issue now. You can post additional information about your problem and *reopen* the issue.
