### ISSUE TITLE
how to use onSelectRow wiht typescript ? any example code?

### ISSUE THREAD

**Issue by 19317362** [free-jqgrid/jqGrid#385]
I'm test freejqgrid with typescript. But I don't know how to implement a simple function.

here is the test code

`export  class jqgrid_base_opt implements FreeJqGrid.JqGridOptions {
        public somAttr: string;

        public constructor(gridAttr: string)
        {
            this.gridAttribute = gridAttr;
        }
        onSelectRow(this: FreeJqGrid.BodyTable, rowid: string,
            status: boolean,
            e: JQueryEventObject): void {
            console.log('onSelectRow ');
            if (rowid === null) {

            }
            else {
                **//how to get the this.gridAttribute ?**
            }
        }
    }`

**Comment by OlegKi** [comment]
I'm not sure that I understand what you want to implement.

What information you want to save in `gridAttr`? You try to define new class `jqgrid_base_opt`, which inherits `FreeJqGrid.JqGridOptions` instead of just creating the grid with some options. Thus you probably want to create **more then one grids** with the same options. You use `this.gridAttribute` inside of constructor, thus you probably want to **declare** string property `gridAttribute` in `jqgrid_base_opt` class (with something like `gridAttribute?: string;`). Then I suppose that you want to create jqGrid using `jqgrid_base_opt` instance as parameter instead of an instance of  `FreeJqGrid.JqGridOptions`. In other words, you will create the grid, which has **additional parameter** `gridAttribute` together with other standard parameters of jqGrid (like `colModel`, `datatype` and so on). If `gridAttribute` will be one more parameter (a custom parameter) of jqGrid then you will be able to access it as any other parameter of jqGrid. So the expression `$(this).jqGrid("getGridParam", "gridAttribute")`  or `$(this).jqGrid("getGridParam").gridAttribute` or just `this.p.gridAttribute` will be the value which you need. If you will don't get `gridAttribute` in the way, then I probably misunderstand what you do and what you want to implement. I'd ask you to provide more full demo, which demonstrates what you do: how you declare the class and how you use it creating jqGrid.

**Comment by 19317362** [comment]
@OlegKi Thanks for your detailed reply. 
First, sorry for my poor English. 
Really, my gridAttribute is an object. Use string just for a demo.
The reason I want to do like this is : I'm trying to find a way with less coding to work with JQGRID.
I use jqgrid with C# backend.  A few years before, I begin to use jqgrid. Limited by my knownlegement, most code of the  grids are hand coded. A lot's JS code , C# code.

That makes the project hard to modify. If I need to  add a field, I must modify servel places:
the JS code, the data action, the add,edit,export  etc...

What I'm trying is like this:
1.  ORM: Entity Framework + Code First + Migration
    Thus, I can easily deal with the DB related things.
 
2. VM (ViewModel) 
   Use code to dynamic generate JQGRID options (mainly colModel)

    [Grid(  //define GRID related options
        cmTemplete = "sortable:true,editable: false,search:true"
        , caption = "Hello JQGRID"
        , frozenCnt = 3
        , autoSearch = false
        , search = true
        , sortname = "ModifyAt"
        , sortorder = "desc"
        )]
    public class VMHello
    {
        [Key]
        [GridColumn(Visible = false  //define colModel related options
            )]
        public long Id { get; set; }

        [GridColumn()]
        public string Value { get; set; }



        [GridColumn(Searchable = true
            )]
        public DateTime? ModifyAt { get; set; }

	}	

In this way, modifications (like add field, remove field, re-arrange the order,get data,export) with be easy: just modify the ORM and VM.

The main problem is : it's TOO difficult to fullfill   the GridAttribute and the GridColumnAttribute according to JQGRID one by one. Mainly ,the function callbacks.

I  mainly generate the colModel options dynamicly. I want define other options in TS. 
Mainly   callbacks like onSelectRow,beforeSubmit,afterSubmit etc.  These function will be different grid by grid.  So I want use different TS class to deal with it in the OO way.

var theOptionsGeneratedFromVM_A = { ... } //JS code generated in CS code dynamicly
var tsOption_A = new  jqgrid_opt_A (otherGridAttrA)
jqg_init(divA,theOptionsGeneratedFromVM_A ,tsOption_A );

var theOptionsGeneratedFromVM_B
var tsOption_B = new  jqgrid_opt_B (otherGridAttrB)
jqg_init(divB,theOptionsGeneratedFromVM_B ,tsOption_B );

//ts code
function jqg_init(div: JQuery
    , options: FreeJqGrid.JqGridOptions //theOptionsGeneratedFromVM* 
    , myopt: jqgrid_base_opt //come from TS class jqgrid_opt_A ,jqgrid_opt_B etc, grid by grid
    
    ): void 
{

    $.extend(true, options, myopt); //merge the two option: CS + TS
    let grid: FreeJqGrid.JQueryJqGrid = div.jqGrid(options);//init
}

The code works fine. Thanks for your great work.

Then, in the TS callbacks, "this" is not  jqgrid_base_opt.

I'm not master with JS and TS. Maybe I'm on the wrong way.

Maybe I can deal with this as your suguestion: $(this).jqGrid("getGridParam").gridAttribute or just this.p.gridAttribute 

I want to find some way like the following, but failed.

In TS code
class SomeTsClass
{
     private propertyOfTsClass : any
     private innerFunction(e:any)
    {
       this.propertyOfTsClass  ...
    }
     someFunction()
     {
          var someDiv = $("#someId");
          someDiv.on('click', ".menu_tab",
                 e => {
                    e.stopPropagation(); 
                    this.innerFunction(e);
                });

     }
}

It's just an idea for less coding, less error making.  
As you know, a middle web system may need more than 100 tables, more than 200 View Models => Grids. 

I hope I answered what you want to know.

I referenced some idea and code from the following link
https://github.com/aiska/Jq.Grid

**Comment by 19317362** [comment]
@OlegKi I've tried use data to deal with this:

....
$.extend(true, options, myopt); //merge the two option: CS + TS
let grid: FreeJqGrid.JQueryJqGrid = div.jqGrid(options);//init
div.data("myattr",gridAttr);

then, in the onSelectRow

let myattr = div.data('myattr');

It works. :)

**Comment by OlegKi** [comment]
You don't close the issue. Thus I suppose that your problem is still unsolved.

I am still not sure that I can full follow you. There are really many alternative ways to implement your requirements. To recommend you one way I need more understand what you really need. It would be very helpful if you create working code, which demonstrates what you really need. The code with `gridAttr`, `options`, `myopt` hide details, which could be very important. 

To make the code of grids short and easy to maintain one can extend for example `$.jgrid.defaults` object to change the defaults of jqGrid options. Another good way is the usage of column templates, which could essentially simplify `colModel`. One more important way would be the usage of jQuery events instead of usage callbacks. For example, if you define `onSelectRow` callback on the base class then the same callback `onSelectRow` overwrite the base class. On the other side you can bind **multiple** `jqGridSelectRow` events (with respect of `jQuery.on` or `jQuery.bind` method). It allows to define one event handler, which will be applied for multiple grids on the same page.

By the way, the usage of `$.extend` is one way to make a copy of object, but `$.extend` *modifies* the first non-boolean parameter. To prevent modification one uses typically an empty object `{}` as the second parameter of `$.extend`:
```
let grid: FreeJqGrid.JQueryJqGrid = div.jqGrid($.extend(true, {}, options, myopt));
```
I'm not sure why you need to save some additional information (`gridAttr`) with respect of `data`. The list of parameters of jqGrid is **extensible**. You can use 
```
let grid: FreeJqGrid.JQueryJqGrid = div.jqGrid($.extend(true, {my: gridAttr}, options, myopt));
```
for example and to get `my` parameter at any time later.

Finally I want to repeat that having **realistic example** is really important to understand what you need to implement and which way would be the best. As an example I want to tell you some real problem from my experience with jqGrid. One day I analyzed the code of jqGrid to improve the performance. I used large data array to be able better to measure the time. I used developer tools to measure which parts of the code took the most time. I was very wonder after I could see that the line `$.extend(true, {}, ...` used to expand parameter of jqGrid took more time as all other steps of creating the grid. The problem was that `$.extend` used for deep copy of array works *very slowly*. Mostly one don't need to clone `data` parameter, which could be really large. Small modification of the code (see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.15.1/js/grid.base.js#L2729-L2732), [this one](https://github.com/free-jqgrid/jqGrid/blob/v4.15.1/js/grid.base.js#L2749) and [another one](https://github.com/free-jqgrid/jqGrid/blob/v4.15.1/js/grid.base.js#L3015-L3018)) improved the total performance essentially. It shows that one could the solution of the same problem could be good or bad depend on the many other subjects. I don't want to say you some preferences without knowing enough details.

**Comment by 19317362** [comment]
@OlegKi Can you read C# code ? If you can , I can make a sample code project in github.

I'll test jQuery.on / jQuery.bind and the issue you pointed about $.extend.

I'm not master on JQuery/JQGrid and JS.   I only know pieces of things on these.  I can only use JS/JQuery/JQGrid.  

I'm familare with C/C++.  On the begining of seeing your free-jqgrid.d.ts, I want to treat the callback function like the C++ OO patten. 

The things I thinked is like this (let's throw away the gridAttr, it's a little case):
 namespace WPS { 
    export  class jqgrid_base_opt implements FreeJqGrid.JqGridOptions {
         public constructor()
        {
            this.gridAttribute = gridAttr;
        }
        onSelectRow(...): void 
       {
               //here, I'll do some common works for all my grid. 
       ｝
｝//end of class
 
    export  class jqgrid_opt_a extends jqgrid_base_opt  {// this is a sub-class
         public constructor()
        {
            super();
        }
        onSelectRow(...): void 
       {
               //here, I'll first call onSelectRow of jqgrid_base_opt  
               super.onSelectRow(...);
               //then, do the work special for jqgrid_opt_a 
               this.someFunction();//
               ......
       ｝
        private someFunction()
        {
        }
｝//end of class
  
}//end of namespace

This is very common for C++/C#/JAVA.  

Then, I start to try and I find it's not as I images:
onSelectRow(this: FreeJqGrid.BodyTable ...):
The "this" is not that "this".  Call to base class and call to class member can not be used.

Maybe, I'm totally wrong.
Sure, we can deal with the things in other ways.  

Thank you very much for the very detailed answer. I'm very sorry for wasting your time.

**Comment by 19317362** [comment]
@OlegKi I'll close this question.  I don't want wasting your time.  
If you will and have the time, I can make a sample project on github to show you what I'm trying to test.
As I say at the begining: I just want to make a framework for less code, easy modifcation, with C# + TS + JS + JQGRID.
