### ISSUE TITLE
Grid recreation with multiselect

### ISSUE THREAD

**Issue by Blipz** [free-jqgrid/jqGrid#386]
Hi Oleg,

I encountered a strange behavior while trying to recreate a grid from the parameters previously saved with the "getGridParam" method.

When the multiselect plugin is used, each time a grid is recreated a new column with checkboxes appears. Forcing _multiselect_ to false when reimporting the parameters does not work either, because the JS events are not handled.

Please see the [sample](https://jsfiddle.net/quecbng6/).

Is it the expected behavior? Should I use another method to save/load the parameters?

Thank you in advance!

**Comment by OlegKi** [comment]
Hi!

I would not recommend you to use jqGrid parameters to use there in other grid. The problem is that parameters object will be **changed** during creating the grid and during later working with the grid. The problem which you could see on your demo can be explained because `colModel` and `colNames` properties of internal object with parameters will be *changed* (extended) if one from three following option are used:
```
rownumbers: true,  // create "rn" column
multiselect: true, // create "cb" column
subGrid: true,     // create "subgrid" column
```
The simplest fix could looks like following https://jsfiddle.net/quecbng6/1/, but I would not recommend you to use the code, because changes of internal parameter will be more deep.

It would be safe the code, which create *deep copy* of the original object with parameter. I mean the usage of the code like
```JavaScript
var params1 = $.extend(true, {}, params),
    params2 = $.extend(true, {}, params);
```
which creates objects `params1` and `params2`, which are *independent* (contains no references to the same shared object). On the other side the content of all `params`, `params1` and `params2` objects is the same, at least at the beginning of creating the grid.

The demo https://jsfiddle.net/quecbng6/2/ demonstrates the recommended approach.

**Comment by OlegKi** [comment]
One more important thing, which you should take in consideration is the problem with **unique** ids of the rows of grids. To fix the problem you should use `idPrefix` with **unique** value on every grid on the page. See https://jsfiddle.net/quecbng6/3/ an one more demo. If you need to *generate* the unique id prefix then you could use `$.jgrid.randId()` function. See https://jsfiddle.net/quecbng6/4/

**Comment by Blipz** [comment]
Yes, but my point was more about reusing the current `colModel` of the grid (because it may have been changed with the columnChooser), not its original `colModel`.

I mean, you create the grid with `colModel` as a 2-element array, but `.jqGrid("getGridParam", "colModel")` returns a 3-element array because of multiselect (or more because of subgrid, rownumbers, and so forth).

Maybe [this](https://jsfiddle.net/quecbng6/5/) could work. Or better, use the `hidedlg` key to filter out the dynamically added columns, like used in columnChooser.

**Comment by OlegKi** [comment]
I can only repeat that I **don't recommend** you to get the state of `colModel` and other options *after* the grid is created and to use it as input parameter for other grids. `colModel` will be *modified* in many places of the code of jqGrid. One can make simple examples, like your last demo, working, but one can get a lot of other problems if you would use other features and options of jqGrid.

Just one more example. jqGrid support pagers. One can use `toppager: true`, `pager: true` or `pager: "#idOfPagerDiv"`. The *input* option `toppager: true` will be **modified** during creating the grid. jqGrid create new `<div>`, it assigns unique id value for the div and it sets the id selector of the div as the value of `toppager`. Thus one will have something like `toppager: "#jqg2"` instead of `toppager: true` after the grid was crated. The usage of `toppager: "#jqg2"` for another grid on the page would be wrong.

Thus I suggest you to work with copies of *original options* of jqGrid. The problems like the information, which columns become hidden and the new order of columns could be easy solved in another way. Look at [the answer](https://stackoverflow.com/a/31663268/315935), which demonstrates the usage of ideas from [the old answer](https://stackoverflow.com/a/8436273/315935) for free jqGrid.

**Comment by Blipz** [comment]
OK thank you for your time, it's all clear now.
