### ISSUE TITLE
delete rows with key that contains comma

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#388]
Is there an easy way to tell the delGridRow method to use a different delimiter other than a comma? I have primary keys that contain commas so the delGridRow methods break down.

I'm not sure what the best answer to this would be:
1.  ability to set a different delimiter?
2.  ability to quote keys?
3.  ability to submit as array instead of comma separated list?

It looks like the with the serialize_del_data method the postdata is already comma separated .. Any ideas?

**Comment by OlegKi** [comment]
It's good suggestion! I made some changes in the source code (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/425a03f59607e52718106304f48acee11bd5aaae)). One can use now for example
```JavaScript
formDeleting: {
    idSeparator: ";"
}
```
to use semicolon instead of comma as the separator of ids sent to the server during deleting. Additionally I added arrays of rowids as parameter of many callbacks, inclusive `serializeDelData` callback. Please read the comment of [the commit](https://github.com/free-jqgrid/jqGrid/commit/425a03f59607e52718106304f48acee11bd5aaae). As I described in the comment, the array of rowids contains the ids with `idPrefix`, if you use the option in jqGrid.

**Comment by Gazoo** [comment]
Many thanks Oleg!

**Comment by OlegKi** [comment]
You are welcome! Please, close the issue after testing the latest code of free jqGrid from GitHub.

**Comment by Gazoo** [comment]
Tested and working for me :)
