### ISSUE TITLE
autosuggest gets cut off

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#398]
UI elements like auto suggest are getting cut off in the advanced search dialog. At first I thought that this was just a z-index issue but it looks like the jqgrid is setting overflow to hidden:

```
.ui-jqdialog.ui-widget {
    overflow: hidden;
}
```

I can fix this if I override:
```
#searchmodfbox_grid.ui-jqdialog.ui-widget { 
overflow: visible;
} 
```

Do you see this causing any other problems? Is there a reason that this was set to overflow: hidden; ?
![bug](https://user-images.githubusercontent.com/379016/33219021-5d55d0e2-d0fd-11e7-8efa-8eb8bfe31a55.gif)

**Comment by OlegKi** [comment]
Sorry, but it's difficult to help you having so few information. Please post always, which version of free jqGrid you use and post the demo, which reproduces the problem or at lease JavaScript code. You write about "autosuggest" without any details. It's important that the parent of the menu used for autocomplete/autosuggest would be `<body>` and not the dialog window for example. Thus *the implementation* of autocomplete/autosuggest is extremely important.

For example, the demo https://jsfiddle.net/OlegKi/yvbt6w54/ from the [README4.14.0.md](https://jsfiddle.net/OlegKi/yvbt6w54/ from https://github.com/free-jqgrid/jqGrid/blob/master/README4.14.0.md) uses jQuery UI Autocomplete and has small problem in the Advanced Searching Dialog in Client column. The problem can be easy fixed by adding
```css
.ui-front.ui-autocomplete {
    z-index: 1000;
}
```
see https://jsfiddle.net/yvbt6w54/41/. Another demo https://jsfiddle.net/OlegKi/su7ebs65/ from [README4.14.1.md](https://github.com/free-jqgrid/jqGrid/blob/master/README4.14.1.md) demonstrates the option `generateDatalist: true` and has no autosuggest problems.

I recommend you to review your code which uses autocomplete/autosuggest or post me more details about your current implementation.

**Comment by Gazoo** [comment]
Sorry for the delay. For some reason your demos don't have the same issue I'm experiencing (using the latest version). I've tried to see what would be causing this but can't figure it out. I'm just going to use the css override which seems to fix it for me. Thanks!
