### ISSUE TITLE
Install NuGet package to ASP.NET MVC Core application

### ISSUE THREAD

**Issue by askrinnik** [free-jqgrid/jqGrid#402]
Hi Oleg,

I created a new ASP.NET MVC Core application in VS 2017
Then I open NuGet package manager and tried to install free-jqGrid package.
Output log shows that 
Successfully installed 'free-jqGrid 4.15.2' to WebApplication3
But I didn't find installed files in my project

The same steps on ASP.NET MVC5 application works good. I see some files in Scripts\free-jqGrid and Content folders

Could you please help to fix the issue?

Thank you in advance

**Comment by catbadger** [comment]
Why not just use .NET's data grid?

**Comment by OlegKi** [comment]
@askrinnik Hi Alexander,

the reason is very easy. Microsoft changed the goal of NuGet packages in ASP.NET Core. It uses NuGet packages **only in the server side code**. To be able to use npm or bower packages on the client side. Free jqGrid provide client functionality. Thus you have to use [npm](https://www.npmjs.com/package/free-jqgrid) package of free jqGrid or [bower](https://bower.io/search/?q=free-jqgrid) package. The usage of bower is the mostly easy, but I'd recommend you to use npm in combination with grunt or glup, which copy *selected* files of free jqGrid (only the files, which you use on your web site) into `wwwroot` folder.

**Comment by askrinnik** [comment]
Hi @OlegKi 
Thank you for your detailed answer and provided links.
Actually it is my fault. I didn't read readme.md. :(

Best wishes
