### ISSUE TITLE
two Ids in form data on submit.

### ISSUE THREAD

**Issue by X-BiLe** [free-jqgrid/jqGrid#418]
i have a simple grid using form editing and in the column definitions i have a "Id" key field.  when the edit url receives the request, the form data has two Ids?  is it possible to exclude the default "id" and just keep my "Id" column?

stepping through the code i see the additional key "id" is getting added at line 13098.

**Comment by OlegKi** [comment]
Please, describe the problems, which you report, more detailed. First of all include the **version** of free jqGrid, which you use, which CSS framework you use (jQuery, Bootstrap, Bootstrap 4).

You should post the demo (in JSFiddle, for example), which reproduces the problem. It's very important to know `datatype`, the existence of local data (`datatype: "local"` or `loadonce: true`), the format of input data, `colModel` and so on. Do you have `Id` or `id` in the input data? Do you define the corresponding column in `colModel`? Is the column editable? Do you use `prmNames`, `jsonReader` (or `xmlReader`, `localReader`), ... I can continue to guess what you do.

Thus, please provide the demo with description of the test case, which reproduces the problem or at least post the JavaScript code with an example of test data.

**Comment by X-BiLe** [comment]
i threw an [example](http://techni-kro.com/Test/) out onto one of my servers to simulate as closely to the real situation.  i have the post response returning the actual form data.

the form data looks like: "Id=3&Id=3&Name=Brandon&oper=edit"
the post data ends up with an "Id" and an "id" column on the previously mentioned line.

Thank you for your time Oleg!

**Comment by OlegKi** [comment]
I asked you about **the version** of free jqGrid, which you use. Did you examined it? You use currently free jqGrid 4.14.1, but the current version is 4.15.2 (probably I'll publish 4.15.3 today). I'd recommend you to use always the latest version.

Your code allows **to edit Id column**. It's very bad idea to do that in the most cases. Editing of ids isn't allowed in databases in the most cases. To edit id in SQL Server, for example, one have to set `SET IDENTITY_INSERT YourTable ON` on the table before editing and change the setting back with `SET IDENTITY_INSERT YourTable OFF`. In any way one needs to know **old id** to find existing record in the table and **new id** to set new value. jqGrid will use `idOld` and `id` properties for old and new ids by default, but one can change the name using `prmNames` option (for example `prmNames: { id: "Id", idold: "IdOld" }`). Nevertheless, sometime (but I think not in your case) it's really required. Because of that I implemented the editing of id, but only in *inline editing* mode and not in *form editing* mode which you use. You can, for example, add the column, which use `formatter: "action"` (by adding the column `{ name: "act", template: "actions" }` to the column model).

The problem with the usage of properties, which starts with low-case letter in JavaScript and upper-case in C# (like `"Id"` and `"id"`) is well known. It can be fixed in different ways. I personally use ASP.NET MVC too and I prefer to use JSON option `ContractResolver = new CamelCasePropertyNamesContractResolver()` in my server code to force `Newtonsoft.Json` to change the case of the properties to low-case **automatically** during JSON serialization of objects. If you use ASP.NET WebApi then you can place in `WebApiConfig.cs` or in `Application_Start` the lines like
```cs
var settings = GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings;
settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
```
(see [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/json-and-xml-serialization#camel-casing) for example). If you don't use WebApi then you can use `ContentResult` in your Controller Action. See [the answer](https://stackoverflow.com/a/22483122/315935) and [this one](http://www.matskarlsson.se/blog/serialize-net-objects-as-camelcase-json).

Alternatively one can use the option `prmNames: { id: "Id" }` to inform jqGrid to use `Id` instead if `id`.

I'd recommend you additionally to consider to use `loadonce: true, forceClientSorting: true` options and to return **array of all data** during filling the grid. Implementing *server side* paging, sorting and filtering is much more complex, but the current web browsers are quickly enough for local (client side) paging of 1000 or 10000 rows. Try the performance of local paging, sorting and filtering on [the demo](https://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-5000-25-free-jqgrid.htm) for example with 5000 rows. The usage of smaller `rowNum` allows to improve the performance additionally. See [the demo](https://www.ok-soft-gmbh.com/jqGrid/OK/performane-15-60000-25-free-jqgrid.htm) which uses 60000 rows.

One more advice. I'd strictly recommended you to include CSS of [Font Awesome](https://fontawesome.com/v4.7.0/) and to add the option `iconSet: "fontAwesome"`. See [the wiki article](https://free-jqgrid.github.io/getting-started/index.html#type_of_data)

**Comment by X-BiLe** [comment]
The sample is a bare minimum example to recreate the issue, we do use font-awesome in our actual implementation.  The issue is indeed a mistake on our part, the Id column is not supposed to be editable, a setting missed when moving to use the cmTemplate.  

The ability to update the libs consistently has not been an option until i managed to upgrade from jqGrid 4.6 a few months ago.  i will get our internal copy up to most recent.

Thanks again for pointing out the issue Oleg, always a pleasure!

PS: our DBA team wanted paging, filtering and sorting done in the DB as it is "optimized" to do so.  We pushed the grid queries into linq expressions and we have also built custom model binders for all interactions.  interesting implementation at least, i will see about getting an example out to get your opinion.

**Comment by OlegKi** [comment]
I'm glad that I could help you.

One remark about the usage of server side paging, filtering and sorting. I'd recommend you **to measure** the performance of `loadonce: true` scenario with server-side implementation. There are typical misunderstanding (especially from DBA team). The grid exist **on the client side**. Sorting request should be send via Ajax request to the Web server, the web server should dispatch the request (one from multiple users) to the database server, get the response, return to the client. Depend on whether you supports **only intranet client** and depend on many other features (especially round trip times), the client side sorting can be much quickly *from the users point of view*. Let's try [the demo](https://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-5000-25-free-jqgrid.htm) with 5000 items, which could be sorted, paged and filtered **locally**. On my computer sorting takes about 50-60 ms and filtering about 70-150ms. It could be less time as the time of communication with the server even if your database server provides the results for less then 1ms. By the way, the local performance will be even better as in the demo if you have less as 5000 rows in the grid.

Thus I recommend everyone **to test (to measure) the performance** of the solution in `loadonce: true` scenario always even you have already have implemented server-side paging. Sometime one have long RTT, sometime the web server could process the requests not so quickly and so on. The tests with `loadonce: true` can be made very quickly and you will know the best choice for your solution.
