### ISSUE TITLE
col model defaultValue issue

### ISSUE THREAD

**Issue by uklimaschewski** [free-jqgrid/jqGrid#419]
Hello Oleg,

when we set a defaultValue in the colModel and trigger the search using triggerToolbar(), the default search value is shown in the toolbar and is correctly transferred to the server.
However, when the user clears the search value to empty and presses enter, the old default value reappears in the toolbar. (Though the search now correctly has no search value).
When the user just changes the value, e.g. deletes only a few characters, everything works as expected.

**Comment by OlegKi** [comment]
Hi Udo,

I'm not sure that I correctly understand the problem. To tell the trust, it's very seldom needed to use `defaultValue` during searching at all. If one do use `defaultValue`, then the empty value and the `defaultValue` will be interpreted as *the same*. Do the search produced in your test case produce wrong search results or your issue is only about the look of the filter toolbar?

Could you post **the demo** (in jsfiddle, for example) and detailed description of the test case, which can be used to reproduce the problem. There are different ways how one can to set `defaultValue`, the problem can exist only with some specific types of data, it's not full clear for me, what you mean under "the old default value" and so on. In any way, please write always the version of free jqGrid, which you use in your tests. The demo answers on all above questions and many other, which I didn't wrote.

**Comment by uklimaschewski** [comment]
Here's a [fiddle](https://jsfiddle.net/yzyj77ay/8/):
If you clear the "And" in the Toolbar and press enter, the search is applied.
But the "And" immediately comes back and is shown in the Toolbar, though the list is not filtered.
The next enter key will then again filter against "And".
If you only remove the last letter, "An" stays there as expected.
In short: You can change the filter value, if there is a default, but you can't remove a default filter from the display.

**Comment by OlegKi** [comment]
Thank you for the demo. Could you describe more exactly which behavior you try to implement? **What behavior you expect in the demo?** I personally never use default values in searching. I hold the existing behavior like it be in jqGrid 4.7, but I personally find it a little annoying or misunderstanding. 

Your demo contains the line `$grid.get(0).triggerToolbar();`, which bring even more misunderstanding. I suppose that you want to *apply* the filter '`name` begin with"And"'. In the case you can add
```JavaScript
search: true,
postData: {
    filters: JSON.stringify({
        groupOp: "AND",
        rules: [
            { field:"name", op:"bw", data: "And" }
        ]
    })
}
```
`loadFilterDefaults: true` is the default option of `filterToolbar`. If some filter are applied in the grid the the filter toolbar loads it in the filter toolbar as far as possible. Thus the demo https://jsfiddle.net/yzyj77ay/19/ do exactly the same what you previous demo, but I changed the `defaultValue` to `defaultValue: "Andy"` to be able to see the difference between the data loaded because of applying the filter and the `defaultValue` of `searchoptions`. For example, the next demo https://jsfiddle.net/yzyj77ay/22/ uses `loadFilterDefaults: false` option and displays default value `Andy` even because the filter applied to the grid contains `data: "And"`.

I wrote, that I'm not sure which behavior you try to implement in the demo. Look at one more demo https://jsfiddle.net/yzyj77ay/24/, where **removed**  `defaultValue` from `searchoptions` und uses only `search: true` with `postData.filters`. It's more close to what I use personally. If you load the data from the server using `datatype: "json", loadonce: true` then you should add `forceClientSorting: true` option additionally. It force applying **local** sorting and filtering *before* displaying the first page of data. Is it probably what you need to implement?

**Comment by uklimaschewski** [comment]
Thanks Oleg, using `postData.filters` and `search: true` is the better way to start a grid with initial search values. This works better than using the `defaultValue` property.
I'll close this issue here.
