### ISSUE TITLE
Bug in addXMLData for IE8

### ISSUE THREAD

**Issue by ctrl11** [free-jqgrid/jqGrid#42]
I ran into an error in the following line of the file jquery.jqgrid.src.js while working in IE8:

$tbody.html($tbody.html() + rowData.join('')); // append to innerHTML of tbody which contains the first row (.jqgfirstrow)

I get a message that says "Function expected" in IE when I reach this line.  It seems to me that the problem is that the code tries to change the value of $tbody.html and return the value of $tbody.html at the same time.  I replaced that one line of code with the following two lines of code and it worked for me (again in IE8):

var temp = $tbody.html().concat( rowData.join('') );
$tbody.html(temp);

Thank you for continuing work on a free version of this plugin.

**Comment by OlegKi** [comment]
Thank you for your feedback!
Could you provides the demo which reproduces the problem? Do you use `datatype: "xml"` or `datatype: "xmlstring"`? If you have problems with providing the demo then could you at least do the following:
1) Verify that you use `<meta http-equiv="X-UA-Compatible" content="IE=edge">` at the beginning of the `<head>`. One will be then sure that IE8 works like IE8 and not in compatibility mode to more old wed browser.
2) Could you change the line
````JavaScript
$tbody.html($tbody.html() + rowData.join(''));
````
to
````JavaScript
var s1 = $tbody.html();
var s2 = rowData.join('');
var s3 = s1 + s2;
$tbody.html(s3);
````
In which line of code you get the message "Function expected"? The changes which you suggest just changes `s1 + s2` to `s1.concat(s2)`, but the existing code of jqGrid contains a lot of other places where one use `+` to concatenate the strings. What is different in the line of code (`$tbody.html($tbody.html() + rowData.join(''));`)? Do you have very large data? Do you use some other (probably old one) version of jQuery which have some side effects with `$tbody.html()`? I have no idea.

I' m ready to make any changes in the code of free jqGrid, but **I want good understand the existing problem**. I made one more test in IE8 with loading of XML data, but could not reproduce any problem. You can try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/xml.htm) and to debug the code near the line 2551: `$tbody.html($tbody.html() + rowData.join(''));`. I get no error in IE8. How the demo works in your test environment? Could you provide another demo which reproduce the error which you describe?

Best regards
Oleg

**Comment by ctrl11** [comment]
I am using datatype 'xml.'
I do not get an error in IE8 when using my test data (two records), but I do get an error on the line

var s2 = rowData.join('');

when I use my real data.  In my real data, rowData's length is 55946. I do not have test data yet, but I will work on producing that for you.  Now the error that shows up in the IE8 console is "Out of memory" on the line var s2 = rowData.join('');

**Comment by ctrl11** [comment]
Here are the files that you can use with IE8 to recreate this issue.
[jqgrid_bug_42.html | uploaded via ZenHub](https://files.zenhub.io/5522b7bd4462991f6ae773db)

[jqgrid_bug_42_small_data.xml | uploaded via ZenHub](https://files.zenhub.io/5522b7e04462991f6ae773dc)

**Comment by OlegKi** [comment]
So you have the problem **only in case of large number of items**? Is it so? In the case the solution which you originally posted (`$tbody.html().concat( rowData.join('') )`) will not help. I suppose that there are some limit in the size of array (`rowData`) which can be joint by the method `.join`. I suppose that it's the problem and not the problem with the total length of the produced string.

One can for example to merge all items of `rowData` to **one item** if the size of rowData will be larger as 32K items for example (`32768`). 

Could you try to modify the code of `addXmlData` / `addJSONData` so: one can include the lines
```JavaScript
if (rowData.length > 32768) {
    rowData = [rowData.join("")];
}
```
at the end of `while` loop which fills the data. I mean to insert the lines after `if (ir === rn) { break; }` line (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.base.js#L2535) and [the line](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.base.js#L2737)).

If you have the test data with large number of `rowData` items then you can just try whether the above changes will fix the problem in IE8. Could you try this please?

Thanks
Oleg

**Comment by ctrl11** [comment]
Actually, I was having this problem with one node and with many nodes of data, but I made the change as you asked, and I do not have this error anymore.  Also, the jqgrid treegrid seems a lot more responsive in IE8 after making the change for this issue and updating to include your other most recent changes.  The only other problem is that I get a dialog box with the message "Stop running this script? A script on this page is causing your web browser to run slowly.  If it continues to run, your computer might become unresponsive" at least two times while the jqgrid treegrid is loading.  I think the while loops to load my data are running too long for IE8.  Would it be possible to wrap these loops in setTimeoout to give the thread a break and avoid the long-running script message?  
(http://stackoverflow.com/questions/10312963/javascript-settimeout)  Sorry if that is a separate issue just let me know and I will open a new issue.  Thanks so much for your help with this.

**Comment by OlegKi** [comment]
First of all I want to solve your original problem. I included the changes described above in the code of free jqGrid (see [here](https://github.com/free-jqgrid/jqGrid/commit/f2fcedd687d0ad01d050b94f1af8b8c382625b66)). I introduced the new parameter `maxItemsToJoin` which default value is 32768. You can reload the sources which you use from github.

About performance problem. I don't think that `setTimout` could solve the problem. The first thing which one have to do if one have a performance problem is localizing the bottleneck. In the most case the bottleneck is *not in the main code of jqGrid*. Instead of that the wrong implemented `loadComplete` or `gridComplete` are the reason of the problem. Do you use the callbacks in jqGrid which get the long-running script message? If yes you should retry it (temporary) with commented `loadComplete` and `gridComplete`. Seconds you should verify that the same performance problem you have with `jquery.jqgrid.min.js`. The code which uses non-minimized version `jquery.jqgrid.src.js` is much slowly especially in old web browsers like IE8. The next experiment: you can include `loadComplete: function () { alert("Filling the grid time: " + this.p.totaltime + "ms"); }`. The `totaltime` parameter will be set by jqGrid. It measures the time of executing of the most expensive part of `addJSONData` / `addXmlData`. **Which value of `totaltime` you have in your tests?**. You can try to set new `maxItemsToJoin` parameter in the grid to `1000` and `10000` and compare the `totaltime` with `maxItemsToJoin: 32768` (the default value). It's very interesting for me the results of testing. Probably we should change the default value of the new `maxItemsToJoin` parameter.

One more common remark: if you would generate JSON results instead of XML you will improve the performance.

**Comment by ctrl11** [comment]
I did not write any code in the gridComplete event, so I have not included that in the tests.  Also, note that I cannot use the minified version of jquery.jqgrid.min.js because my code will not work if I use this minified code.

I did my best to run each test that you asked for, but if I missed something, please let me know.  In addition, the "Stop running this script" dialog appears two times in each test for IE8, which is an improvement over the number of times it used to appear before you implemented the maxItemsToJoin option, but it would be best if I could get rid of the "Stop running this script" dialog completely.

Filling the grid time:
Using non-minimized version jquery.jqgrid.src.js
With code in loadComplete
maxItemsToJoin = default
FireFox37 	4475ms
Chrome41  3719ms
IE8  		84293ms (Stop running this script dialog appears twice)

Using non-minimized version jquery.jqgrid.src.js
With comments in the code for loadComplete
maxItemsToJoin = default
FireFox37 	4459ms
Chrome41	3716ms
IE8		25149ms (Stop running this script dialog appears twice)
******************

Using non-minimized version jquery.jqgrid.src.js
With code in loadComplete
maxItemsToJoin = 1000
FireFox37 	4298ms
Chrome41	3344ms
IE8		17637ms (Stop running this script dialog appears twice)

Using non-minimized version jquery.jqgrid.src.js
With comments in the code for loadComplete
maxItemsToJoin = 1000
FireFox37 	5844ms
Chrome41	3221ms
IE8		34551ms (Stop running this script dialog appears twice)
******************

Using non-minimized version jquery.jqgrid.src.js
With code in loadComplete
maxItemsToJoin = 10,000
FireFox37 	3554ms
Chrome41	3172ms
IE8		17037ms (Stop running this script dialog appears twice)

Using non-minimized version jquery.jqgrid.src.js
With comments in the code for loadComplete
maxItemsToJoin = 10,000
FireFox37 	1983ms
Chrome41	3897ms
IE8		23328ms (Stop running this script dialog appears twice)

**Comment by OlegKi** [comment]
Thank you for your tests! Sorry, but I can't imagine why you code should work with `jquery.jqgrid.src.js`, but it will not work with `jquery.jqgrid.min.js` which corresponds the same `jquery.jqgrid.src.js`. The results should be identical. Could you provides the demo which can be used to reproduces the problem. If you don't want to place the URL in internet you can send it me via email: oleg.kiriljuk@ok-soft-gmbh.com.

By the way if the server response will be generated dynamically from the database you can just use [Fiddler](http://www.telerik.com/fiddler) or Developer Tools of IE/Chrome/Firefox to save the XML data from the server response in the separate file. One can use `url: "filename.xml"` instead of the URL to the server to reproduce the problem. I could debug the demo and pint you to the way to improve the performance.

**Comment by ctrl11** [comment]
I wish I could use JSON but I am also doing an XSLT transformation of the XML file on another web page, so I want to use the same data source in both places.  Also, the XML format is more readable for my end users, who might have to look at the source data.

I forgot that you have integrated maxItemsToJoin so I will run the same tests using the minified jquery.jqgrid.js file and respond in a separate message.

**Comment by ctrl11** [comment]
Okay.  I have emailed the test files to you.  Thanks in advance for any advice you can give me to avoid the Stop running this script" dialog from popping up.  Unfortunately, I was not able to get it working with jquery.jqgrid.min.js.  

In case someone else reads this thread, I should also mention the following details:
web browser: IE8
Win 7 SP1 64-bit 8GB RAM
jqgrid release 4.8.0 with patches applied (maxItemsToJoin)
jqgrid treeGridModel: adjacency
jqgrid datatype: 'xml'
number of data rows: about 2550
length of jqgrid rowData: 55946

**Comment by OlegKi** [comment]
One more clear way to make treegrid working quickly would be loading only visible items (12 items) at the beginning instead of loading all items at once. On the opening of the node jqGrid would send Ajax request to the same URL, but with three additional parameters nodeid, n_level, parented which identifying the opening node. The backend should returns only direct nods of the opening node. Such changing of communication between the server and jqGrid will improve the responsibility of TreeGrid dramatically.

Nevertheless I will change some parts of free jqGrid code so that the performance of loading all TreeGrid items should be improved too.

**Comment by OlegKi** [comment]
Hi! I updated some parts of jqGrid code which is responsible for loading of TreeGrid and improved additionally the time of XML processing. Please retry your tests. I hope that you will not see the message "Stop running this script" with the same size of input data. Please inform ma about the results.

**Comment by ctrl11** [comment]
Okay. Great!  Please give me a few days to run the tests again because I am in the middle of adding some other functionality to me project, but I will definitely get back to you.

**Comment by ctrl11** [comment]
I have run my (unscientific) tests again, and I have attached the results as an image.  (If you want to results in an Excel time, please email me.)  I have observed decreases in the time to fill the grid, but when running this in IE8, the "Stop running this script?" dialog box still pops up, although it only pops up one time.  I wish it were possible not to have the "Stop running this script?" dialog box pop up at all.
  
![free-jqgrid_tests](https://cloud.githubusercontent.com/assets/11810722/7120332/7b1443f8-e1da-11e4-80c1-b00f4709c8ad.JPG)

**Comment by OlegKi** [comment]
Hello! First of all I searched in Internet about the message "Stop running this script?" I found the article https://support.microsoft.com/en-us/kb/175500 which describes the DWORD registry key `MaxScriptStatements` under `HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Styles`. I could see that the setting on my test IE8 machine was increased as the part of corporate installation in the Virtual Machine. It's the reason why I didn't seen the message before.

I don't understand many rows from the table (the picture) which you included in your last comment. You send me via email one example of JavaScript code (one HTML page) and one test XML data for the TreeGrid with 2518 nodes. The code have **no `loadComplete` code** which could be commented. Commenting of `rowattr` don't make any practical changes in the performance. So I find not so important to make the tests. It can be that the code of `loadComplete` in the bottleneck of your solution and you should rewrite it (for example by using of `cellattr` instead of some parts of the current code). The code is unknown for me so I have to ignore the problem. In any way the problem seems be not a common free jqGrid problem.

The next unclear thing: why you made the tests with **non-minimized** code. I think that all productive solutions use only minimized code and so only minimized version of all JavaScript libraries should be used in all performance tests.

I made some changes in the code of TreeGrid in last days. I made the tests with free jqGrid 4.8 and the correct code from GitHub (`https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.min.js`). To be able to compare IE8 I used free jqGrid 4.8 with one post 4.8 fix to allow it run on IE8/IE9 (the code can be found under `http://www.ok-soft-gmbh.com/jqGrid/OK/jqGrid-ie8-fixed/jquery.jqGrid.min.js`). My results shows that **new/old code have improvement have the factor between 1,5 and 2 depend on web browser. So I'm very satisfied with the changes.** You can see the results of my tests below
````none
            free jqGrid 4.8      new free jqGrid code      factor new/old
Chrome           2.87 sec               1.48 sec                 2
IE10             7.9 sec                4.7 sec                  1.7
IE8             16.3 sec               10.8 sec                  1.5
````
I see clear performance advantages by the last changes in the code of free jqGrid. You can measure the time of loading jqGrid without the "Stop running this script?" message if you set DWORD registry key `MaxScriptStatements` to DWORD value `0xFFFFFFFF` under the registry key `HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Styles`.

I suggested you to load tree nodes on demand (lazy loading). It will full solve your problem. Sorry, but I don't see any other simple possibilities to solve your problem without much time investment.

Best regards
Oleg

**Comment by fletchsod-developer** [comment]
Good job on XML performance improvement!!

**Comment by OlegKi** [comment]
I analysed the processing of long XML file once more and can suggest you one more implementation scenario which improves the performance additionally. The modified code don't produced now the message "Stop running this script?" in IE8 in all my tests.

The idea of the improvement is the following: the processing of long XML time is still slowly especially in old IE like IE8. One of the reason is that is: the processing works not full sequential. One read some node  and then access to one or another subnode of the node. It takes additional time. So i suggest
 1. To load XML file via separate $.ajax call.
 2. Process the XML data sequenially inside of success callback of the $.ajax and create JavaScript object which contains the same dataset which exist in XML file
 3. create the grid with the JavaScript object as the input and `datatype: "jsonstring"` (or `datatype: "local"`). One can additionally do the creating of the grid inside of `setTimeout`.

The corresponding code will be for example the following
```JavaScript
$.ajax({
    url: gridFileUrl,
    dataType: 'xml',
    type: 'GET',
    success: function (xmlData) {
        var data = [], item = null, childNodes = xmlData.documentElement.childNodes,
            iNode, nNodes = childNodes.length, node;
        for (iNode = 0; iNode < nNodes; iNode++) {
            node = childNodes[iNode];
            if (node.nodeType === 1 && node.nodeName === "item") { // "item" used in your XML
                item = node;
                var itemChildNodes = item.childNodes, iSubNode, propNode,
                      nSubNodes = itemChildNodes.length, dataItem = {}, child;
                for (iSubNode = 0; iSubNode < nSubNodes; iSubNode++) {
                    // parse nodes which will be provide information for jqGrid columns
                    propNode = itemChildNodes[iSubNode];
                    if (propNode.nodeType === 1 && propNode.childNodes.length > 0) {
                        dataItem[propNode.nodeName] = propNode.childNodes[0].nodeValue;
                    }
                    // parse attributes like id
                    var attributes = item.attributes, iAttribute, attr,
                          nAttributes = attributes.length;
                    for (iAttribute = 0; iAttribute < nAttributes; iAttribute++) {
                        attr = attributes[iAttribute];
                        dataItem[attr.name] = attr.nodeValue;
                    }
                    data.push(dataItem);
                }
            }
        }
        setTimeout(function () {
            grid.jqGrid({
                treeGrid: true,
                datatype: 'local',
                data: data,
                ....
            });
        }, 50);
    }
});
```
As the result the total time was reduced in my tests to 7.5 sec in IE8 and to 3.3 in IE10.

**Comment by ctrl11** [comment]
1.  Some of my XML nodes are empty, which I wanted reflected as empty strings, so I changed the lines 
**if (propNode.nodeType === 1 && propNode.childNodes.length > 0) {
  dataItem[propNode.nodeName] = propNode.childNodes[0].nodeValue;
}**

to this:
**if (propNode.nodeType === 1) {
  dataItem[propNode.nodeName] = 
    propNode.childNodes.length > 0 ? propNode.childNodes[0].nodeValue : '';
}**

2.  Some of the non-leaf nodes were being duplicated by the given code, so insteading of having data.push(dataItem) right after the for(iAttribute = 0 …) loop, I moved it to be after the for (iSubNode = 0 …) loop.  It looks like this:
![image](https://cloud.githubusercontent.com/assets/11810722/7374792/513fe0fe-eda2-11e4-8b6d-253e60e68f18.png)

3.  This loop is not collecting the values for currentpage, totalpages, or totalrecords, and I did not see a need to do so, but you can easily add the code to collect those values if you need them.

4. To make this work, I also changed the xmlReader to localReader in the options for free-jqGrid, but I did not make any changes to the treeReader.

With these changes, I was able to use an XML file with free-jqGrid in IE8 without the slow-running script message appearing. I should note that I needed to use an XML file for other parts of my solution, otherwise I would not have chosen to use an XML file with free-jqGrid. I was a little concerned about reading all of this data into memory (in a previous message I noted the amount of data that I have), but it did work for this project. I am not sure if this solution will continue to work if I add more data, which is a shame because I think that free-jqGrid is most needed in projects where there is a lot of data.
