### ISSUE TITLE
Frozen and scroll set to true

### ISSUE THREAD

**Issue by littlesimon** [free-jqgrid/jqGrid#424]
Hi,
I saw there is some limitation when using frozen columns and scroll= true [http://www.trirand.com/jqgridwiki/doku.php?id=wiki:frozencolumns](url)
Is this still the case with free jqgrid?
Thank!

**Comment by OlegKi** [comment]
Many parts of frozen columns implementations is improved in free jqGrid. For example, one can use inline or cell editing. The performance is essential improved too. On the other side virtual scrolling (`scroll: true` or `scroll: 1`) isn't supported in combination with frozen columns. I don't recommend to use virtual scrolling at all. It brings a lot of disadvantages. I don't removed virtual scrolling, but it's probebly the only feature of jqGrid, which I don't recommend to use neither in old jqGrid (version <=4.7) nor in free jqGrid.

**Comment by littlesimon** [comment]
Thank for the anwser.
Does virtual scrolling will be supported for frozen columns in futur release of free jqgrid?

**Comment by OlegKi** [comment]
No, there are no plans to support virtual scrolling for frozen columns. Virtual scrolling have many disadvantages in the current implementation. I don't remove the feature only to simplify upgrade from old versions of jqGrid. Virtual scrolling will be not developed in the future till the implementation will be full rewritte, but I have no time to do that in the near future. I don't recommend to use virtual scrolling at all and to use standard paging instead. You need just set `rowNum` option to some small value, so that the user can see the page on the screen (something between 5 and 25 typically) and to add either `toppager: true` or `pager: true` option or both.

**Comment by littlesimon** [comment]
Thank for the anwser.
