### ISSUE TITLE
glyphicon not showing up

### ISSUE THREAD

**Issue by nopmania** [free-jqgrid/jqGrid#425]
Hi, free-jqGrid team,

I use jqGrid for my ASP.Net MVC and everything work fine in development environment.
But when i deploy in Production server as new "Application" under Default Web Site, the icons of jqGrid table such as create icon, edit icon, delete icon and refresh icon not showing up.

How can i resolve the problem?

Thank,

**Comment by OlegKi** [comment]
Please post only the issues, which can be reproduced and include more detailed information. Your current post don't include any JavaScript or any HTML code. The version of free jqGrid, jQuery, Bootstrap and so on are unknown too. Which version of ASP.NET MVC you use and how you deploy in Production is also unknown. How somebody could help you having the information?

In any way, I'd recommend you to look at examples of the usage of free jqGrid [here](https://free-jqgrid.github.io/getting-started/index.html). If you use Bootstrap 4 instead of Bootstrap 3 then you should use the option `guiStyle: "bootstrap4"` instead of `guiStyle: "bootstrap"`. Additionally, it's recommended to use [Font Awesome 4.x](https://fontawesome.com/v4.7.0/) because glyphicons are included in Bootstrap 3, but not in Bootstrap 4.

**Comment by nopmania** [comment]
@OlegKi Thank you very much.

I can solve the problem by copy images folder to the same level of bootstrap.css.
