### ISSUE TITLE
Multiselect , multiboxonly and bindKeys

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#426]
For demo : [https://jsfiddle.net/as0w6e11/](https://jsfiddle.net/as0w6e11/)

When i use arrow key up or down , behavior not is ok.

**Comment by OlegKi** [comment]
Could you describe the problem more exactly? Could you describe the test case step by step? **What is expected behavior** and what you see instead. To tell the trust I don't understand why such combination of options could be good. `multiboxonly` options is oriented on working with mouse only, but you use `bindKeys` for keyboard navigation.
