### ISSUE TITLE
i have a idea,also i need it.

### ISSUE THREAD

**Issue by Yancy1028** [free-jqgrid/jqGrid#456]
on column options,i can not return a dom.I need bind some events and attribute ,and i do it can running on  Vue,because i write a plugin. jqGrid is so bast,why us not to do it.

**Comment by OlegKi** [comment]
One of the main problem in writing plugins like jqGrid is performance. One have to reduce the number of changes on the DOM to improve the performance. Solution of the problem based on two main approaches: 

1. creating of content of large DOM elements as strings and placing the DOM fragment assigning `innerHTML` to the root element
2. using disconnecting DOM and document fragments

jqGrid uses the first approach. One uses formatter, custom formatters, `cellattr`, `rowattr` and other callbacks to fill the main body of the grid as array of strings, which represents rows of grid and then places the text on DOM assigning `innerHTML` (see [the line of code](https://github.com/free-jqgrid/jqGrid/blob/v4.15.5/js/grid.base.js#L4317)). Because of that callbacks like formatter, custom formatters, `cellattr` and `rowattr` have to return **string** instead of DOM.

If you need to use DOM manipulations, then you can use [jQuery.detach](https://api.jquery.com/detach/) to disconnect content of grid temporary from the page, then you can make any changes on DOM and connect it back to the page.
