### ISSUE TITLE
Height resize issue

### ISSUE THREAD

**Issue by cunnpole** [free-jqgrid/jqGrid#459]
If a height isn't specified at grid creation you get overlapping of the scrollbar when you then set a height:
https://jsfiddle.net/cunnpole/4ga1ekh3/146/

Uncomment line 34 and you'll see what I mean. This didn't affect ye olde 4.6. The workaround is simple (if you plan to set the height at any point, give it a height) but thought it might be worth raising as it now permanently leaves a space for the vertical scroll.

**Comment by cunnpole** [comment]
Also setting grid height with a string px value has the same undesirable behaviour. See line 39 here:
https://jsfiddle.net/cunnpole/4ga1ekh3/174/

**Comment by OlegKi** [comment]
I agree that it's a problem. As a workaround I suggest you to include additional call of `setGridWidth` after setting of the height with respect of `setGridHeight`. As the new `width` one can use the *current* width of the grid: 
```JavaScript
var $grid = $("#grid1");

$grid.setGridHeight(150);
$grid.jqGrid("setGridWidth", $grid.jqGrid("getGridParam", "width"), true);
```
See https://jsfiddle.net/OlegKi/23pdazx7/

P.S. Please use always only the last version of free jqGrid in demos (4.15.5 instead of 4.12.0).

**Comment by OlegKi** [comment]
I din't get any answer on my last comment since very long time. Thus I'm closing the issue.
