### ISSUE TITLE
Issue with checkbox formatter in the cellEdit mode

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#46]
Hi! Here are jsFiddles to test:

[free-jqgrid 4.8.0](http://jsfiddle.net/ovkadurin/r0rk2Lfo/)
_Steps to reproduce the issue_:
1. Click on any checkbox. Its formatter becomes type of "text". Supposed to be "checkbox"
2. Click on any checkbox in the "ckbx treeGrid" table. Then save or escape. Notice that a "leaf" icon disappeared
 
[jqgrid 4.6](http://jsfiddle.net/ovkadurin/srmzgafh/) (just to compare behaviour)
_Steps to reproduce the issue_:
1. Click on any cell but outside of a checkbox in the "ckbx" column.  Its formatter becomes type of "text". Supposed to be "checkbox"
2. Repeat a step 1 for the "ckbx treeGrid" table. Then save or escape. Notice that a "leaf" icon disappeared
 
Checkbox formatter acts strange when jqgrid is in the cellEdit mode. Does it works as expected or it's a bug?

**Comment by OlegKi** [comment]
Thank you for the demo and clear described test case! I wish me more bug/problem reports which are prepared so carefully. So I have to answer you immediately.

The problem is the following: The columns having `formatter: "checkbox"` don't have `edittype: "checkbox"`. The `formatter: "checkbox"` gives no information about editing. Adding of the setting fixes the problem. See  http://jsfiddle.net/OlegKi/r0rk2Lfo/12/.

I'd recommend you additionally to try `formatter: "checkboxFontAwesome4"` or even better `template: "booleanCheckboxFa"` and to remove `formatoptions: {disabled: false}`. In case of usage `template: "booleanCheckboxFa"` (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.8.0/js/jquery.fmatter.js#L87-L104)) you can remove some settings (like `align: "center"` and `edittype: "checkbox"`).

Editing of the column of TreeGrid which are used in `ExpandColumn: "name"` (or the first column by default) is not supported in any version of jqGrid. The usage of
```JavaScript
afterSaveCell: function (rowid, nm, v, iRow, iCol) {
    $(this).jqGrid("setTreeNode", iRow, iRow + 1);
}
```
can restore the icon after saving the text, but I think that it will work not in all cases. Even starting of editing of the node of the grid (I mean elements with `isLeaf: "false"`) will shows divs and spans (outerHTML) which is unneeded. One will have to use other callbacks of cell editing to remove unneeded HTML markup.

I want to make some changes in the implementation of TreeGrid which should allow editing and additionally will improve the performance of TreeGrid. I will inform you after I'll post the corresponding changes.

**Comment by okadurin** [comment]
Very thanks for quick reply! Now I see that `edittype: "checkbox"` resolves the issue. 
About disappearing of the icon. I decided to simplify the test case as much as possible. So I cut off all columns and left only one to test (further I added anothe "comments" column). So this issue is a kinda artificial. But now I knew that it's not supported of editing the "ExpandColumn" column.
I've just tested  `formatter: "checkboxFontAwesome4"` and `template: "booleanCheckboxFa"` - looks nice!

I have a question about `template: "booleanCheckboxFa"`.  Is it possible it acts like with setting `formatoptions: {disabled: false}` ? The difference is in the click count user should do to set value. In case of `template: "booleanCheckboxFa"` on the first click cell becomes editable and on the second click the value is set. On the other hand in case with `formatoptions: {disabled: false} ` it is needed to click only one time.

**Comment by OlegKi** [comment]
What you suggest seems very tricky and it means playing on the side effects of `edittype: "checkbox"`.

I would recommend you to try don't make the column with formatter: "checkbox" editable and to follow the solution which I suggested in [the answer](http://stackoverflow.com/a/24239416/315935). See [the demo](http://www.ok-soft-gmbh.com/jqGrid/EditableCheckbox.htm) or the modifications with message message box: http://www.ok-soft-gmbh.com/jqGrid/EditableCheckbox1.htm. It could solves your another problem in case of usage chechbox in the column used in "ExpandColumn" of TreeGrid.

**Comment by okadurin** [comment]
I got it. Thank you!
