### ISSUE TITLE
Context menu is not visible if right clicked in bottom of screen

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#48]
Trying to use create context menu from toolber buttons plugin.
if right clicked in bottom row which is in end of brower window, context menu is not fully visible: its part which is outside browser window is clipped.
Problebly context menu shoud adjust its position so that it is fully visible. If there are to many buttons, scroll bar and/or multi column context menu should appear.

Posted also a week ago in

http://stackoverflow.com/questions/29475962/how-to-show-full-createcontextmenufromtoolbarbuttons-in-free-jqgrid

**Comment by OlegKi** [comment]
The origin of the problem in `jquery.contextmenu-ui.js` used by `jquery.createcontexmenufromnavigatorbuttons.js`. I want to rewrite the code of `createContexMenuFromNavigatorButtons` to use jQuery UI Menu instead of `contextMenu` defined in `jquery.contextmenu-ui.js`. Nevertheless I made small improvements in the code of the plugin (see [the changes](https://github.com/free-jqgrid/jqGrid/commit/64d13728a74c2189846bc5a94a13c4fd4e6bc4dd)). The changes makes `jquery.contextmenu-ui.js` not perfect, but there should solve the main problems which you describes in the issue.

**Comment by kobruleht** [comment]
Thank yuo. I found tow issues in new code:  1. If there are more columns than fits to screen, clicking in right side of grid does not show full menu: 

![notv](https://cloud.githubusercontent.com/assets/1274923/7168876/55fc5448-e3c9-11e4-9ad8-33d785da7f66.png)

2. If last row is only partially visible, right click causes scrolling and makes last row fully visible.
