### ISSUE TITLE
How is ignoreCase option incorporated into customSortOperations method

### ISSUE THREAD

**Issue by MSIH** [free-jqgrid/jqGrid#54]
Is the ignoreCase option applied to the customSortOperations method, so the item and searchValue are automatically converted to the same case for comparison?

If not,

 1. how can I test for the ignoreCase option?
 2. I would like to make a feature request for this functionality

**Comment by OlegKi** [comment]
If you use case insensitive compare of two strings you should just convert both to upper case or to low case using `.toUpperCase()` or `.toLowerCase()`. The option `ignoreCase` do absolutely the same in case of the standard comparing.

The problem is that case insensitive compare *can't be implemented* for all languages. I recommend you to read [the answer](http://stackoverflow.com/a/29415927/315935). It's very important for understanding of the problem of case insensitive compare. Exactly because of that `customSortOperations` don't use `ignoreCase` option which is global for all columns. If you implement custom operation you can test the value of `ignoreCase` option (`this.p,ignoreCase`) and to add the call of `.toUpperCase()`. Automatic usage of `ignoreCase` option will break the possibility to implement of some scenarios.

**Comment by MSIH** [comment]
Thanks
