### ISSUE TITLE
Drop hardcoded CSS font-size

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#66]
Every time I'm upgrading free-jqGrid I'm commenting out every font-size properties from ui.jqgrid.css (because of Bootstrap and bootstrap wrapper for jqGrid I'm using). Maybe some method or attributes should be providen to set up those font sizes?

**Comment by OlegKi** [comment]
It's a wrong way you should *never modify* the original code of `ui.jqgrid.css`. Instead of that you should just create small CSS file with your modification, which you includes *after* the original `ui.jqgrid.css`. You can set any allowed value for the property (see [here](http://www.w3schools.com/cssref/pr_font_font-size.asp)). For example you can set `inherit` or `initial` value. In the way you will have no problem with including new version of `ui.jqgrid.css`.

By the way if you change the `font-size` you should probably modify some `padding` values. All the customization can be placed together in one file.

If you have some better suggestion for the setting of `font-size` - you are welcome. You should only think about compatibility with previous versions so that it should be not that other people will have to make many modifications in his code after updating to new version of free jqGrid.

**Comment by Wooya** [comment]
Ok, I've just thinking about font-size should be always inherited. Maybe I'm wrong, It's just my little suggestion.

**Comment by OlegKi** [comment]
Sorry, but it's definitively wrong. One design one component in one font size using all margin, padding, the size of icons the height of rows and so on. Then one can include the component on the page which use another font and it will work. I though to change `ui.jqgrid.css` to use `em` for jqGrid instead of `px`, but it's a lot of work in many places of the code and not in CSS only. If one use icons, then one should still use `px` values in case of usage fixed pixel icons like jQuery UI icons. In case of mixing texts and icons one have to be very careful.

In any way changing of jqGrid to `em` is the only way to inherited fonts. The current version can display good results only with the fixed tested font size `font-size: 11px;`. If another value looks good after your customization - it's fine, but try to set `font-size: 32px;` in `ui.jqgrid.css` and look on the results. Even if you will set 33% zoon in the web browser you will still not see the grid which looks good. The margins and paddings used in the grid will be not correct.

**Comment by Wooya** [comment]
Ok. Now I understand. Closing :)
