### ISSUE TITLE
Subgrid titlebar is thicker then parent grid titlebar in Firefox

### ISSUE THREAD

**Issue by zajc** [free-jqgrid/jqGrid#67]
Simple example is here: http://jsfiddle.net/Mlodey/2tkkqbeq/3/
If you check the code in Firefox (version 38), you can see thicker titlebar in subgirds.
The titlebar is 2 times thicker than in parent grid.
Everything works fine in Google Chrome. I find the same issue in 4.9.0 beta 1 version.
It looks like .css issue. I can't find a solution for this problem.

**Comment by OlegKi** [comment]
Thank you for the bug report. The problem exist because of usage `ui-helper-clearfix` class in the grid header. I find the class unneeded especially because the column header is not the first element in the grid. One could include it in gBox (the outer div which have the class `ui-jqgrid`), but it seem me not required too. I will make some additional tests and then commit the fix to github which will not use `ui-helper-clearfix` class in the grid title bar. The preliminary changes you can see [here](http://jsfiddle.net/OlegKi/2tkkqbeq/30/). The JavaScript code includes some changes which I test now, so I don't want to commit it just now. I will inform you after I makes the tests and after I will publish the changes on github.

**Comment by OlegKi** [comment]
I posted [the commit](https://github.com/free-jqgrid/jqGrid/commit/926ddd785c25818e42d8cb3693a17a986f4cbfc6). Please retry the code of 4.9.0 beta 1. The issue should be solved now.

**Comment by zajc** [comment]
Thanks. It works now.
