### ISSUE TITLE
PivotGrid - custom aggregate formmatter problem

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#74]
I think this is a fantastic feature for most developers who use pivot table.
There is a feature, which called `KPI`.

http://codepen.io/mrjumpy/pen/GJrjYM?editors=101
Look at the image. Here is the scenario:

If we want to know the price lower than 200 in the table, and changing its background color.
what should we do now?

The codepen is my implement.
You can found the problem:
We can't fill background, cause we can't get the DOM in the `formmatter` function.

We can collect the rowId and pos which is inside formmatter, 
and wait for the pivotGrid rendered done. 
after pivotGrid rendered done, then we rendered the cell's background. 
Just like the codepen that I implemented.
But, I think this flow is not appropriate.

Any idea?

**Comment by OlegKi** [comment]
I suppose that you never used `cellattr` before. `formatter`will be used to *format* the content of the cell. For example to format number by inserting dots and commas. What you need is to set *attribute* of the cells formatted using `formatter: "number"`. You need set `class` or `style` attribute on some from the cells.

So you should just remove the custom formatter and the modifications of DOM elements. Instead of that you need just use
````JavaScript
aggregates: [{
      width: 51,
      member: 'Price',
      aggregator: 'sum',
      label: 'Price',
      cellattr: function(rowId, cellValue) {
        if (parseFloat(cellValue) < 200) {
          return ' class="ui-state-error"';
        }
      }
  },
  ...
]
````
I used the standard jQuery UI class `ui-state-error` which looks good for every jQuery theme which you use. In the same way you can define your custom CSS rule which will overwrite the background color and you will have the same results.

**Comment by OlegKi** [comment]
see http://codepen.io/anon/pen/YXNbQE

**Comment by OlegKi** [comment]
It's better to us a little modified version of `cellattr`:
```JavaScript
cellattr: function(rowId, cellValue, rawObject, cm, rdata) {
    if (parseFloat(rdata[cm.name]) < 200) {
        return ' class="ui-state-error"';
    }
}
```
The main difference of the code to the previous one is the usage of `rdata[cm.name]` instead of `cellValue`. The problem is that `cellValue` is **formatted** value where one could have commas `,` instead of `.` used in the input data and so on. In case of usage of `autoResizable: true` option `cellValue` contains the wrapper, so the *formatted* data can looks like `"<span class='ui-jqgrid-cell-wrapper'>193.81</span>"` or `"<span class='ui-jqgrid-cell-wrapper'>193,81</span>"` depend on locale. In any way it would be wrong just to use `parseFloat(cellValue)` in the case. The object `rdata` represent the item of data which be read from the input data. The `cm` is the current column in `colModel`. Thus `rdata[cm.name]` get us **unformatted data** in locale independent format. Thus it's safe to use `parseFloat` in the case.

You can see the results on the next demo http://codepen.io/anon/pen/YXNbQE. One can see that some `0,00` value in the grid are not marked red. The reason is the input data don't contains any data for the column. If you would like to mark undefined input data in the same way red then you should be the following
```JavaScript
cellattr: function(rowId, cellValue, rawObject, cm, rdata) {
    var inputCellData = rdata[cm.name];
    if (inputCellData === undefined || parseFloat(inputCellData) < 200) {
        return ' class="ui-state-error"';
    }
}
```
see the next demo http://codepen.io/anon/pen/YXNbQE 

P.S. I consider to change the value of `cellValue` used in `cellattr` callback to make processing of data more easy. I think that introducing of new parameters which manage this would be the most flexible choice.

**Comment by OlegKi** [comment]
I change in the demo `totalText` to `footerText` in `xDimension` which is required after the last changes posted.

**Comment by mrjumpy** [comment]
I'm wondering if I want to get `yDimension.label` inside cellattr. How should I do?
Because we have a feature to do, for example.
Only when yDimension's label is 2011 along with xDimension label is `Baby`, then the cellattr return style and render it.

I could get `Baby` label or price/sum/total label, but I can't get any yDimension's label inside cellattr.
So I can't use if-else to separate cell that I don't want to render it.

You can see the Demo.
I left some comments in the cellattr. Hope it could get you more clear.
http://codepen.io/mrjumpy/pen/XbMBoZ?editors=001

**Comment by OlegKi** [comment]
It's absolutely correct question! I started already to add `xIndex` and `yIndex` to the grid data, but it was not what is really good to use. I added now new information in `rdata` (the last option of `cellattr`). The object contains now additional property `pivotInfos` which is object with many different information which could be helpful. All the information corresponds only the current row.

To get common information which corresponds to the whole grid one can use `pivotOptions` property of the grid. It is the pivot options (it has `aggregates`, `xDimension`, `yDimension` properties and all other) extended with tree additional properties:
- data - the original input data used to create pivot grid
- xIndex - index with all unique x values of input data with references to the original data
- yIndex - index with all unique y values of input data with references to the original data 

The `rdata.pivotInfos` contains information about all cells of the row. To get information about the cell one need get `rowPivotInfos[cm.name]`. The example below shows how one can get different information inside of `cellattr`:
```JavaScript
cellattr: function(rowId, cellValue, rawObject, cm, rdata) {
        var gridPivotInfos = this.p.pivotOptions,
            pivotInputData = gridPivotInfos.data,
            yIndex = gridPivotInfos.yIndex,
            xIndex = gridPivotInfos.xIndex,
            rowPivotInfos = rdata.pivotInfos,
            x = rowPivotInfos.x, // the same as xIndex[rowPivotInfos.iX]
            cellPivotInfos = rowPivotInfos[cm.name], // rowPivotInfos is undefined cuttenly for columns with total or group totals
            y = cellPivotInfos !== undefined ? cellPivotInfos.y : null,
            a = cellPivotInfos !== undefined ? cellPivotInfos.a : null, // gridPivotInfos.aggregates[cellPivotInfos.ia]
            iRows = cellPivotInfos !== undefined ? cellPivotInfos.iRows : null, // indexs of pivotInputData used in cell value
            rows = cellPivotInfos !== undefined ? cellPivotInfos.rows : null; // array of items of pivotInputData used in cell value

    ...
}
```
The last comment. The contain of the cell is the sum (or the result of some other aggregator) over **multiple** source items of data. `cellPivotInfos.rows` is the array with the source items used in calculation. One can examine any other properties of the items to get additional information.

**Comment by mrjumpy** [comment]
It's great!!
But, there's another request.
How can I get the data of header from table?
Just like:
$('#jqGrid').getHeader()
then, return the header data
{2011, 2015, 7, 12 etc...}

**Comment by mrjumpy** [comment]
Oops!!
If I'm increase xDimension to > 1.
There will be a bug here.
Take a look, please.
Thank you.
http://codepen.io/mrjumpy/pen/PqpvxB?editors=001

**Comment by OlegKi** [comment]
Thank you for the bug report. If was small problem in processing of grouping summary in jqGrid, but the most problem was in the demo.

I added `summaryType: function () { return "Subtotals:"; }` to the second `xDimension` item and 
added `summaryType: "sum"` to `aggregates` to have correct grouping summary.

I changed the code of `cellattr` so that it works correctly in case of `undefined` values of `rowId`, `rawObject` and `rdata`. It's the case of processing grouping summary by `cellattr`.

The code of `cellattr` is now the following
```JavaScript
cellattr: function(rowId, cellValue, rawObject, cm, rdata) {
    var gridPivotInfos = $(this).jqGrid("getGridParam", "pivotOptions"),
        pivotInputData = gridPivotInfos.data,
        yIndex = gridPivotInfos.yIndex,
        xIndex = gridPivotInfos.xIndex,
        rowPivotInfos = rdata != null ? rdata.pivotInfos : null,
        x = rowPivotInfos != null ? rowPivotInfos.x : null, // the same as xIndex[rowPivotInfos.iX]
        cellPivotInfos = rowPivotInfos != null ? rowPivotInfos[cm.name] : null, // rowPivotInfos is undefined cuttenly for columns with total or group totals
        y = cellPivotInfos != null ? cellPivotInfos.y : null,
        a = cellPivotInfos != null ? cellPivotInfos.a : null, // gridPivotInfos.aggregates[cellPivotInfos.ia]
        iRows = cellPivotInfos != null ? cellPivotInfos.iRows : null, // indexs of pivotInputData used in cell value
        rows = cellPivotInfos != null ? cellPivotInfos.rows : null; // array of items of pivotInputData used in cell value
  
    // The callback cellattr will be called to build grouping summary row too
    // One have rowId===undefined, rawObject===undefined, rdata===undefined in the case
    var inputData = rdata != null ? rdata[cm.name] : cellValue;
    if ((x != null && x[0] === "Baby") && (y != null && y[0] === "2011") && parseFloat(inputData) < 200) {
        return ' class="ui-state-error"';
    }
}
```
See the modified demo http://codepen.io/anon/pen/aOJeXg

Additionally I posed same additional modifications in jqPivot. Now it set additional properties in `pivonInfos`. I documented the property in the comment to [the merge](https://github.com/free-jqgrid/jqGrid/commit/bfd9a902904b7827f1c4945db9b6f499cc222030). I will include the information in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9) later.
