### ISSUE TITLE
Incorrect filter format being sent due to incorrect stringResult setting

### ISSUE THREAD

**Issue by springbok** [free-jqgrid/jqGrid#75]
I have a grid with datatype set to json, I do not set stringResult to true as my server code expects search values to sent as columName=filterValue. The problem is that when the grid is hidden when the page is loaded the following code is executed:

if (o.searchOperators || p.datatype === "local") { o.stringResult = true; }

By this stage p.datatype is set to 'local' as the grid is hidden, so stringResult is now true. When the grid is made visible the datatype is reset to json via this code:

if (hg) { p.datatype = tdt; populate.call(ts); hg = false; }

The problem is stringResult is not reset to it's original value which means all the filter values are sent as something like this:

"filters"=>"{\"groupOp\":\"AND\",\"rules\":[{\"field\":\"notes_note\",\"op\":\"bw\",\"data\":\"test\"}]}"

This is not what I was expecting, am I missing something?

**Comment by OlegKi** [comment]
Thank you for the bug report! The problem was: one have to use `stringResult: true` for local searching. I fixed the code now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/75c03c492d5fa18e63739f37f235a6254e95486f)) so that the initial value of `stringResult` will be not changed. Instead of that the test for `o.stringResult || o.searchOperators || p.datatype === "local"` will be used every time instead of just testing `o.stringResult`. I think that the format of searching parameters will be correct in all scenarios.

**Comment by springbok** [comment]
Hi Oleg, 

Thank you for your super fast response and fix it's much appreciated! I've tested the change and it works great.
