### ISSUE TITLE
scrollbar wrong position after setGridWidth 

### ISSUE THREAD

**Issue by GabrielMancik** [free-jqgrid/jqGrid#79]
My Grid have:
scroll: true,
loadonce: true
shrinkToFit: true
viewrecords: true

I am trying to set its width to fill the parent element with this code:
$("#reportGrid").setGridWidth($("#topContainer").width());

the result:
![image](https://cloud.githubusercontent.com/assets/12762648/8006195/c89208e6-0b91-11e5-963d-6b118c450ca5.png)

After manually resizing one column, the scrollbar appear in its correct position.

**Comment by OlegKi** [comment]
Sorry, but I'm not sure that I understand you correctly. Which position you mean? What is "its correct position"? The scroll bar exist on the correct place on the picture which you posted. Do you specified any fixed `width` parameter during *creating* the grid? Do you used `autowidth: true` option? The logic of grid resizing depends on whether you create the grid with "fixed sized" or not. You can try to set `autowidth: true` option before `$("#reportGrid").setGridWidth($("#topContainer").width());` for example.

If the above suggestions not help, I would ask you to post the demo and the test case which can be used to reproduce the problem.

**Comment by GabrielMancik** [comment]
the scrollbar should have its own column like this: 
![image](https://cloud.githubusercontent.com/assets/12762648/8006465/7f2a5c46-0b94-11e5-9328-20e32781f480.png)

but after using method setGridWidth it occupies the space of last column.

more set properties:
url: {something},
datatype: "json",
mtype: "GET",
pager: '#pager',
colNames: {something},
jsonReader: root: {something},
shrinkToFit: true,
rowNum: 40,
scroll: true,
loadonce: true,
gridview: true,
viewrecords: true,
height: 500,

Yes, I have some column set as fixed width. But removing this fixed setting does not resolve the problem.

I am affraid I cannot provide more code to look at.

**Comment by GabrielMancik** [comment]
autowidth: true does not help either

**Comment by OlegKi** [comment]
Sorry, but there are exist **no column for the scroll bar**. There are the body of the grid (the main table) and some outer divs. Old jqGrid just use static parameter `scrollOffset` with fixed value. Is the result one have empty place of the right side of simplest grid with one row. I try to determine *dynamically* whether the grid *with the data* have scroll bars or not. It could be not perfect, but **I can't help you if you don't post the demo which can be used to reproduce the problem**.

For example it's very important to know **when** you execute the code
```JavaScript
$("#reportGrid").setGridWidth($("#topContainer").width());
```
Changing the grid which have **no data** have not the same results like resizing the grid **filled with data** (for example inside of `loadComplete`). If you makes *manual* resizing of column you do it *after* the grid is already filled with data. So you have another results.

**Comment by OlegKi** [comment]
Is the problem still exist? I' like to publish version 4.9. I want to fix all reported bugs.

As I wrote, it's unclear for me **when** you change the width of the grid (using `$("#reportGrid").setGridWidth($("#topContainer").width());`): before or after the filling of data. You can change the width of grid multiple times.

You use `loadonce: true` option. So you wll have `datatype` equal to `"json"` during initial loading of data from the server and you will have it equal to `"loca"` later. So you can include `loadComplete` close the following
```JavaScript
loadComplete: function () {
    var $self = $(this);
    if ($self.jqGrid("getGridParam", "datatype") !== "local") {
        $self.jqGrid("setGridWidth", $("#topContainer").width());
    }
}
```
The above code will change the width *after* loading or reloading the data from the server. I hope that it will solve your problem.

**Comment by GabrielMancik** [comment]
I am not sure if we understand each other. Do you not see difference between the first and second picture in regards to scrollbar? It is true that first time i resize grid the data is not present in the table. But resizing grid is done when window is resizing. So I load the data, resize window which resizes grid (the second time, first time in window.onload when i have no data) and I have the scrollbar as you see it in the first picture. I will not be in the work for few days, so i cannot post any demo.

But this is not big problem for me at the moment. I have make it work consistent as you see it in the first picture. Just reporting :) So if you consider this to not be bug feel free to close the issue.

**Comment by OlegKi** [comment]
To decide whether it's a bug or not I have to know one thing which I marked fat multiple times in my comments. **when** (at what moment) you call `setGridWidth`?

It's important to understand, that scrollbar exist *not in the HTML table, btable (body table) which hold the main data, but in the outer div, so named bDiv.

The difference in two pictures which you posed is the following: the first picture have the width of the btable *the same* as the width of the outer div (bdiv) which have the scrollbar. I suspect that you make the call `$("#reportGrid").setGridWidth($("#topContainer").width());` **before** filling of the data. Such call inform jqGrid to set the width of btable and bdiv at the same value `$("#topContainer").width()`. If no data came later then such width will be really perfect. So the method `setGridWidth` do in the case exactly what you you asked.

If you would call `$("#reportGrid").setGridWidth($("#topContainer").width());` **after**  the data are filled and the scrollbar of bdiv is created then `setGridWidth` will reduce the width of btable to the width of scrollbar. jqGrid uses really the exact width of the toolbar in pixel. If you would use large zoom in Google Chrome for example than the width of the scrollbar will stay unchanged with the zoom and the scrollbar width in pixel will be relatively small (8-11px for example instead of 17-18 px under Zoom 100%). I want to say that the current code really calculate the width of scrollbar of bdiv and set the width of btable to the width of bdiv minus the width of scrollbar.

I hope that you understand now how `setGridWidth` work. So if the first picture was created in case of usage `setGridWidth` *before* filling and the second picture in case of usage `setGridWidth` *after* filling then there are no bug in the code. If you used another scenario, that it could be a bug. Because of that I repeat my question: **when** (at what moment, in which callback) you call `setGridWidth`?

I recommend you to call `setGridWidth` inside of `loadComplete` callback (see my previous comment).

If you understand the described above logic and you have suggestion how to change it and improve the look of jqGrid: your suggestions are welcome. You should take in consideration the compatibility with the old code. The call `setGridWidth` with specific width and specific value of `shrink` parameter means that the width of both bdiv and btable need be set. Should jqGrid change the width of btable automatically after the filling of the grid? Should be used the value of `shrink` parameter of the last `setGridWidth` call or the value of `shrinkToFit` option of jqGrid? In what situations (in which combinations of other parameters) should jqGrid uses the scenario? Or one should introduce one more parameter which force the re-resizing of btable after every filling? What is your opinion?

**Comment by GabrielMancik** [comment]
Thank you for the answer. I understand now how it works, and what you describe sound logical to me. So no problem there. 
I call setGridWidth multiple times. First time it is without the data (no records). This call produce first picture (I understand now that this is correct). Then I call setgridWidth again with data. But this call does not change first picture into second picture. 

You wrote: If you would call $("#reportGrid").setGridWidth($("#topContainer").width()); after the data are filled and the scrollbar of bdiv is created then setGridWidth will reduce the width of btable to the width of scrollbar. But in my scenario (where first time setgridWidth is call nothing is in table) this is not true.

**Comment by OlegKi** [comment]
You wrote "... Then I call setGridWidth again with data. But this call does not change first picture into second picture." It could be a bug. **Could you prepare small demo which reproduces the problem?**

I'm a little guardedly with changing the code of `setGridWidth` because there are exist really many different scenarios and one strategy is good for one case, but it's bad for another case. So I would ask you to post the demo which reproduces the problem. I want to decide after analyzing the test case whether it's better to change the code of free jqGrid to fix the problem or I would suggest you a workaround which will work in your case.

**Comment by OlegKi** [comment]
Please, could you prepare small demo which reproduces the problem? I plan to release version 4.9 at the weekend. If you could not post the demo till the time I will can't fix the problem in release 4.9. It's not a real problem because the sources from GitHub are full at any time, but the releases are mostly tested versions. So if you have time for it now, please send me the demo as soon as possible. Best regards.

**Comment by bkwdesign** [comment]
I maybe should open up a separate ticket for this, but, I'm also experiencing a scrollbar issue.. it changes from a correct position to an incorrect position during a mouse-wheel-scroll (i.e. during scrolling of the data table region)

It also jumps to an incorrect position if you place the cursor onto the vertical scrollbar and begin to drag down (thus, the vertical scrolling of the data table is then interrupted, because the scrollbar I had mouse-downed upon has now jettisoned out of view)

I've described it in some detail [here on Stack Overflow](http://stackoverflow.com/questions/38021570/jqgrids-sizing-behavior-changes-when-scrolling-through-a-large-set-of-records)

**Comment by OlegKi** [comment]
@bkwdesign 
Hi Brian! 

It would be better if you opens *separate issue* for the problem. Moreover it's really required that you prepare the demo, which reproduce the problem. It's unclear for me whether you have the problem with the usage of **mouse-wheel-scroll** only or there are some problem with virtual scrolling (`scroll: 1`) or you have a compatibility problem with the usage of free jqGrid and jQuery UI Layout, ...

I have to debug the demo to localize the problem. You use `loadonce: true`, thus it should be possible to reproduce the same problem with `datatype: "local"` and some local data.

I have an interest to fix any bugs existing in free jqGrid. One the other side from pragmatical point of view you can just use the standard paging (no virtual scrolling). The pictures, which you posted, displays 3245 rows of data. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-5000-25-free-jqgrid.htm) displays 5000 rows of data with 13 columns and 25 rows in a page. You can see the exact performance of local paging, sorting and filtering in milliseconds. [Another old demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-13-40000-20-free-jqgrid.htm) displays 40000 rows and it still work pretty good in modern web browsers. Virtual scrolling have many different technical problems. It's restricted to display about 66000 rows (see [the answer](http://stackoverflow.com/a/28255394/315935)) and some other implementation problems. I don't remove the feature from free jqGrid (it's almost the same like it was in jqGrid 4.7), I think that the implementation of virtual scrolling have to be full rewritten (which require the time for rewriting and testing). It's probably the only feature of jqGrid, which I don't recommend to use.

**Comment by bkwdesign** [comment]
Thanks @OlegKi. So, I've  created a jsFiddle and posted to this [stackoverflow's comment section](http://stackoverflow.com/questions/38021570/jqgrids-sizing-behavior-changes-when-scrolling-through-a-large-set-of-records), as well as [opened this new issue](https://github.com/free-jqgrid/jqGrid/issues/246) referring to both

**Comment by OlegKi** [comment]
The issue seems to be solved, but it was not closed before.
