### ISSUE TITLE
Custom Element

### ISSUE THREAD

**Issue by joelmontealegre** [free-jqgrid/jqGrid#94]
An undefined error is displayed when a column with edittype = 'custom' is edited.  The error must have been due to an unassigned variable customValue.  It can be corrected by assigning a value from the cm parameter.

case "custom":  // line 1149 of jquery.jqgrid.src.js
    try {
	customValue = cm.editoptions.custom_value;   // this is the fix
	if ($.isFunction(customValue)) {
		result = customValue.call($t, $dataFiled.find(".customelement"), "get");
		if (result === undefined) {
			throw "e2";
		}

**Comment by OlegKi** [comment]
Thank you very much for the bug report! The origin of the bug was [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0/js/grid.base.js#L1116) where I initialized `customValue` as `customValue = cm.custom_value` instead of `customValue = editoptions.custom_value`. I merged [the corresponding bug fix](https://github.com/free-jqgrid/jqGrid/commit/211117f4a7796d4feb26e943d4fd6a9f88e8a93c) just now. You need to reload the sources from GitHub. It's a petty that the fix is not included in the release 4.9.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!

**Comment by joelmontealegre** [comment]
Sorry for not closing. It's all right now. I thought it was the person who committed the changes and confirm the test result should be the who closes the issue. Next time I will. Thanks again.


Sent by Outlook for Android





On Fri, Jun 19, 2015 at 12:14 PM -0700, "Oleg Kiriljuk" <notifications@github.com> wrote:
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!

---

**Comment by OlegKi** [comment]
It's no problem. Just think about closing your issue in the future and I will be sure that the fix solved the original problem in your environments.

Thank you once more for reporting the issue! Please report all bugs and any suspected places in the future. Only in the way one can improve the code and increase there quality in different use cases.
