### ISSUE TITLE
datatype as function

### ISSUE THREAD

**Issue by john-w-watson** [free-jqgrid/jqGrid#97]
I'm new to jqGrid - using version 4.8.0.  I've got the datatype option set to a function.  While the grid is being constructed, it sets "p.datatype = p.datatype.toLowerCase()" (line 4437 or jquery.jqgrid.src.js).  This line fails when the datatype option is set to a function.  Everything appears to work correctly if I comment out this line of code.  Am I doing something wrong, or is this a defect?

**Comment by OlegKi** [comment]
First of all I recommend you to use free jqGrid [4.9.0](https://github.com/free-jqgrid/jqGrid/tree/v4.9.0) instead of 4.8.0. You can load it from GitHub or to use the corresponding URLs from CDN (see [the readme](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0/README.md) or [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs)). The problem with the usage of `datatype` as function is solved in the version 4.9.

Additionally I would remark that 99% of the code, which uses `datatype` as function. will be wrong used. If you use `jQuery.ajax` inside of the function then you should don't use the feature. Instead of that one can use `ajaxGridOptions`, `jsonReader` and `jsonmap` to full customize the Ajax request and to inform jqGrid how to fill the grid with the data from the server response. To say more I need to use the JavaScript code which you use and I need to know the exact format of data returned from the server.

**Comment by john-w-watson** [comment]
Thank you for the quick response.
